### PR TITLE
[BE] fix jacobian array differentiation

### PR DESCRIPTION
**Pull request by kabdelhak**
### Related Issues
 - fixes ticket #7550

### Purpose
 - problem: differentiation of arrays that have iteration as well as inner variables

### Approach
 - old behavior: if any of them is an iteration variable, the whole array cref is assumed to be
 - new behavior: if it contains both, it is scalarized and treated individually (just the cref!)
 - remaining issues: just works for vectors, higher dimension tensors will throw an error

### CODE REVIEW

**Review by mahge — APPROVED** [review]

**Comment by mahge** [comment]
LGTM. You might have just fixed a bunch of models. 

I think I have seen something similar for records. A whole record being differentiated. I am not sure if it falls in the same group but just a heads up if it was done unnecessarily and can be fixed. At least we will avoid confusing generated code if nothing else.

**Comment by mahge** [comment]
https://github.com/OpenModelica/OpenModelica/blob/328b4a8b94de6148c55a04b9fc0a575c2002672d/OMCompiler/Compiler/FrontEnd/Expression.mo#L4671

If you want to change a list to a multi dimensional array. ✌

**Comment by kabdelhak** [comment]
> https://github.com/OpenModelica/OpenModelica/blob/328b4a8b94de6148c55a04b9fc0a575c2002672d/OMCompiler/Compiler/FrontEnd/Expression.mo#L4671
> 
> If you want to change a list to a multi dimensional array. v

Do you mean this can be used for treating higher dimension tensors? If the scalarization of crefs has the same ordering logic it would be an easy addition using that function i guess.

**Comment by mahge** [comment]
Even better now.

**Pull request merged**
