### PR TITLE
ticket:5128 Added drag and drop for text layer

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-04-10_09-32-05](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6671/console).

**Comment by hkiel** [comment]
Could the relative path be added if holding down ALT key?

**Comment by atrosinenko** [comment]
Just as a note: Alt + mouse drag on Linux traditionally drags windows and this seems to be quite unconditional.

**Comment by adeas31** [comment]
@hkiel maybe you prefer some other key combination.

**Comment by hkiel** [comment]
@adeas31 The key is not really important. You can choose one that makes kind of sense - you only need to document that ;-)

**Comment by adeas31** [comment]
Forget about the key combination. It will automatically make the class name relative if inserting inside a package otherwise the full class name is used. See #141 

Actually we can do a lot more like default component name, prefixes etc. but for now just the class names are fine.

**Pull request closed without merging**
