### PR TITLE
Fix the Text(textColor = ...) annotation & re-enable it on icons

### PR DESCRIPTION
**Pull request by atrosinenko**
This PR implements handling of the `textColor` field of the `Text` graphical annotation. It also re-enables drawing of Text-s on component icons. 

@adeas31 Frankly speaking, I don't know why it was disabled. I understand why `%`s are prohibited (since these icons represent "classes", not instances), but why generally text is only allowed for functions?

How it looks like now (look at the `Complex` library icon):
library tree

### CODE REVIEW

**Comment by atrosinenko** [comment]
Please note that this PR introduces regression without OpenModelica/OMCompiler#3052.

**Comment by adeas31** [comment]
I think it is because the long strings doesn't look nice in Libraries Browser. For example try the following,
```
model M
  annotation (Icon(graphics={Rectangle(
          lineColor={160,160,164},
          fillColor={160,160,164},
          fillPattern=FillPattern.Solid,
          extent={{-100,-100},{100,100}},
          radius=25.0), Text(
          lineColor={255,255,255},
          extent={{-90,-50},{90,50}},
          textString="Long text string")}));
end M;
```

I checked how Dymola is handling it and it seems they only render if the text string is 2 characters long. So maybe we can also check for that.

I also think that if we are going to read `textColor` then we should also generate the `textColor` annotation when user makes custom models. Right now it is not super clear for me how it is intended to be used so I opened an issue https://github.com/modelica/ModelicaSpecification/issues/2346.

**Comment by atrosinenko** [comment]
Fixed the part about text length: added a configuration option for that since I usually use strings larger than two characters.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2019-04-15_15-59-19](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6681/).

**Comment by atrosinenko** [comment]
Technically, one can assume that something starting from '{' and ending in '}' is the color, not the font name (so `textColor` can be made an optional argument) but this seems too hacky for me...

**Comment by adeas31** [comment]
Am I missing something here? Why do we need that hack?

**Comment by atrosinenko** [comment]
Otherwise tests are really broken (`textColor = {-1, -1, -1}`). Or we should atomically commit this with proper **emitting** these `textColor`s, as you initially suggested.

**Comment by adeas31** [comment]
I think instead of hacking anything we should update the tests. Its fine to have `{-1, -1, -1}` in the output. You already made OMEdit aware of it.

**Comment by atrosinenko** [comment]
But as I understand, it is the `textColor` that is the preferred way to express color of the text label now. So this would work when reading OMEdit-generated files in OMEdit, but not in other implementations. Or is some other code really used when creating diagrams?

Frankly speaking, I plainly forget to check write-side when improving the read-side. :(

**Comment by adeas31** [comment]
`ShapeAnnotation::getShapeAnnotation()` is used for writing. Since you are updating the value of `mLineColor` so I guess it is fine. OMEdit can read the new preferred way as well as the old but will still write in old style. Maybe we can also update that OMEdit always writes both `lineColor` and `textColor`.

I suggest don't use the value of `textColor` for `mFillColor` as fill settings are totally ignored for text annotations.

**Comment by atrosinenko** [comment]
> I suggest don't use the value of textColor for mFillColor as fill settings are totally ignored for text annotations.

Looks like this is true. In the Modelica Language Specification v3.4 - 18.6.4 they say
```modelica
record Text
...
  Color textColor=lineColor;
...
end Text;
```
and 
> The contents inherited from FilledShape is deprecated

**Comment by atrosinenko** [comment]
After all, the old contents of `fillColor` would probably even more safe without this updating.

**Comment by atrosinenko** [comment]
I fixed (not-) setting the `mFillColor`. What is the preferred way to run separate tests for the debugging purposes?

**Comment by adeas31** [comment]
Testsuite is now part of OpenModelica.git so update the tests with this PR.

**Comment by atrosinenko** [comment]
I want to say, is there some simple one-command way to run specific tests that everyone use? Can I at any time simply run `make` in the `testsuite` directory and get a good approximation of what I get on build server or should I first collect some reference results?

**Comment by adeas31** [comment]
Well you can run the testsuite on your machine with make as you said and it will tell you which tests are failing. I think most developers just run testsuite via build server as is way much faster. In this PR we already have the reference tests just update them and make a commit.

**Comment by atrosinenko** [comment]
Technically, I have updated them, but not sure it is not fitting tests to ignore real errors.

**Comment by adeas31** [comment]
I have started Hudson. We will see.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-04-16_20-38-18](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6684/console).

**Comment by atrosinenko** [comment]
Thanks!

**Comment by adrpo** [comment]
For testing you can just run testsuite/partest/runtests.pl

**Pull request closed without merging**
