### PR TITLE
Implemented cut copy paste functionality for graphical items

### PR DESCRIPTION
**Pull request by adeas31**
Fixes ticket:3776

### CODE REVIEW

**Comment by JKRT** [comment]
@adeas31 

I added @casella as the reviewer of this : )

**Comment by casella** [comment]
That's great news. Unfortunately I cannot compile OMC from source, so I can't test a feature which is on @adeas31's branch. I'd like to test it on a nightly. Is this reliable enough to push it on master before the 1.14.0 beta1 release, or should we keep it for 2.0.0?

**Comment by adeas31** [comment]
Yes we can push it in master for 1.14. It should be fine.

**Comment by casella** [comment]
Great! I'll check tomorrow with the nightly build and report.

**Pull request merged**
