### PR TITLE
Add external TLM models to OMSimulator models

### PR DESCRIPTION
**Pull request by robbr48**
### Purpose

Add new external TLM models to OMSimulator models.

### Approach

Similar to how FMU submodels are added. Accessed from toolbuttons or context menu, with a dialog for choosing model path, start script and name. 

This requires OpenModelica/OMSimulator#700

### CODE REVIEW

**Comment by adeas31** [comment]
We can somehow accommodate this in the existing submodel addition routines. I don't like the idea that we need to create new classes just for that. My proposal is to use the same interface since that is used for adding fmus and tables. We can extend it for external models. The only thing external models require is start script argument.

**Comment by robbr48** [comment]
@adeas31 I changed the implementation to use the existing classes. It only asks for a script file if current system is of TLM type, and allows all file formats if so. Else, only submodel types are allowed.

**Comment by adeas31** [comment]
I have no idea why the tests are failing for this PR. @sjoelund do you have any hint?
@robbr48 maybe you need to rebase.

**Comment by sjoelund** [comment]
It's omsi / OMSimulator tests that fail https://test.openmodelica.org/jenkins/job/OpenModelica/view/change-requests/job/PR-303/lastCompletedBuild/testReport/
Does it still fail without the OMSimulator submodule changes?

**Comment by robbr48** [comment]
I believe I fixed the error in OMSimulator. There is also a PR in the submodule that needs to be merged before this one.

**Comment by adeas31** [comment]
@robbr48 I believe you need to update the OMSimulator submodule to the latest commit otherwise OMEdit can't find `oms_getExternalModelInfo`.

**Comment by robbr48** [comment]
@adeas31 I have updated the submodule and the tests are successful. I think this can be merged.

**Pull request merged**
