### PR TITLE
Never select CSE vars in minimalTearing

### PR DESCRIPTION
**Pull request by phannebohm**
Addresses issue #7800
Continuation of PR #8049

### CODE REVIEW

**Comment by phannebohm** [comment]
Idk what happened here. The tests are fine but `fmuchecker-results` fails with the message
`Failed to extract omc-clang.tar.gz`

@adrpo, @sjoelund any help? Something with Jenkins maybe?

**Comment by sjoelund** [comment]
> Idk what happened here. The tests are fine but `fmuchecker-results` fails with the message `Failed to extract omc-clang.tar.gz`
> 
> @adrpo, @sjoelund any help? Something with Jenkins maybe?

I don't have time to check the logs from my phone, but maybe one machine is running out of disk space?

**Comment by phannebohm** [comment]
Whatever it is, it's persistent. A rerun gave the same error, but it can't be related to my changes, can it?

**Comment by casella** [comment]
No regressions in the [library testsuite report](https://libraries.openmodelica.org/branches/history/master/2021-11-11%2011:51:16..2021-11-11%2022:54:30.html). Good!

**Pull request merged**
