### PR TITLE
[OMEdit] Additional parameters for vector scaling

### PR DESCRIPTION
**Pull request by anotheruserofgithub**
### Purpose

This PR provides new parameters for the vector scaling heuristics introduced in #9389 in order to be fully customizable and handle time-varying lengths.
Some refactoring was involved to also remove duplicate code and improve data privacy.

### Approach

Additions to the length scale adjustment by providing [two new parameters](https://github.com/OpenModelica/OpenModelica/pull/9428/commits/d2e49b3c3fd9c82fc289d96bfb2a14afd0270f9c#diff-003ee05536a1844c1876692266cec5626d4a656eaa622da88191b5ffcf95d3d6R745-R746), one for each of the constraints, along with [a bit of documentation](https://github.com/OpenModelica/OpenModelica/pull/9428/commits/d2e49b3c3fd9c82fc289d96bfb2a14afd0270f9c#diff-003ee05536a1844c1876692266cec5626d4a656eaa622da88191b5ffcf95d3d6R706-R711).
This way, each constraint can be separately enabled/disabled, and also time-varying vector lengths can be efficiently accounted for.

### Tests

- `Modelica.Mechanics.MultiBody.Examples.Elementary.ForceAndTorque`
- Below model containing only visualizers (shapes and vectors), identical to the one in #9389 except for an additional setting
<details><summary>TestScalingVectorVisualizers.mo (click to expand)</summary>

```modelica
model TestScalingVectorVisualizers "Demonstrate animation of vector visualizers with automatic scaling"
  constant Boolean testMinimumLengthConstraint=true;
  constant Boolean testTimeVaryingLengths=true;
  import MB = Modelica.Mechanics.MultiBody;
  inner MB.World world;
  MB.Visualizers.Advanced.Shape s1(
    shapeType="cylinder",
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    r_shape={0,0,0},
    lengthDirection={-1,0,0},
    widthDirection={0,1,0},
    length=0.45,
    width=0.035,
    height=0.035,
    extra=0.0,
    color={255,0,0},
    specularCoefficient=0.7
  );
  MB.Visualizers.Advanced.Shape s2(
    shapeType="cylinder",
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    r_shape={0,0,0},
    lengthDirection={-1,0,0},
    widthDirection={0,1,0},
    length=0.45,
    width=0.035,
    height=0.035,
    extra=0.0,
    color={255,0,0},
    specularCoefficient=0.7
  );
  MB.Visualizers.Advanced.Shape s3(
    shapeType="cylinder",
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    r_shape={0,0,0},
    lengthDirection={-1,0,0},
    widthDirection={0,1,0},
    length=0.45,
    width=0.035,
    height=0.035,
    extra=0.0,
    color={255,0,0},
    specularCoefficient=0.7
  );
  MB.Visualizers.Advanced.Shape s4(
    shapeType="cylinder",
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    r_shape={0,0,0},
    lengthDirection={-1,0,0},
    widthDirection={0,1,0},
    length=0.45,
    width=0.035,
    height=0.035,
    extra=0.0,
    color={255,0,0},
    specularCoefficient=0.7
  );
  MB.Visualizers.Advanced.Shape s5(
    shapeType="cylinder",
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    r_shape={0,0,0},
    lengthDirection={-1,0,0},
    widthDirection={0,1,0},
    length=0.45,
    width=0.035,
    height=0.035,
    extra=0.0,
    color={255,0,0},
    specularCoefficient=0.7
  );
  MB.Visualizers.Advanced.Vector v1(
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    coordinates={(time+1)*1200,0,0},
    color={0,0,255},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Force,
    headAtOrigin=false,
    twoHeadedArrow=false
  );
  MB.Visualizers.Advanced.Vector v2(
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    coordinates={-(time+1)*120,0,0},
    color={0,255,0},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Torque,
    headAtOrigin=false,
    twoHeadedArrow=false
  );
  MB.Visualizers.Advanced.Vector v3(
    R=MB.Frames.nullRotation(),
    r={0,0.1,0},
    coordinates=if testTimeVaryingLengths then {(1/(time+1))*2*1200,0,0} else {(time+1)*2*1200,0,0},
    color={0,0,255},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Force,
    headAtOrigin=true,
    twoHeadedArrow=true
  );
  MB.Visualizers.Advanced.Vector v4(
    R=MB.Frames.nullRotation(),
    r={0,0.1,0},
    coordinates=if testTimeVaryingLengths then {-(1/(time+1))*2*120,0,0} else {-(time+1)*2*120,0,0},
    color={0,255,0},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Torque,
    headAtOrigin=true,
    twoHeadedArrow=true
  );
  MB.Visualizers.Advanced.Vector v5(
    R=MB.Frames.nullRotation(),
    r={0,0.2,0},
    coordinates={(time+1)*8*1200,0,0},
    color={0,0,255},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Force,
    headAtOrigin=false,
    twoHeadedArrow=false
  ) if testMinimumLengthConstraint;
  MB.Visualizers.Advanced.Vector v6(
    R=MB.Frames.nullRotation(),
    r={0,0.2,0},
    coordinates={-(time+1)*8*120,0,0},
    color={0,255,0},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Torque,
    headAtOrigin=false,
    twoHeadedArrow=false
  ) if testMinimumLengthConstraint;
  MB.Visualizers.Advanced.Vector v7(
    R=MB.Frames.nullRotation(),
    r={-0.1,0.3,0},
    coordinates={-1,2,0},
    color={255,0,255},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Velocity,
    headAtOrigin=false,
    twoHeadedArrow=false
  );
  MB.Visualizers.Advanced.Vector v8(
    R=MB.Frames.nullRotation(),
    r={-0.1,0.3,0},
    coordinates={-2,1,0},
    color={255,255,0},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Acceleration,
    headAtOrigin=false,
    twoHeadedArrow=true
  );
  MB.Visualizers.Advanced.Vector v9(
    R=MB.Frames.nullRotation(),
    r={-0.1,-0.2,0},
    coordinates={-1,-2,0},
    color={255,0,155},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.AngularVelocity,
    headAtOrigin=false,
    twoHeadedArrow=false
  );
  MB.Visualizers.Advanced.Vector v10(
    R=MB.Frames.nullRotation(),
    r={-0.1,-0.2,0},
    coordinates={-2,-1,0},
    color={255,155,0},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.AngularAcceleration,
    headAtOrigin=false,
    twoHeadedArrow=true
  );
  MB.Visualizers.Advanced.Vector v11(
    R=MB.Frames.nullRotation(),
    r={0,-0.25,0},
    coordinates={0.5,0.75,0},
    color={0,255,255},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.RelativePosition,
    headAtOrigin=false,
    twoHeadedArrow=false
  );
end TestScalingVectorVisualizers;
```
</details>

### Related Issues

- Fixes "TODO" in PR #9389
- Complementary fix for #8211
- Proposal for custom annotations in #9390
- MSL discussion on scaling vectors by tools: modelica/ModelicaStandardLibrary#3991
- MSL `ForceAndTorque` model has color issue: modelica/ModelicaStandardLibrary#3989

### CODE REVIEW

**Comment by anotheruserofgithub** [comment]
@adeas31 This should also go in v1.20, but should be rebased on #9389 after the latter is merged in master.

**Comment by anotheruserofgithub** [comment]
This one too is ready, once checks pass ;)

**Comment by anotheruserofgithub** [comment]
I don't know why the CLA check is blocked. Should I do something?

**Comment by anotheruserofgithub** [comment]
@adeas31 Did you have time to review it?

**Review by adeas31 — APPROVED** [review]
Looks good.

**Comment by anotheruserofgithub** [comment]
Thank you very much!

**Pull request merged**
