### PR TITLE
ticket:5927 fix the crash in linearization for Matlab

### PR DESCRIPTION
**Pull request by adrpo**
- %g was given a string
- remove trailing spaces before \n in CodegenC.tpl
- update test

### CODE REVIEW

**Comment by adrpo** [comment]
@kabdelhak maybe you can do it better, have `Ts` for all the languages as currently it seems to be used only by Matlab.

**Comment by kabdelhak** [comment]
> @kabdelhak maybe you can do it better, have `Ts` for all the languages as currently it seems to be used only by Matlab.

I will have a look tomorrow!

**Comment by adrpo** [comment]
@kabdelhak the help that you get is a bit misleading: 

```
stdout            | info    | The output format can be changed with the command line option --linearizationDumpLanguage.
stdout            | info    | The options are: --linearizationDumpLanguage=modelica, matlab, julia, python.
```
I thought the executable had this flag as the executable shown this, but you need to do this via OMC and recompile.

I think it would just be possible (and nice) to provide the linearization for all the languages we have in the same exe, just switch inside this function based on the language.
```
const char *<%symbolName(modelNamePrefix,"linear_model_frame")%>(int language)
if language==matlab return matlabString;
if language==julia return juliaString;
...
```

**Comment by kabdelhak** [comment]
> I think it would just be possible (and nice) to provide the linearization for all the languages we have in the same exe, just switch inside this function based on the language.

Ah i see what you mean, sure we can do that. So it should be a runtime flag instead of a compiler flag?

**Comment by adrpo** [comment]
Basically ... yes. But don't bother now, later after 1.16.

**Comment by casella** [comment]
@kabdelhak, @adrpo, this is no big deal, but if we already plan to change the interface, switching from compiler flag to simulation flag, it would be better to do so before the release. Otherwise we'll later  have backwards compatibility issues, or otherwise we'd need to keep unnecessary duplicate flags.

**Pull request merged**
