### PR TITLE
[OMCompiler] Fix some leaks in C runtime

### PR DESCRIPTION
**Pull request by jschueller**
backport from #7441 cc @AnHeuermann

### CODE REVIEW

**Comment by AnHeuermann** [comment]
What is the other commit you need so less memory is leaked?
Is it cc713acc3daeaebdb8770cc56d13ba0057ff9810 or an additional one?

**Comment by jschueller** [comment]
It was the one from https://github.com/OpenModelica/OpenModelica/pull/7141

**Comment by AnHeuermann** [comment]
I'll create a PR to backport it.

**Review by AnHeuermann — APPROVED** [review]

**Comment by jschueller** [comment]
it passed now

**Pull request merged**
