### PR TITLE
Codegen/record and array improvments 2

### PR DESCRIPTION
**Pull request by mahge**
[CG,Boot] Add element size to the runtime array representation.

  - We now store the element size in the array.
    - A number of allocation functions have been updated accordingly.
    - There might still be some left here and there. We need to see
      testsuite results.

  - Bootstrap tarball is updated!

### CODE REVIEW

**Comment by sjoelund** [comment]
Why do you need to update the bootstrapping tarball? This almost never needs to be done and is usually fixed by some ifdefs

**Comment by mahge** [comment]
@sjoelund I am not sure actually. It can probably be avoided. I would like to avoid it if I can. This is just to run the testsuite for now. 99+ tests will fail anyway.

The general reason is that now I have changed the array structure in the run-time. It has _element size_ stored inside it. This means array accesses and copy now use the stored size to know offsets. Since the bootstrap sources do not include the run-time/c files they do not match anymore.

In general this should not affect MetaModelica and bootstraping. However, Modelica style array declarations such as this are allowed in MetaModelica

`Integer[N] a;
`

These use the normal run-time array.

Specifically there is just two cases so far in the compiler where this is done. _Config.mo_ has two array declarations like these.

https://github.com/OpenModelica/OpenModelica/blob/201d5a1ba412e7d9f114b7d98014155bf1ff5ce1/OMCompiler/Compiler/Util/Config.mo#L468

https://github.com/OpenModelica/OpenModelica/blob/201d5a1ba412e7d9f114b7d98014155bf1ff5ce1/OMCompiler/Compiler/Util/Config.mo#L492

These generate array literals with the old structure like this

```
static string_array const _OMC_LIT130 = {
  1, _OMC_LIT130_dims, (void*) _OMC_LIT130_data, (modelica_boolean) 0
};

```

Which can not compile since the run-time now has a different representation.  It expects this:

```
static string_array const _OMC_LIT130 = {
  1, _OMC_LIT130_dims, sizeof(modelica_string), (void*) _OMC_LIT130_data, (modelica_boolean) 0
};
```

My first thought was to change the Config.mo in order to not generate the literals. But then I realized that as long as this array declaration and usage is allowed people might use it. That means CodegenCFunctions needs to be updated in the bootstrap sources anyway.

Maybe we should not allow Modelica style array declaration such as `Integer[N] a1;` in MetaModelica and always use 
```
array<Integer> a;
...
a := arrayCreate(a, 0);
```

Or maybe there is another way. I am not sure really.

**Comment by sjoelund** [comment]
It's always possible to patch only certain files in the sources. But the patched files will generate the old code as well. So perhaps it needs an #ifdef for bootstrapping stages to implement some simple version of this. Or perhaps simply a sed command at stage 2 to fix that config flags line.

**Comment by mahge** [comment]
Ya it is easy to change Config.mo to avoid this specific case. However if people write this in other files we might have to keep patching those files as well. 

So
1 - We sed and update all the array literals in stage 1 after extraction
2 - Then we patch codeGenCfunctions.c so that the bootstrapped compiler can generate correct code for stage 2.

is this correct? I am not sure about the #ifdefs.

I think it might be better to separate MetaModelica and normal run-time and just forbid those Modelica style declarations. They are not used that much anyway. Then bootstrapping would not care about Modelica array representations of the run-time system. Another option is to include some stable versions of rutime/c files in the bootstrap sources

It is also confusing to have two _incompatible_ array representations.

**Comment by mahge** [comment]
This issue has been postponed and will be revisited later.

**Pull request closed without merging**
