### PR TITLE
Fixing compilation error on MSVC

### PR DESCRIPTION
**Pull request by AnHeuermann**
- Error: cannot allocate an array of constant size 0
  - Make sure allocating size greater then 0

### CODE REVIEW

**Comment by mahge** [comment]
I do not think the issue is zero size arrays. It is that **variable size arrays** are not allowed in C89/90. MSVC is C89 and does not support variable size arrays. GCC supports them as default enabled extension (and also if you specify).

It does not matter what size the array is. In C you are only allowed to allocate arrays of known sizes at compilation time. The error message in the original PR might be confusing.

**Comment by AnHeuermann** [comment]
Yes, my description is a bit confusing.

**Comment by AnHeuermann** [comment]
Related to https://github.com/OpenModelica/OpenModelica/pull/7039

**Review by adrpo — APPROVED** [review]
LGTM!

**Pull request merged**
