### PR TITLE
Differentiate homotopy operator with lambda

### PR DESCRIPTION
**Pull request by AnHeuermann**
For [trac ticket 6328](https://trac.openmodelica.org/OpenModelica/ticket/6328).

Before we only differentiated the `actual` expression.
Now we will differentiate `lambda*actual + (1-lambda)*simplified`.

### CODE REVIEW

**Review by casella — COMMENTED** [review]
@AnHeuermann, of course you differentiate homotopy only for the `initial` set of equations, not for the `initial-lambda0`, where `homotopy()` is replaced by its `simplified` argument, nor for the `regular` set of equations, where `homotopy()` is replaced by its `actual` argument. Right?

**Comment by AnHeuermann** [comment]
> Right?

:grimacing: I'm not so sure.
From `-d=symjacdump` I can see that we generate Jacobians for
```
1/1 (1): $res_NLSJac0_2 := y1 + homotopy(sin(y1), y1) + homotopy(sin(y2), y2) - y2
2/2 (1): $res_NLSJac0_1 := -1.0 + y1 + homotopy(sin(y1), y1) + y2 + homotopy(sin(y2), y2)
```

```
1/1 (1): $res_LSJac1_2 := 2.0 * y1
2/2 (1): $res_LSJac1_1 := -1.0 + 2.0 * (y1 + y2)
```
and
```
1/1 (1): $res_NLSJac2_4 := -1.0 + y1 + $cse3 + y2 + $cse4
2/2 (1): $res_NLSJac2_3 := sin(y1) - $cse3
3/3 (1): $res_NLSJac2_2 := y1 + $cse3 + $cse4 - y2
4/4 (1): $res_NLSJac2_1 := sin(y2) - $cse4
```
and all three seem to be correct.

When looking at SimCode it seems to be correct as well:
```
*********************
* SimCode Equations *
*********************


allEquations:
========================================

23:  (NONLINEAR) index:1 jacobian: true
crefs: y1 , $cse3 , $cse4 , y2
	16: sin(y2) - $cse4 (RESIDUAL)
	15: $cse4 - y2 + $cse3 + y1 (RESIDUAL)
	14: sin(y1) - $cse3 (RESIDUAL)
	13: -1.0 + y1 + $cse3 + y2 + $cse4 (RESIDUAL)
	Jacobian idx: 2
	17: $cse5=cos(y1) [Real]
	18: $cse6=cos(y2) [Real]
	19: $res_NLSJac2_1.$pDERNLSJac2.dummyVarNLSJac2=$cse6 * y2.SeedNLSJac2 - $cse4.SeedNLSJac2 [Real]
	20: $res_NLSJac2_2.$pDERNLSJac2.dummyVarNLSJac2=y1.SeedNLSJac2 + $cse3.SeedNLSJac2 + $cse4.SeedNLSJac2 - y2.SeedNLSJac2 [Real]
	21: $res_NLSJac2_3.$pDERNLSJac2.dummyVarNLSJac2=$cse5 * y1.SeedNLSJac2 - $cse3.SeedNLSJac2 [Real]
	22: $res_NLSJac2_4.$pDERNLSJac2.dummyVarNLSJac2=y1.SeedNLSJac2 + $cse3.SeedNLSJac2 + y2.SeedNLSJac2 + $cse4.SeedNLSJac2 [Real]
	
columnVars(6)
----------------------
index:0: $cse6 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
index:1: $cse5 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
index:3: $res_NLSJac2_4.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
index:2: $res_NLSJac2_3.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
index:1: $res_NLSJac2_2.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
index:0: $res_NLSJac2_1.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []

========================================



odeEquations (0 systems):
========================================
========================================



algebraicEquations (1 systems):
========================================
23:  (NONLINEAR) index:1 jacobian: true
crefs: y1 , $cse3 , $cse4 , y2
	16: sin(y2) - $cse4 (RESIDUAL)
	15: $cse4 - y2 + $cse3 + y1 (RESIDUAL)
	14: sin(y1) - $cse3 (RESIDUAL)
	13: -1.0 + y1 + $cse3 + y2 + $cse4 (RESIDUAL)
	Jacobian idx: -1
	17: $cse5=cos(y1) [Real]
	18: $cse6=cos(y2) [Real]
	19: $res_NLSJac2_1.$pDERNLSJac2.dummyVarNLSJac2=$cse6 * y2.SeedNLSJac2 - $cse4.SeedNLSJac2 [Real]
	20: $res_NLSJac2_2.$pDERNLSJac2.dummyVarNLSJac2=y1.SeedNLSJac2 + $cse3.SeedNLSJac2 + $cse4.SeedNLSJac2 - y2.SeedNLSJac2 [Real]
	21: $res_NLSJac2_3.$pDERNLSJac2.dummyVarNLSJac2=$cse5 * y1.SeedNLSJac2 - $cse3.SeedNLSJac2 [Real]
	22: $res_NLSJac2_4.$pDERNLSJac2.dummyVarNLSJac2=y1.SeedNLSJac2 + $cse3.SeedNLSJac2 + y2.SeedNLSJac2 + $cse4.SeedNLSJac2 [Real]
	
columnVars(6)
----------------------
index:0: $cse6 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
index:1: $cse5 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
index:3: $res_NLSJac2_4.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
index:2: $res_NLSJac2_3.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
index:1: $res_NLSJac2_2.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
index:0: $res_NLSJac2_1.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []

========================================


clockPartitions (0 systems):

========================================



initialEquations: (1)
========================================
7:  (NONLINEAR) index:0 jacobian: true
crefs: y1 , y2
	2: -1.0 + y1 + homotopy(sin(y1), y1) + y2 + homotopy(sin(y2), y2) (RESIDUAL)
	1: homotopy(sin(y2), y2) - y2 + homotopy(sin(y1), y1) + y1 (RESIDUAL)
	Jacobian idx: 0
	3: $cse1=cos(y1) [Real]
	4: $cse2=cos(y2) [Real]
	5: $res_NLSJac0_1.$pDERNLSJac0.dummyVarNLSJac0=y1.SeedNLSJac0 + __HOM_LAMBDA * $cse1 * y1.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y1.SeedNLSJac0 + y2.SeedNLSJac0 + __HOM_LAMBDA * $cse2 * y2.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y2.SeedNLSJac0 [Real]
	6: $res_NLSJac0_2.$pDERNLSJac0.dummyVarNLSJac0=y1.SeedNLSJac0 + __HOM_LAMBDA * $cse1 * y1.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y1.SeedNLSJac0 + __HOM_LAMBDA * $cse2 * y2.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y2.SeedNLSJac0 - y2.SeedNLSJac0 [Real]
	
columnVars(4)
----------------------
index:0: $cse2 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
index:1: $cse1 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
index:1: $res_NLSJac0_2.$pDERNLSJac0.dummyVarNLSJac0 (no alias)  initial: 	no arrCref index:() []
index:0: $res_NLSJac0_1.$pDERNLSJac0.dummyVarNLSJac0 (no alias)  initial: 	no arrCref index:() []

========================================



initialEquations_lambda0: (1)
========================================
12:  (LINEAR) index:0 jacobian: true
	variables:
index:-1: y1 (no alias)  initial: 	no arrCref index:() []
index:-1: y2 (no alias)  initial: 	no arrCref index:() []
	b-vector:
	9: -1.0 + 2.0 * (y1 + y2) (RESIDUAL)
	8: 2.0 * y1 (RESIDUAL)
	Jacobian idx: 1
	10: $res_LSJac1_1.$pDERLSJac1.dummyVarLSJac1=2.0 * (y1.SeedLSJac1 + y2.SeedLSJac1) [Real]
	11: $res_LSJac1_2.$pDERLSJac1.dummyVarLSJac1=2.0 * y1.SeedLSJac1 [Real]
	
columnVars(2)
----------------------
index:1: $res_LSJac1_2.$pDERLSJac1.dummyVarLSJac1 (no alias)  initial: 	no arrCref index:() []
index:0: $res_LSJac1_1.$pDERLSJac1.dummyVarLSJac1 (no alias)  initial: 	no arrCref index:() []
	simJac:
```

But I can't find the Jacobian using lambda for the initialization (`0<lambda<1`) in the generated C code.

**Comment by AnHeuermann** [comment]
Okay, the mixed homotopy solver currently uses a numerical Jacobian for `0<lambda<1`, since no Jacobian is generated in the C code for
```
initialEquations: (1)
========================================
7:  (NONLINEAR) index:0 jacobian: true
crefs: y1 , y2
	2: -1.0 + y1 + homotopy(sin(y1), y1) + y2 + homotopy(sin(y2), y2) (RESIDUAL)
	1: homotopy(sin(y2), y2) - y2 + homotopy(sin(y1), y1) + y1 (RESIDUAL)
	Jacobian idx: 0
	3: $cse1=cos(y1) [Real]
	4: $cse2=cos(y2) [Real]
	5: $res_NLSJac0_1.$pDERNLSJac0.dummyVarNLSJac0=y1.SeedNLSJac0 + __HOM_LAMBDA * $cse1 * y1.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y1.SeedNLSJac0 + y2.SeedNLSJac0 + __HOM_LAMBDA * $cse2 * y2.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y2.SeedNLSJac0 [Real]
	6: $res_NLSJac0_2.$pDERNLSJac0.dummyVarNLSJac0=y1.SeedNLSJac0 + __HOM_LAMBDA * $cse1 * y1.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y1.SeedNLSJac0 + __HOM_LAMBDA * $cse2 * y2.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y2.SeedNLSJac0 - y2.SeedNLSJac0 [Real]
	
columnVars(4)
----------------------
index:0: $cse2 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
index:1: $cse1 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
index:1: $res_NLSJac0_2.$pDERNLSJac0.dummyVarNLSJac0 (no alias)  initial: 	no arrCref index:() []
index:0: $res_NLSJac0_1.$pDERNLSJac0.dummyVarNLSJac0 (no alias)  initial: 	no arrCref index:() []

========================================
```
 So it will not need the new(or fixed) Jacobian we generated in Backend/SimCode.

**Comment by casella** [comment]
> 😬 I'm not so sure.

Ouch. I'm not sure I fully understand the role of all the logs you posted. What do you see in OMEdit declarative debugger? There, the three sets of initial, initial-lambda0 and regular equations are clearly marked
> From `-d=symjacdump` I can see that we generate Jacobians for
> 
> ```
> 1/1 (1): $res_NLSJac0_2 := y1 + homotopy(sin(y1), y1) + homotopy(sin(y2), y2) - y2
> 2/2 (1): $res_NLSJac0_1 := -1.0 + y1 + homotopy(sin(y1), y1) + y2 + homotopy(sin(y2), y2)
> ```
> 
> ```
> 1/1 (1): $res_LSJac1_2 := 2.0 * y1
> 2/2 (1): $res_LSJac1_1 := -1.0 + 2.0 * (y1 + y2)
> ```
> 
> and
> 
> ```
> 1/1 (1): $res_NLSJac2_4 := -1.0 + y1 + $cse3 + y2 + $cse4
> 2/2 (1): $res_NLSJac2_3 := sin(y1) - $cse3
> 3/3 (1): $res_NLSJac2_2 := y1 + $cse3 + $cse4 - y2
> 4/4 (1): $res_NLSJac2_1 := sin(y2) - $cse4
> ```
> 
> and all three seem to be correct.
> 
> When looking at SimCode it seems to be correct as well:
> 
> ```
> *********************
> * SimCode Equations *
> *********************
> 
> 
> allEquations:
> ========================================
> 
> 23:  (NONLINEAR) index:1 jacobian: true
> crefs: y1 , $cse3 , $cse4 , y2
> 	16: sin(y2) - $cse4 (RESIDUAL)
> 	15: $cse4 - y2 + $cse3 + y1 (RESIDUAL)
> 	14: sin(y1) - $cse3 (RESIDUAL)
> 	13: -1.0 + y1 + $cse3 + y2 + $cse4 (RESIDUAL)
> 	Jacobian idx: 2
> 	17: $cse5=cos(y1) [Real]
> 	18: $cse6=cos(y2) [Real]
> 	19: $res_NLSJac2_1.$pDERNLSJac2.dummyVarNLSJac2=$cse6 * y2.SeedNLSJac2 - $cse4.SeedNLSJac2 [Real]
> 	20: $res_NLSJac2_2.$pDERNLSJac2.dummyVarNLSJac2=y1.SeedNLSJac2 + $cse3.SeedNLSJac2 + $cse4.SeedNLSJac2 - y2.SeedNLSJac2 [Real]
> 	21: $res_NLSJac2_3.$pDERNLSJac2.dummyVarNLSJac2=$cse5 * y1.SeedNLSJac2 - $cse3.SeedNLSJac2 [Real]
> 	22: $res_NLSJac2_4.$pDERNLSJac2.dummyVarNLSJac2=y1.SeedNLSJac2 + $cse3.SeedNLSJac2 + y2.SeedNLSJac2 + $cse4.SeedNLSJac2 [Real]
> 	
> columnVars(6)
> ----------------------
> index:0: $cse6 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
> index:1: $cse5 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
> index:3: $res_NLSJac2_4.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
> index:2: $res_NLSJac2_3.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
> index:1: $res_NLSJac2_2.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
> index:0: $res_NLSJac2_1.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
> 
> ========================================
> 
> 
> 
> odeEquations (0 systems):
> ========================================
> ========================================
> 
> 
> 
> algebraicEquations (1 systems):
> ========================================
> 23:  (NONLINEAR) index:1 jacobian: true
> crefs: y1 , $cse3 , $cse4 , y2
> 	16: sin(y2) - $cse4 (RESIDUAL)
> 	15: $cse4 - y2 + $cse3 + y1 (RESIDUAL)
> 	14: sin(y1) - $cse3 (RESIDUAL)
> 	13: -1.0 + y1 + $cse3 + y2 + $cse4 (RESIDUAL)
> 	Jacobian idx: -1
> 	17: $cse5=cos(y1) [Real]
> 	18: $cse6=cos(y2) [Real]
> 	19: $res_NLSJac2_1.$pDERNLSJac2.dummyVarNLSJac2=$cse6 * y2.SeedNLSJac2 - $cse4.SeedNLSJac2 [Real]
> 	20: $res_NLSJac2_2.$pDERNLSJac2.dummyVarNLSJac2=y1.SeedNLSJac2 + $cse3.SeedNLSJac2 + $cse4.SeedNLSJac2 - y2.SeedNLSJac2 [Real]
> 	21: $res_NLSJac2_3.$pDERNLSJac2.dummyVarNLSJac2=$cse5 * y1.SeedNLSJac2 - $cse3.SeedNLSJac2 [Real]
> 	22: $res_NLSJac2_4.$pDERNLSJac2.dummyVarNLSJac2=y1.SeedNLSJac2 + $cse3.SeedNLSJac2 + y2.SeedNLSJac2 + $cse4.SeedNLSJac2 [Real]
> 	
> columnVars(6)
> ----------------------
> index:0: $cse6 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
> index:1: $cse5 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
> index:3: $res_NLSJac2_4.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
> index:2: $res_NLSJac2_3.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
> index:1: $res_NLSJac2_2.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
> index:0: $res_NLSJac2_1.$pDERNLSJac2.dummyVarNLSJac2 (no alias)  initial: 	no arrCref index:() []
> 
> ========================================
> 
> 
> clockPartitions (0 systems):
> 
> ========================================
> 
> 
> 
> initialEquations: (1)
> ========================================
> 7:  (NONLINEAR) index:0 jacobian: true
> crefs: y1 , y2
> 	2: -1.0 + y1 + homotopy(sin(y1), y1) + y2 + homotopy(sin(y2), y2) (RESIDUAL)
> 	1: homotopy(sin(y2), y2) - y2 + homotopy(sin(y1), y1) + y1 (RESIDUAL)
> 	Jacobian idx: 0
> 	3: $cse1=cos(y1) [Real]
> 	4: $cse2=cos(y2) [Real]
> 	5: $res_NLSJac0_1.$pDERNLSJac0.dummyVarNLSJac0=y1.SeedNLSJac0 + __HOM_LAMBDA * $cse1 * y1.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y1.SeedNLSJac0 + y2.SeedNLSJac0 + __HOM_LAMBDA * $cse2 * y2.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y2.SeedNLSJac0 [Real]
> 	6: $res_NLSJac0_2.$pDERNLSJac0.dummyVarNLSJac0=y1.SeedNLSJac0 + __HOM_LAMBDA * $cse1 * y1.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y1.SeedNLSJac0 + __HOM_LAMBDA * $cse2 * y2.SeedNLSJac0 + (1.0 - __HOM_LAMBDA) * y2.SeedNLSJac0 - y2.SeedNLSJac0 [Real]
> 	
> columnVars(4)
> ----------------------
> index:0: $cse2 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
> index:1: $cse1 (no alias)  protected  hideResult  initial: 	no arrCref index:() []
> index:1: $res_NLSJac0_2.$pDERNLSJac0.dummyVarNLSJac0 (no alias)  initial: 	no arrCref index:() []
> index:0: $res_NLSJac0_1.$pDERNLSJac0.dummyVarNLSJac0 (no alias)  initial: 	no arrCref index:() []
> 
> ========================================
> 
> 
> 
> initialEquations_lambda0: (1)
> ========================================
> 12:  (LINEAR) index:0 jacobian: true
> 	variables:
> index:-1: y1 (no alias)  initial: 	no arrCref index:() []
> index:-1: y2 (no alias)  initial: 	no arrCref index:() []
> 	b-vector:
> 	9: -1.0 + 2.0 * (y1 + y2) (RESIDUAL)
> 	8: 2.0 * y1 (RESIDUAL)
> 	Jacobian idx: 1
> 	10: $res_LSJac1_1.$pDERLSJac1.dummyVarLSJac1=2.0 * (y1.SeedLSJac1 + y2.SeedLSJac1) [Real]
> 	11: $res_LSJac1_2.$pDERLSJac1.dummyVarLSJac1=2.0 * y1.SeedLSJac1 [Real]
> 	
> columnVars(2)
> ----------------------
> index:1: $res_LSJac1_2.$pDERLSJac1.dummyVarLSJac1 (no alias)  initial: 	no arrCref index:() []
> index:0: $res_LSJac1_1.$pDERLSJac1.dummyVarLSJac1 (no alias)  initial: 	no arrCref index:() []
> 	simJac:
> ```
> 
> But I can't find the Jacobian using lambda for the initialization (`0<lambda<1`) in the generated C code.

**Comment by casella** [comment]
> Okay, the mixed homotopy solver currently uses a numerical Jacobian for `0<lambda<1`,
> So it will not need the new(or fixed) Jacobian we generated in Backend/SimCode.

Wait, for the real application (not for the MWE), we are not using the mixed homotopy solver, which I understand is dense, but rather the sparse Kinsol-KLU. I hope we can handle symbolic jacobians there too

**Comment by AnHeuermann** [comment]
>What do you see in OMEdit declarative debugger?

Oh that is working. From the debugger it tells me that we have a (correct) Jacobian for initialization and lambda>0.
But the debugger doesn't know the C code, so it doesn't know that the Code generated is missing that Jacobian.
I guess there is something not working at code generation. I'm investigation if I can find that location. But when we generate code for the Jacobian it should work with all our solvers.

**Comment by AnHeuermann** [comment]
image

**Comment by casella** [comment]
I just added two more tests in [#6328](https://trac.openmodelica.org/OpenModelica/attachment/ticket/6328/) to force using the Kinsol solver with sparse KLU linear solver.

**Pull request merged**
