### PR TITLE
Removed obsolete functions

### PR DESCRIPTION
**Pull request by JKRT**
* This resolves the circular dependency between Util and flags

### CODE REVIEW

**Comment by JKRT** [comment]
@adrpo  @lochel  @sjoelund  Any ideas?

**Comment by sjoelund** [comment]
I think it was unused in OMC for some years. Most probably an alternative can be used; perhaps without the flags if @niklwors can tell us if BoschRexroth still uses that flag...

**Comment by lochel** [comment]
@niklwors please review or comment

**Comment by niklwors** [comment]
@JKRT @lochel  I cannot find where we use the function modelicaStringToCStr. We are using Util.escapeModelicaStringToCString but this is also used by other templates.

**Comment by JKRT** [comment]
> 
> 
> @JKRT @lochel I cannot find where we use the function modelicaStringToCStr. We are using ```
Util.escapeModelicaStringToCString but this is also used by other templates.

find . -type f -exec grep --color -nH --null -e "Util.modelicaStringToCStr" \{\} +
./BackEnd/BackendInline.mo\0904:        funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(p), false);
./BackEnd/BackendInline.mo\0932:          funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(p), false);
./BackEnd/Differentiate.mo\02295:        funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(path), false);
./BackEnd/Differentiate.mo\02687:      funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(path), false);

A couple of places in the backend. I reckon it might be OK to replace it with the other function there? 
```

**Comment by niklwors** [comment]
> 
> 
> > @JKRT @lochel I cannot find where we use the function modelicaStringToCStr. We are using ```
> > Util.escapeModelicaStringToCString but this is also used by other templates.
> 
> find . -type f -exec grep --color -nH --null -e "Util.modelicaStringToCStr" {} +
> ./BackEnd/BackendInline.mo\0904: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(p), false);
> ./BackEnd/BackendInline.mo\0932: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(p), false);
> ./BackEnd/Differentiate.mo\02295: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(path), false);
> ./BackEnd/Differentiate.mo\02687: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(path), false);
> 
> A couple of places in the backend. I reckon it might be OK to replace it with the other function there?

yes this is ok to replace it with other functions. Should I replace it, or can you do this?  Is there a similar function?

**Comment by JKRT** [comment]
> 
> 
> > > @JKRT @lochel I cannot find where we use the function modelicaStringToCStr. We are using ```
> > > Util.escapeModelicaStringToCString but this is also used by other templates.
> > 
> > 
> > find . -type f -exec grep --color -nH --null -e "Util.modelicaStringToCStr" {} +
> > ./BackEnd/BackendInline.mo\0904: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(p), false);
> > ./BackEnd/BackendInline.mo\0932: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(p), false);
> > ./BackEnd/Differentiate.mo\02295: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(path), false);
> > ./BackEnd/Differentiate.mo\02687: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(path), false);
> > A couple of places in the backend. I reckon it might be OK to replace it with the other function there?
> 
> yes this is ok to replace it with other functions. Should I replace it, or can you do this? Is there a similar function?

I will do it. I will give you a message after my change. escapeModelicaStringToCString should do the trick and would be the right function to use

**Comment by niklwors** [comment]
> 
> 
> > > > @JKRT @lochel I cannot find where we use the function modelicaStringToCStr. We are using ```
> > > > Util.escapeModelicaStringToCString but this is also used by other templates.
> > > 
> > > 
> > > find . -type f -exec grep --color -nH --null -e "Util.modelicaStringToCStr" {} +
> > > ./BackEnd/BackendInline.mo\0904: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(p), false);
> > > ./BackEnd/BackendInline.mo\0932: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(p), false);
> > > ./BackEnd/Differentiate.mo\02295: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(path), false);
> > > ./BackEnd/Differentiate.mo\02687: funcname = BackendUtil.modelicaStringToCStr(AbsynUtil.pathString(path), false);
> > > A couple of places in the backend. I reckon it might be OK to replace it with the other function there?
> > 
> > 
> > yes this is ok to replace it with other functions. Should I replace it, or can you do this? Is there a similar function?
> 
> I will do it. I will give you a message after my change. escapeModelicaStringToCString should do the trick and would be the right function to use

Thank you very much.

**Comment by JKRT** [comment]
Seems like I cannot get around this. Closing for now.

**Pull request closed without merging**
