### PR TITLE
Keep the NFApi settings

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by adeas31** [comment]
@adrpo this should fix #6394. Can you please test it.

**Review by adrpo — APPROVED** [review]
As far as I can understand this, it looks OK.

**Comment by adrpo** [comment]
This needs to be ported to 1.17 and 1.16 as well?

**Comment by adrpo** [comment]
I will build this and test it now.

**Comment by adeas31** [comment]
Yes we need to port this.

**Pull request merged**
