### PR TITLE
update OSMC license to the latest from the OSMC bylaws

### PR DESCRIPTION
**Pull request by adrpo**
Update the OSMC license to the latest

### CODE REVIEW

**Comment by sjoelund** [comment]
We should also update the OM webpage (the Hugo repository)

**Comment by jdsika** [comment]
@adrpo I would like to get in touch regarding specifics of the license as we are evaluating the usage at BMW. The License seems to be allowed to be changed according to the commit 01.02.2023 and currently at v1.8 - is the backwards compatibility of these changes evaluated and is there somewhere a document with the changelog and rationals behind the decisions from v1.0 to v1.8?

Feel free to get in touch via email: carlo.van-driesten@bmw.de

**Comment by jdsika** [comment]
Further questions:
* Is there a SPDX-ID?
* Is it OSI-Certified?

**Comment by casella** [comment]
> Further questions:
> 
>     * Is there a SPDX-ID?

No / not yet.
 
>     * Is it OSI-Certified?

AGPL (which is one option of OSMC-PL) [is](https://opensource.org/license/agpl-v3).

**Pull request merged**
