### PR TITLE
Update QWT to 6.1.5

### PR DESCRIPTION
**Pull request by perost**
- Older versions of QWT causes issues with QT 5.15 due to missing
  include statements, which has been fixed in the latest version.

### CODE REVIEW

**Comment by perost** [comment]
Not sure what's going on with the versions, our old version said it was 6.2.0 while the latest stable version released in june is 6.1.5. But this is the latest stable version at least.

**Comment by sjoelund** [comment]
https://github.com/svn2github/Qwt/commit/5a58c81fe66ce1218a5ce320b0d58f8d507944f3#diff-376a8e54ee1fc913fdda4d6a736f859a - some commit between 6.1.0 and 6.1.1. I guess they changed their mind about the version bump

**Comment by sjoelund** [comment]
I guess we should build this on OSX and Windows to make sure it works there

**Comment by perost** [comment]
> I guess we should build this on OSX and Windows to make sure it works there

Yes, that might be a very good idea. I forgot it doesn't happen automatically.

**Comment by adeas31** [comment]
Not sure if we should update it now just before the release.

**Comment by sjoelund** [comment]
The release was branched off a long time ago in order for us to be able to update the master

**Comment by adeas31** [comment]
@adrpo told we will pick up whatever is in the master.

**Comment by adrpo** [comment]
We only branched and tagged v1.16.0-dev.03 and we should use what is on master for 1.16 beta.

**Comment by perost** [comment]
The Windows build fails due to:
```
ld.exe: cannot find -lQt5PrintSupportd
ld.exe: cannot find -lQt5Svgd
ld.exe: cannot find -lQt5Widgetsd
ld.exe: cannot find -lQt5Guid
ld.exe: cannot find -lQt5Concurrentd
ld.exe: cannot find -lQt5Cored
```
I guess we need to add these libs to OMDev?

The MacOS build fails because of:
```
cp -a qwt/lib/libomqwt*dylib /Users/hudson/jenkins-slave/ws/OpenModelica_PR-6717/build/lib/x86_64-darwin15.4.0/omc/
install_name_tool -id @rpath/libomqwt.6.2.0.dylib /Users/hudson/jenkins-slave/ws/OpenModelica_PR-6717/build/lib/x86_64-darwin15.4.0/omc/libomqwt.6.2.0.dylib
error: install_name_tool: can't open file: /Users/hudson/jenkins-slave/ws/OpenModelica_PR-6717/build/lib/x86_64-darwin15.4.0/omc/libomqwt.6.2.0.dylib (No such file or directory)
```
Not sure why it's expecting the library to be 6.2.0, I can't find anything that references 6.2.0 in the updated QWT build files. Is the MacOS build using something else to build it?

**Comment by sjoelund** [comment]
> I guess we need to add these libs to OMDev?

Or configure qwt not to use the debug libraries?

> Not sure why it's expecting the library to be 6.2.0, I can't find anything that references 6.2.0 in the updated QWT build files. Is the MacOS build using something else to build it?

It's in our makefiles (because qmake / cmake won't output a working rpath)

**Comment by perost** [comment]
> > I guess we need to add these libs to OMDev?
> 
> Or configure qwt not to use the debug libraries?

Seems I accidentally removed a win32 guard when manually merging qwtconfig.pri, that's probably the reason.
> > Not sure why it's expecting the library to be 6.2.0, I can't find anything that references 6.2.0 in the updated QWT build files. Is the MacOS build using something else to build it?
> 
> It's in our makefiles (because qmake / cmake won't output a working rpath)

Thanks, should be fixed now.

**Comment by perost** [comment]
Seems the issues have been fixed now, so I guess the question now is just when to merge it.

**Comment by adrpo** [comment]
We don't ship with Qt debug libraries for OMDev as those are huge and would make it even larger than already is by several GB.

@adeas31 I think we should just merge this and test a bit the plotting.

**Comment by adeas31** [comment]
Yes we can merge it and I will then test the plotting on Windows a bit to see if there are any issues. @perost can test on Linux.

**Comment by perost** [comment]
> Yes we can merge it and I will then test the plotting on Windows a bit to see if there are any issues. @perost can test on Linux.

Ok, it's merged now. I also tested it on Linux before making the PR by opening a result file with OMPlot, which as far as I could determine worked fine.

**Pull request merged**
