### PR TITLE
[FMI] BLAS, LAPACK and CMINPACK SourceFiles added to modelDescription

### PR DESCRIPTION
**Pull request by AnHeuermann**
### Related Issues

Fixes https://github.com/OpenModelica/OpenModelica/issues/8524

Makes it possible to re-compile FMUs with FMPy (assuming you have pthreads).

### Purpose

Adding FMU source files of LAPACK, BLAS and CMINPACK as well as optional CVODE files to `SourceFiles` section of modelDescription.xml.

### Approach

  - Added them in SimCodeMain.mo during generation of the FMU and the modelDescription XML.

### CODE REVIEW

**Comment by AnHeuermann** [comment]
Compiling source-code FMUs with CVODE won't work, because one needs to defines `OMC_MINIMAL_RUNTIME=1;OMC_FMI_RUNTIME=1;CMINPACK_NO_DLL;WITH_SUNDIALS` and we don't have a buildDescrption.xml to document this.

**Comment by casella** [comment]
It looks like the failing tests are due to the fact that something has changed in the generated code file names, which I guess is expected with this PR. Do I understand correctly?

**Comment by AnHeuermann** [comment]
I changed the order of some files in the modelDescription. I'll change it back or change the expected output of the tests.
Currently I'm working on a test that will use FMPy to re-compile / simulate some FMUs from our cross-check.

**Comment by casella** [comment]
Thanks @AnHeuermann!

Are the exported source code FMU now going to work in all cases where the dgesv_ symbol issue popped up? Can @t-sommer try this out already when the nightly build is available?

**Comment by AnHeuermann** [comment]
Yes and yes

**Comment by t-sommer** [comment]
You can try it yourself: `fmpy compile MyModel.fmu`. Should work on all platforms.

**Comment by AnHeuermann** [comment]
We already do: https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-11435/6/pipeline/1070#step-1190-log-13

**Comment by casella** [comment]
@dietmarw, a small step for a man, a giant leap for FMU export 😄

**Pull request merged**
