### PR TITLE
Migrate OMSysIdent docs into User's Guide

### PR DESCRIPTION
**Pull request by bernhard-thiele**
OMSysIdent was previously part of OMSimulator. It has been extracted out of the OMSimulator project and reorganized as a separate project. Since it is part of the OpenModelica tool suite, the proposal is to integrate its documentation into the OpenModelica User's Guide.

### CODE REVIEW

**Review by adrpo — APPROVED** [review]
OK by me!

**Comment by bernhard-thiele** [comment]
@adrpo From my side we can merge it. I don't know why the license/cla check doesn't complete. Should be fine.

**Comment by sjoelund** [comment]
I redelivered the payload and it's now happy

**Comment by adrpo** [comment]
Should we put this on maintenance/v1.16 as well?

**Comment by bernhard-thiele** [comment]
It might be a good idea to put this on maintenance/v1.16 if it is not much extra work. OMSysIdent was mentioned in some publications and it would be a bit odd if it can't be found in the documentation.

**Comment by adrpo** [comment]
Did that already, mainteanance/v1.16 is basically current master.

**Pull request merged**
