### PR TITLE
[NF,BE] Avoid expansion of vectorized bindings if not scalarizing (#12951)

### PR DESCRIPTION
**Pull request by rfranke**
The goal is to have constant code size and translation time if just array dimensions change.
This is why vectorized bindings must not be expanded.

- NF: use each for vectorized attributes
- BE: remove fill from vectorized variable and parameter bindings, treating them like each

### CODE REVIEW

**Comment by rfranke** [comment]
7 tests are failing. Not too bad, but still more than 0. Take `testsuite/flattening/modelica/scodeinst/BuiltinAttribute23.mos` as example:
```
// name: BuiltinAttribute23
// keywords:
// status: correct
//

model BuiltinAttribute23
  parameter Real x0 = 0;
  type T = Real[3] (each start = x0);
  T t;
  annotation(__OpenModelica_commandLineOptions="--newBackend");
end BuiltinAttribute23;

// Result:
// class BuiltinAttribute23
//   parameter Real x0 = 0.0;
//   Real[3] t(start = array(x0 for $i1 in 1:3));
// end BuiltinAttribute23;
// endResult
```
Failing with:
```
-Real[3] t(start = array(x0 for $i1 in 1:3));
+Real[3] t(start = x0);
```
Btw. the new result should read:
```
+Real[3] t(each start = x0);
```
The `each`appears in debug outputs, but is missing in the final output, e.g. calling with `-dumpFlatModel`:
```
########################################
scalarize
########################################

class BuiltinAttribute23
  parameter Real x0 = 0.0;
  Real[3] t(each start = x0);
end BuiltinAttribute23;

class BuiltinAttribute23
  parameter Real x0 = 0.0;
  Real[3] t(start = x0);
end BuiltinAttribute23;
```
EACH seems to be part of Flat Modelica according to this: https://github.com/OpenModelica/OpenModelica/blob/dc0fc08659343e12f8e94e52d8323559116fe30c/OMCompiler/tools/xml/flatmodelicaxml/flat_modelica_parser.g#L265

@perost why does `each` not appear in the final output?

Moreover, replacing `each start = x0` with `start = array(x0 for $i1 in 1:3)` appears bad as the information that each element is getting the same value is hidden -- requires some expression parser to recreate it. Why is `each` not used?

**Comment by perost** [comment]
> EACH seems to be part of Flat Modelica according to this: 
> @perost why does `each` not appear in the final output?

I have no clue what that parser is, but `each` has never been part of the normal flat model output and not handled by the backend. In some cases the backend accepts scalar values as if they were `each`, but we've tried to move away from that as it's prone to errors and just have expressions of the correct type instead.

I'm not sure why we're creating array constructor expressions instead of using `fill`, I think this was something the new backend wanted. Maybe @kabdelhak can comment on that.

**Comment by rfranke** [comment]
Actually this change should only take effect with `-d=-nfScalarize`. It appears that `annotation(__OpenModelica_commandLineOptions="--newBackend");` sets this implicitly.

**Comment by perost** [comment]
> Actually this change should only take effect with `-d=-nfScalarize`. It appears that `annotation(__OpenModelica_commandLineOptions="--newBackend");` sets this implicitly.

Yes, the new backend is based on the non-scalarized flattening, and `--newBackend` implicitly sets `-d=-nfScalarize,vectorizeBindings`.

**Comment by rfranke** [comment]
Moved all changes to the old backend, a bit cumbersome but with less side effects. The `each` qualifier is quite effective if it avoids the creation of potentially large arrays that don't contain more information than a scalar value. Maybe more error prone indeed. Assuming that early translation phases do their job in checking correctness, later stages could focus on runtime efficiency.

**Pull request merged**
