### PR TITLE
Remove excess nesting

### PR DESCRIPTION
**Pull request by FDzhang**
### Related Issues
no

### Purpose
Equivalent logic, reducing hierarchy

### Approach
Remove excess nesting

### CODE REVIEW

**Review by adeas31 — APPROVED** [review]
LGTM.

@FDzhang sign the license/cla. If you already signed it then force push the pull request.

**Comment by FDzhang** [comment]
> LGTM.
> 
> @FDzhang sign the license/cla. If you already signed it then force push the pull request.

Excuse me, how should I 'sign the license/cla'

**Comment by adeas31** [comment]
There is a `license/cla` check in the PR. You need to sign the license/cla with same email that you used with git commit.

**Comment by FDzhang** [comment]
> There is a `license/cla` check in the PR. You need to sign the license/cla with same email that you used with git commit.

 thanks，i already signed it， but I don't have the authority to force push the pull request

**Pull request merged**
