### PR TITLE
Don't dump equations into Cpp FMU sources

### PR DESCRIPTION
**Pull request by rfranke**
This addresses the discussion in #7560

### CODE REVIEW

**Comment by adrpo** [comment]
We should put this on a flag as for easier debugging you might want to have it.

**Comment by rfranke** [comment]
The idea is to debug with `simulate`. This generates the same equations.

**Comment by adrpo** [comment]
Sorry, I merged this one by mistake. Hopefully is OK.

**Comment by rfranke** [comment]
OK for me. We can refine this with a flag later.

**Pull request merged**
