### PR TITLE
Updated 3rdParty with new cppzmq library. Extended makefile.common  f…

### PR DESCRIPTION
**Pull request by niklwors**
…or installing zmq config files to libzmq/build/ folder, for using find_package(zeromq) in cmake. Installing cppzqm file to cppzmq/build/

### CODE REVIEW

**Comment by adrpo** [comment]
This would not work until we have updated 3rdParty first, then make a PR including the new submodule hash.

**Comment by adrpo** [comment]
I now merged the changes to 3rdParty, you can update this PR to the new 3rdParty hash.

**Comment by niklwors** [comment]
ok, I have updated the 3rdParty hash

**Comment by adrpo** [comment]
Good, lets see how the build works.

**Comment by niklwors** [comment]
I think the dependency to libzmq from cppzmq is missing. I will add it.

**Comment by adeas31** [comment]
I think we should also enable Windows and MAC builds for this PR.

**Comment by adrpo** [comment]
@adeas31: done.

**Comment by niklwors** [comment]
Can someone of you see the error in the log?

**Comment by sjoelund** [comment]
You removed the $(builddir_lib_omc)/$(LIBZMQLIB) target, which is used by other targets...

**Comment by sjoelund** [comment]
Also note that if you use PHONY targets, they often mess with the parallel builds. For example if both cpp and c runtime depend on libzmq, they can build 2 copies of it at once causing random failures... Read the GNU make documentation very carefully when making changes such as these.

**Comment by niklwors** [comment]
I've removed the dependency from the cpp runtime to cppzmq. But what I want is for the cppp runtime to create cppzmq, too, and for cppzmq to create libzmq if not already done.  Therefore  I have added the dependency cppzmq to the target runtimecpp. The cppzmq target has the dependency libzmq. But for some reason it doesn't work. clang reports an error in libzmq build:
"/usr/bin/clang"
 is not able to compile a simple test program.
But this was not changed by this PR. 
Does anybody know what else is wrong?

**Comment by adrpo** [comment]
The problem with the previous build was that libzmq was built in parallel and that just didn't work fine (same happened for gcc not only for clang). I will merge your code and then try to fix the build of cppzmq.

**Pull request merged**
