### PR TITLE
update discrete system before evaluating DAE

### PR DESCRIPTION
**Pull request by arun3688**
### Related Issues

https://github.com/OpenModelica/OpenModelica/issues/12350

### Purpose

Update discrete system before evaluating DAE, when `reinit`

### CODE REVIEW

**Comment by bilderbuchi** [comment]
@arun3688 is it possible to backport this fix for #12350 to 1.23? 
In case this has been done already, please disregard. ^^

**Comment by bilderbuchi** [comment]
This would be useful because then the fix would land in your published Docker images before 1.24 is finished, and we could build on those.

**Comment by casella** [comment]
Sure, please see #12350.

**Comment by bilderbuchi** [comment]
Many thanks! :-)

**Pull request merged**
