### PR TITLE
Fixed obsolete warning messages 

### PR DESCRIPTION
**Pull request by casella**
Fixed obsolete warning messages with reference to non-existing OMEdit options

### CODE REVIEW

**Review by lochel — APPROVED** [review]

**Comment by casella** [comment]
@lochel, do you have any idea why the testuite failed?

**Comment by lochel** [comment]
The messages are part of the baseline of many tests on our testsuite.

**Review by adeas31 — APPROVED** [review]
Fine with me. However, there are still some tests that needs to be updated.

**Comment by casella** [comment]
> The messages are part of the baseline of many tests in our testsuite.

I can imagine that, but it's not immediately apparent fo me from the logs, probably because I don't know exactly where to look at.

> I can take care of it if you want.

That would be nice. I'd like to learn how to do it myself, but I'm really swamped.

Thanks!

**Comment by perost** [comment]
> I can imagine that, but it's not immediately apparent fo me from the logs, probably because I don't know exactly where to look at.

Click "Details" on the failing job, then click on "Tests" in Jenkins in the upper right corner. Then just click on any test in the list to expand it and show the log.

**Comment by casella** [comment]
> 
> 
> > I can imagine that, but it's not immediately apparent fo me from the logs, probably because I don't know exactly where to look at.
> 
> then click on "Tests"

Aha, this is what I always forget. I look at the raw logs, but "Tests" is the place to look at.

Yeah, obviously there are many tests in the testuite with not fully specified initial conditions, and of course they all fail because of a different warning message.

@lochel, if you could update them you would do me a big favour. Thanks!

**Comment by casella** [comment]
Great, thanks!

**Pull request merged**
