### PR TITLE
Reduce -nlsMinSize default to 1000

### PR DESCRIPTION
**Pull request by phannebohm**
issue #7848

@casella the default for -lssMinSize is already at 200
https://github.com/OpenModelica/OpenModelica/blob/9431d4e064e46f015f9793a3f952ec4f6fbf90be/OMCompiler/SimulationRuntime/c/util/simulation_options.h#L43

### CODE REVIEW

**Comment by casella** [comment]
Mayb 201 is too conservative for the kind of problem we are trying to solve. Let's stick to 1000

**Comment by casella** [comment]
Please don't forget to update the [flag documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-nlssminsize), because that still mentions 4001, this must be updated manually.

**Comment by phannebohm** [comment]
> Please don't forget to update the [flag documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-nlssminsize), because that still mentions 4001, this must be updated manually.

Do you by any chance know where that is in our repository? I can't find it :smile:

**Comment by mahge** [comment]
https://github.com/OpenModelica/OpenModelica/blob/master/doc/UsersGuide/source/simulationflags.rst

From here search for what you want to update. Most of the info is generated automatically from the description of the flags.

**Pull request merged**
