### PR TITLE
[NB] update for-when nesting

### PR DESCRIPTION
**Pull request by kabdelhak**
- have size instead of type at for equation
  - correctly determine this size
  - correctly set empty attributes at size 0 when equations
  - add more debugging output for causalization failure

### CODE REVIEW

**Comment by perost** [comment]
For `Expression.rangeSize` I would instead implement it as:
```Modelica
size := Dimension.size(Type.nthDimension(typeOf(range), 1));
```
That way you don't need to implement yet another error-prone range calculation, and it also works with any kind of range and not just integer ranges.

**Comment by kabdelhak** [comment]
I am a little confused, locally i cannot reproduce the failing test cases. Have to look into that... @phannebohm can you clone my branch and test if the test run for you?

**Comment by perost** [comment]
> I am a little confused, locally i cannot reproduce the failing test cases. Have to look into that... @phannebohm can you pull my branch and test if the tests run for you?

It seems it's only failing on the Clang tests, not with GCC. So you probably need to build omc with Clang if you're not already doing so.

**Comment by perost** [comment]
I tried reproducing the issue but it works for me, but running it through valgrind showed that the output parameter `changed` in `NBResolveSingularities.noIndexReduction` is not assigned a value.

**Comment by kabdelhak** [comment]
> I tried reproducing the issue but it works for me, but running it through valgrind showed that the output parameter `changed` in `NBResolveSingularities.noIndexReduction` is not assigned a value.

Thanks a lot! will fix that

**Comment by phannebohm** [comment]
I couldn't reproduce any of this... but now all seems to work on jenkins also, so :+1:

**Comment by kabdelhak** [comment]
> I couldn't reproduce any of this... but now all seems to work on jenkins also, so 👍

yay! I guess?

**Pull request merged**
