### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by casella**

### CODE REVIEW

**Comment by casella** [comment]
@lochel, @sjoelund, I just changed an 'e' into an 'a' in the text of the guide that describes portability issue. How can this affect the testsuite results? I guess something fishy's going on here

**Comment by lochel** [comment]
Looks like a time-out. I restarted the jenkins job.

**Comment by casella** [comment]
> 
> 
> Looks like a time-out. I restarted the jenkins job.

Yeah. Strange that it happened here, I never saw that before.

**Comment by casella** [comment]
All's well that ends well. BTW, how do you restart the jenkins job without any commit?

**Comment by sjoelund** [comment]
> All's well that ends well. BTW, how do you restart the jenkins job without any commit?

Press the restart or run button in Jenkins.

**Comment by lochel** [comment]
Or by pushing an empty commit to your pull request.

**Pull request merged**
