### PR TITLE
WIP - Snapshot based redo undo functionality for OMSimulator models

### PR DESCRIPTION
**Pull request by adeas31**
- [x] Fixes ticket:5789 delete ssp components
Fixes ticket:5984
  - [x] Disable the text view if its not allowed to edit.
  - [x] Clicking in the libraries browser should accept text changes.
  - [x] Tabs should be preserved when accepting text changes.
  - [x] The open nodes of the tree view in the libraries browser should be preserved when accepting text changes.
- [x] Create new OMSimulator models by right clicking in the Libraries Browser
- [x] Improved the addsubmodel dialog. Let user first select the file and then propose name from filename.

### CODE REVIEW

**Comment by lochel** [comment]
Component names cannot contain dots. Please replace them with underscores or something else.

**Comment by adeas31** [comment]
> Component names cannot contain dots. Please replace them with underscores or something else.

Instead of auto replacing them, I added a check for dots.
BTW I expect `oms_addSubModel` to fail if name is illegal.  Are there more such restrictions with name?

**Comment by lochel** [comment]
Everything works rather well I think. Just some minor comments:

- The API is catching the error and showing a error message in OMEdit.
- The pre-selected name is rather bad right now. Just replacing the dots with an underscore would be much better. Just consider a typical case as this one with the FMUs `DualMassOscillator.System1.fmu` and `DualMassOscillator.System2.fmu`.
- Please open directly the file browser when adding a submodel.

**Comment by adeas31** [comment]
> Everything works rather well I think. Just some minor comments:
> 
> * The API is catching the error and showing a error message in OMEdit.

I see but the error message is not very helpful. It says `[addSubModel] System "Test.Root.SC" does not contain system "DualMassOscillator"` when the submodel name is `DualMassOscillator.System2`.

> * The pre-selected name is rather bad right now. Just replacing the dots with an underscore would be much better. Just consider a typical case as this one with the FMUs `DualMassOscillator.System1.fmu` and `DualMassOscillator.System2.fmu`.

Done.

> * Please open directly the file browser when adding a submodel.

Done.

**Comment by lochel** [comment]
Do you want me to test it again?

**Comment by adeas31** [comment]
> Do you want me to test it again?

I will let you know when its ready for testing again.

**Comment by casella** [comment]
@lochel, @adeas31, can we merge this before feature freeze?

**Comment by adeas31** [comment]
Not yet. I need some more time to finish this.

**Comment by casella** [comment]
OK, no problem 😃

**Comment by adeas31** [comment]
@lochel this is up for testing again.

**Comment by lochel** [comment]
@adeas31 I have again the problem that not all changes end up in the build of OMEdit. Even though you did change the Makefile to fix this problem as far as I remember.

**Comment by adeas31** [comment]
Strange. Maybe you still have the old makefile and qmake skips the generation of the new one.

**Comment by lochel** [comment]
How should I force to build OMEdit then?

**Comment by adeas31** [comment]
`touch main.cpp`

**Pull request merged**
