### PR TITLE
[OMSICpp] new branch with all the changes that were reverted

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

**Comment by adrpo** [comment]
@AnHeuermann, @niklwors here is the OMSICpp branch with all the changes that I reverted from master. You should be able to continue your work on this branch until is ready to be merged (my bad, I merged your stuff too early).

**Comment by niklwors** [comment]
@adrpol @AnHeuermann  I tried to merge this branch with the master branch and resolve the merge conflicts above. But this is with normal merge and rebase not possible because of the revert commit's in the master branch. Do you know how this branch can be merged?

**Comment by adrpo** [comment]
@niklwors strange, I will try it myself and see if I find a way.

**Comment by adrpo** [comment]
Closing this one and opening another one soon enough.

**Pull request closed without merging**
