### PR TITLE
Add ssp to the recognized file types

### PR DESCRIPTION
**Pull request by lochel**
This will add ssp to the list of recognized file types. However, I don't know if this causes problems, because the list seem to be used in different places.

### CODE REVIEW

**Review by adeas31 — CHANGES_REQUESTED** [review]
What/where do you need this for?

`Helper::omsFileTypes` is what you want to use.

**Comment by lochel** [comment]
I wanted to use the File->Open Model (or rather the icon in the toolbar). I missed the SSP menu again. Is there a particular reason for keeping it that separated? I guess most people will just click on the "Open Model"-icon as I did...

**Comment by adeas31** [comment]
I see. Maybe we should rename `Open Model` to `Open Modelica Model`. I prefer them separated. Some time ago we decided to have a dedicated menu for SSP.

**Comment by lochel** [comment]
But this is really bad. People - like me - will not understand why they cannot open a SSP file in OMEdit ... 

The SSP menu is fine for most actions, but not for open/save. (I am not sure about new model.) You are also using the save button for both Modelica and SSP. Therefore, it is confusing to not have a shared button for opening those models.

**Comment by adeas31** [comment]
We can use open button to open the ssp models. Its the new that is the problem and naturally one wants to use File->new for ssp models as well.

I understand the problem and I might have a solution for it. Let me think about it and I will come up with a proper solution for it.

**Comment by lochel** [comment]
Not sure if relevant, but what is `composite model` and `external model` in the file menu referring to? Is it the old tlm implementation that doesn't depend on OMSimulator?

**Comment by adeas31** [comment]
Yes!

**Comment by lochel** [comment]
@adeas31 is going to implement it properly

**Pull request closed without merging**
