### PR TITLE
Update Docker images to Jammy

### PR DESCRIPTION
**Pull request by AnHeuermann**
### Related Issues

We need to update the Dockerfiles to update OMSimulator sub-module.

Related to https://github.com/OpenModelica/OpenModelica/pull/10353.

### Purpose

Use Docker images based on Ubuntu Jammy (22.04.2 LTS).

### Approach

  - Created new repository for build-deps images: https://github.com/AnHeuermann/build-deps (Will be moved to OpenModelica soon, I hope)

### Changes

  - Removed 32-bit Linux builds (there is no 32bit Ubuntu Jammy as far as I know)
  - Removed all outdated Docker images (reached EOL)
    - [ ] Re-add some older compilers to Jenkins pipelines, see https://openmodelica.org/developersresources/devdocumentation/
  - Jenkins: Use Jammy instead of Bionic Docker files
  - Changed `autoconf` --> `autoreconf --install` in scripts
  - Updated Inkscape and Pandoc commands for User's Guide, fixed pdf build to use .png instead of .* files
  - Updated testsuite
    - Deavtivated ThermoSysPro.Examples.SimpleExamples.TestDynamicWaterHeating.mos
    - Only test OpenCL test on Intel machines (no AMD support?)
    - Removed some ever-changing LOG_IPOPT_ERROR logs.

### CODE REVIEW

**Comment by AnHeuermann** [comment]
The C++ HPCOM test seem to produce segmentation fault. No idea why. If I find some time I can debug a bit. But otherwise I would suggest to deactivate the failing ones for now.

**Comment by AnHeuermann** [comment]
I can't reproduce the issue in the failing test [openmodelica/cppruntime/hpcom/Modelica.Electrical.Analog.Examples.CauerLowPassSC_level_omp_measureTime.mos](https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-11027/14/tests).

I'm using the same Docker image, the Makefiles build and the same configure call. Maybe it only fails sometimes? Or is it because I use a different CPU (Intel vs AMD)?
No idea how to fix that one, so I'll just deactivate the test.

**Comment by adrpo** [comment]
I don't know how good it is to remove the 32bit Linux builds. Aren't some platforms such as Arduino just 32bit? Or maybe I am missing something?

**Comment by AnHeuermann** [comment]
> I don't know how good it is to remove the 32bit Linux builds. Aren't some platforms such as Arduino just 32bit? Or maybe I am missing something?

Are we supporting them? On https://openmodelica.org/developersresources/devdocumentation/ we have `fc37`. Is that Arduino?
And are we testing any 32bit stuff on Jenkins? I can't see any build or test pipelines on the master.
I don't see a point in running OpenModelica (OMEdit) itself on an Arduino. You might want to run a simulation (FMU) on it, in that case we would need to test cross-compilation for these targets.

But there a few OS that are still available as 32bit. Jammy is not, but we can create additional Docker images with an OS that still supports 32 bit. So someone would could try to create images for `fc37` or `fc38` and then integrate them into the PR tests to see if they actually work.

Actually it would be a very good idea to have one Docker image for each system we want to support. Creating additional Focal images is easy. Additional Debian Dockerfiles are probably similar. For the other OS I have no idea how to do it. I'm assuming `el8` is Red Hat Enterprise Linux 8. So we can't create an image for that one. And CentOS 8 has reached EOL / is replaced by CentOS Stream 8? But not sure.

I could only find sources for Ubuntu images in https://github.com/OpenModelica/OpenModelicaBuildScripts/tree/master/docker. Is there another place where Dockerfiles are stored?

**Comment by AnHeuermann** [comment]
I'll manually push a version of https://github.com/AnHeuermann/build-deps/releases/tag/v1.22.0 without the non-root user to docker.openmodelica.org for now, so we can get this PR merged.

Then we can decide later on how to proceed with the build and upload process of build-deps Docker images.

**Comment by AnHeuermann** [comment]
I updated the image on [DockerHub](https://hub.docker.com/layers/anheuermann/openmodelica-build-deps/v1.22.1/images/sha256-b7b2f4f948832a70777e7c2f6a956c148d851c75b019ffaf5bae0267d24b3668?context=repo) and pushed the same image to docker.openmodelica.org/build-deps:v1.22.1.

The image is a bit large (4.6 GB). Maybe we should use an alpine image, if we support that OS that is.

**Comment by bilderbuchi** [comment]
> The image is a bit large (4.6 GB). Maybe we should use an alpine image, if we support that OS that is.

I'd be careful with that, Alpine is based on `musl` and not `glibc`, and for example this has no support for (gcc) profiling or some (all?) sanitizers (asan, ubsan,...).

**Pull request merged**
