### PR TITLE
Julia

### PR DESCRIPTION
**Pull request by JKRT**
Let's test

### CODE REVIEW

**Comment by sjoelund** [comment]
We still need to remove toJuliaOutput from all commits (and/or squash a lot). Should be easy with https://rtyley.github.io/bfg-repo-cleaner/ and then squash a lot at the same time

**Comment by adrpo** [comment]
Some tests fail also. Some because libraries changes, one due to parser changes it seems.

**Comment by adrpo** [comment]
Tests are updated in #389.

**Comment by adrpo** [comment]
This test fail is a bit weird: https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-385/6/tests/
LargeFileChange.mos – openmodelica_diff

**Comment by JKRT** [comment]
> 
> 
> We still need to remove toJuliaOutput from all commits (and/or squash a lot). Should be easy with https://rtyley.github.io/bfg-repo-cleaner/ and then squash a lot at the same time

I might need some help with this. I have done some minor rebasing before but I am afraid to mess things up. I would suggest melding all my summer commits into one and then maybe do it on an author basis

**Comment by sjoelund** [comment]
I'll try to do this and push --force. Be aware if you push to the julia branch on JKRT, then :)

**Comment by adrpo** [comment]
#389 fixes also the last failing test.

**Comment by sjoelund** [comment]
These commits now should not contain any reference to toJuliaOutput. They're about 100 fewer than before

**Comment by JKRT** [comment]
@sjoelund  @adrpo https://github.com/JKRT/OMCompiler.jl I backed up old toJulia here among some other things. I would need to use builddeps and some other things to get the parser and so on going again however

**Comment by sjoelund** [comment]
Honestly I think the parser deserves its own package. It's a very frequently requested feature to be able to access the OM AST.

**Comment by JKRT** [comment]
> 
> 
> Honestly I think the parser deserves its own package. It's a very frequently requested feature to be able to access the OM AST.

I really like that idea, in some way I find it pretty neat what we are currently doing. (Building a component based compiler)

Could you create one, add me and Adrian?

**Comment by JKRT** [comment]
> 
> 
> > Honestly I think the parser deserves its own package. It's a very frequently requested feature to be able to access the OM AST.
> 
> I really like that idea, in some way I find it pretty neat what we are currently doing. (Building a component based compiler)
> 
> Could you create one, add me and Adrian?

My basic idea, for now, is to have some sort of a core in that repository for the frontend and the backend with everything else algorithms and so on as dependencies. I think that would make for quite a neat design (However, atm I would like to run most of the stuff just adding everything to my path an run all.jl (Maybe rename to main.jl))

**Comment by sjoelund** [comment]
The main problem is that it's a bit of work to setup all the ANTLR stuff for the parser

**Comment by JKRT** [comment]
> 
> 
> The main problem is that it's a bit of work to setup all the ANTLR stuff for the parser

Lets move this discussion to https://github.com/JKRT/OMCompiler.jl

**Comment by JKRT** [comment]
Awaiting merge now? Or should something else be added

**Comment by adrpo** [comment]
I'm not sure we should push the parser changes (Modelica.g) in the OM repo. Even if the macros are defined to not do anything it clutters the current parser quite a bit.

**Comment by sjoelund** [comment]
There was some fix in there for the normal grammar as well :)

⁣Get BlueMail for Android ​

**Comment by adrpo** [comment]
That sounds bad, i'll see if i can find it and apply it to OM repo.
The parser stuff I'll try to move to OMCompiler.jl, is not that much work to setup ANTLR

**Comment by adrpo** [comment]
Why do we have OMEdit edits in here?

**Comment by adrpo** [comment]
ok, OMEdit files are gone now :)

**Pull request merged**
