### PR TITLE
Improve event handling by using dense output instead of hermite

### PR DESCRIPTION
**Pull request by bernhardbachmann**
### Purpose

Improve event handling by using dense output instead of hermite for interpolation during bisection

### CODE REVIEW

**Comment by bernhardbachmann** [comment]
@AnHeuermann Is the build again broken? Or, is it my fault?

**Comment by AnHeuermann** [comment]
Looks like it's a Jenkins issue. I restarted the job.

**Comment by AnHeuermann** [comment]
If there is no error message in Jenkins this usually means something broke. You can always check the log file of the Jenkins pipeline. In [this case](https://test.openmodelica.org/jenkins/job/OpenModelica/job/PR-10404/2/console) `cacheBranch` failed:
```
Error when executing failure post condition:
java.lang.NullPointerException: Cannot invoke method cacheBranch() on null object
```

**Comment by casella** [comment]
Excellent, thanks!

**Pull request merged**
