### PR TITLE
[BE] remove known variables for init lambda 0

### PR DESCRIPTION
**Pull request by kabdelhak**
- avoids hardcoded known variable binding equations and allows -override
 - ticket #6001

### CODE REVIEW

**Comment by adeas31** [comment]
Did you test OMEdit with it?

**Comment by kabdelhak** [comment]
> Did you test OMEdit with it?

No, but i don't see why it should not work with OMEdit.

**Comment by adeas31** [comment]
The actual ticket was reported for OMEdit resimulate which doesn't use override. It uses model_init.xml file but perhaps your fix handles that as well.

Do you want to test OMEdit?

**Comment by kabdelhak** [comment]
> The actual ticket was reported for OMEdit resimulate which doesn't use override. It uses model_init.xml file but perhaps your fix handles that as well.
> 
> Do you want to test OMEdit?

I always have problems building OMEdit. :(

But yes it should work the same. This PR avoids the creation of hardcoded bindings which prevented -override from working... applies the same to the init.xml i would assume

**Comment by adeas31** [comment]
Can you run the script I posted on the ticket?
I get the following output with your changes,

```
true
""
record SimulationResult
    resultFile = "",
    simulationOptions = "startTime = 0.0, stopTime = 50.0, numberOfIntervals = 500, tolerance = 1e-006, method = 'dassl', fileNamePrefix = 'Modelica.Fluid.Examples.Tanks.EmptyTanks', options = '', outputFormat = 'mat', variableFilter = '.*', cflags = '', simflags = '-override=tank1.level_start=1.2'",
    messages = "Simulation execution failed for model: Modelica.Fluid.Examples.Tanks.EmptyTanks
assert            | warning | The following assertion has been violated during initialization at time 0.000000
|                 | |       | tank1.level <= tank1.fluidLevel_max
assert            | error   | Vessel is overflowing (fluidLevel > fluidLevel_max = 1.2)
assert            | info    | simulation terminated by an assertion at initialization
",
    timeFrontend = 2.8481999,
    timeBackend = 0.1507156,
    timeSimCode = 0.0302018,
    timeTemplates = 0.1070016,
    timeCompile = 16.2107382
end SimulationResult;
""

""
```

We can add this to the testsuite.

**Comment by kabdelhak** [comment]
> Can you run the script I posted on the ticket?

Yes, this output is expected. The tank volume is capped at 1.0, if you use `-override=tank1.level_start=0.8` everything works fine.

**Comment by kabdelhak** [comment]
> We can add this to the testsuite.

I would rather add the minimal model right?

**Pull request merged**
