### PR TITLE
[OMEdit] Heuristics for scaling vector visualizers

### PR DESCRIPTION
**Pull request by anotheruserofgithub**
### Purpose

This PR implements methods for the automatic adjustment of radius & length scales of vector visualizers at initialization.
Some fixes are provided for non-critical issues.
Improvements in efficiency are also included.

### Approach

Four new attributes are attached to each vector visualizer and can be independently enabled or disabled:
- adjustable-radius,
- adjustable-length,
- scale-invariant,
- drawn-on-top.

The first two attributes inform whether radius scale and length scale can be adjusted, respectively.
The third attribute allows to continuously maintain a constant pixel size through the auto-scale feature of OSG's AutoTransform, particularly when zooming in/out the scene, which is very convenient to be able to compare vector lengths (meaning, their relative strength) all along the simulation.
The fourth attribute serves as a reinforcement for the previous one, because it renders vectors on top of everything else drawn in the scene, therefore not only small vectors but also tips of arrow heads are always visible and comparable (although this may sometimes break the notion of perspective).

Two separate kinds of adjustments are applied:
1. Radius scale: Browse fixed-radius vectors as well as relevant shapes to compute the median of their radii, and use this median value (± some constant factor) to scale the default radius of adjustable-radius vectors.
2. Length scale: For each vector quantity independently, increase the length of adjustable-length vectors for them to be clearly visible, while ensuring that the following two constraints are satisfied (both ± some constant margin), the first one taking precedence over the second one:
   - shaft lengths must be greater than zero in order to be comparable,
   - final camera distance to focal center must not be greater than initial distance computed without drawing adjustable-length vectors.

Implemented heuristics are thoroughly documented above and inside method [`VisualizationAbstract::chooseVectorScales`](https://github.com/OpenModelica/OpenModelica/pull/9389/commits/364b2cd9e7f939437fbdb03dfdaa96e65613592a#diff-003ee05536a1844c1876692266cec5626d4a656eaa622da88191b5ffcf95d3d6R620).
Default values of their parameters are defined [at the beginning of this same method](https://github.com/OpenModelica/OpenModelica/pull/9389/commits/364b2cd9e7f939437fbdb03dfdaa96e65613592a#diff-003ee05536a1844c1876692266cec5626d4a656eaa622da88191b5ffcf95d3d6R627-R633).

### Tests

- `Modelica.Mechanics.MultiBody.Examples.Elementary.ForceAndTorque`
- Below model containing only visualizers (shapes and vectors)
<details><summary>TestScalingVectorVisualizers.mo (click to expand)</summary>

```modelica
model TestScalingVectorVisualizers "Demonstrate animation of vector visualizers with automatic initial scaling"
  constant Boolean testMinimumLengthConstraint=true;
  import MB = Modelica.Mechanics.MultiBody;
  inner MB.World world;
  MB.Visualizers.Advanced.Shape s1(
    shapeType="cylinder",
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    r_shape={0,0,0},
    lengthDirection={-1,0,0},
    widthDirection={0,1,0},
    length=0.45,
    width=0.035,
    height=0.035,
    extra=0.0,
    color={255,0,0},
    specularCoefficient=0.7
  );
  MB.Visualizers.Advanced.Shape s2(
    shapeType="cylinder",
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    r_shape={0,0,0},
    lengthDirection={-1,0,0},
    widthDirection={0,1,0},
    length=0.45,
    width=0.035,
    height=0.035,
    extra=0.0,
    color={255,0,0},
    specularCoefficient=0.7
  );
  MB.Visualizers.Advanced.Shape s3(
    shapeType="cylinder",
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    r_shape={0,0,0},
    lengthDirection={-1,0,0},
    widthDirection={0,1,0},
    length=0.45,
    width=0.035,
    height=0.035,
    extra=0.0,
    color={255,0,0},
    specularCoefficient=0.7
  );
  MB.Visualizers.Advanced.Shape s4(
    shapeType="cylinder",
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    r_shape={0,0,0},
    lengthDirection={-1,0,0},
    widthDirection={0,1,0},
    length=0.45,
    width=0.035,
    height=0.035,
    extra=0.0,
    color={255,0,0},
    specularCoefficient=0.7
  );
  MB.Visualizers.Advanced.Shape s5(
    shapeType="cylinder",
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    r_shape={0,0,0},
    lengthDirection={-1,0,0},
    widthDirection={0,1,0},
    length=0.45,
    width=0.035,
    height=0.035,
    extra=0.0,
    color={255,0,0},
    specularCoefficient=0.7
  );
  MB.Visualizers.Advanced.Vector v1(
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    coordinates={(time+1)*1200,0,0},
    color={0,0,255},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Force,
    headAtOrigin=false,
    twoHeadedArrow=false
  );
  MB.Visualizers.Advanced.Vector v2(
    R=MB.Frames.nullRotation(),
    r={0,0,0},
    coordinates={-(time+1)*120,0,0},
    color={0,255,0},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Torque,
    headAtOrigin=false,
    twoHeadedArrow=false
  );
  MB.Visualizers.Advanced.Vector v3(
    R=MB.Frames.nullRotation(),
    r={0,0.1,0},
    coordinates={(time+1)*2*1200,0,0},
    color={0,0,255},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Force,
    headAtOrigin=true,
    twoHeadedArrow=true
  );
  MB.Visualizers.Advanced.Vector v4(
    R=MB.Frames.nullRotation(),
    r={0,0.1,0},
    coordinates={-(time+1)*2*120,0,0},
    color={0,255,0},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Torque,
    headAtOrigin=true,
    twoHeadedArrow=true
  );
  MB.Visualizers.Advanced.Vector v5(
    R=MB.Frames.nullRotation(),
    r={0,0.2,0},
    coordinates={(time+1)*8*1200,0,0},
    color={0,0,255},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Force,
    headAtOrigin=false,
    twoHeadedArrow=false
  ) if testMinimumLengthConstraint;
  MB.Visualizers.Advanced.Vector v6(
    R=MB.Frames.nullRotation(),
    r={0,0.2,0},
    coordinates={-(time+1)*8*120,0,0},
    color={0,255,0},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Torque,
    headAtOrigin=false,
    twoHeadedArrow=false
  ) if testMinimumLengthConstraint;
  MB.Visualizers.Advanced.Vector v7(
    R=MB.Frames.nullRotation(),
    r={-0.1,0.3,0},
    coordinates={-1,2,0},
    color={255,0,255},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Velocity,
    headAtOrigin=false,
    twoHeadedArrow=false
  );
  MB.Visualizers.Advanced.Vector v8(
    R=MB.Frames.nullRotation(),
    r={-0.1,0.3,0},
    coordinates={-2,1,0},
    color={255,255,0},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.Acceleration,
    headAtOrigin=false,
    twoHeadedArrow=true
  );
  MB.Visualizers.Advanced.Vector v9(
    R=MB.Frames.nullRotation(),
    r={-0.1,-0.2,0},
    coordinates={-1,-2,0},
    color={255,0,155},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.AngularVelocity,
    headAtOrigin=false,
    twoHeadedArrow=false
  );
  MB.Visualizers.Advanced.Vector v10(
    R=MB.Frames.nullRotation(),
    r={-0.1,-0.2,0},
    coordinates={-2,-1,0},
    color={255,155,0},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.AngularAcceleration,
    headAtOrigin=false,
    twoHeadedArrow=true
  );
  MB.Visualizers.Advanced.Vector v11(
    R=MB.Frames.nullRotation(),
    r={0,-0.25,0},
    coordinates={0.5,0.75,0},
    color={0,255,255},
    specularCoefficient=0.7,
    quantity=MB.Types.VectorQuantity.RelativePosition,
    headAtOrigin=false,
    twoHeadedArrow=false
  );
end TestScalingVectorVisualizers;
```
</details>

### Related Issues

- Complementary fix for #8211
- Proposal for custom annotations in #9390
- MSL discussion on scaling vectors by tools: modelica/ModelicaStandardLibrary#3991
- MSL `ForceAndTorque` model has color issue: modelica/ModelicaStandardLibrary#3989
- **TODO**: Consider the entire simulation interval (between start time and stop time) to determine if the length scale has shrunk the vectors too much, but this requires consistent discretization and might lead to highly expensive evaluations for long simulation intervals.

### CODE REVIEW

**Comment by anotheruserofgithub** [comment]
@adeas31 May I ask you to please have a look? This should go in v1.20 since animation of Vector will be introduced there.

Any feedback will be appreciated!

**Review by adeas31 — APPROVED** [review]
LGTM.

So the pending messages thing is only for debugging and is not actually used at the moment, right?

Please re-run the PR. @adrpo has fixed the CMake build.

**Comment by adeas31** [comment]
`/usr/bin/ld: ../OMEditLIB/libOMEditLib.a(Visualization.cpp.o): undefined reference to symbol 'glClear'`

Are you missing some dependency?

**Comment by anotheruserofgithub** [comment]
> `/usr/bin/ld: ../OMEditLIB/libOMEditLib.a(Visualization.cpp.o): undefined reference to symbol 'glClear'`
> 
> Are you missing some dependency?

Yeah, unfortunately I have to make a direct call to `glClear()` because OSG has no wrapper for it, so I need to add -lGL explicitly for the linker. I think I finally got it right, let's see what happens. Weird that it was working with `make` but not `cmake`, as I was not linking to GL in `configure.ac` either (added it now).

**Comment by anotheruserofgithub** [comment]
Well, now that I am thinking of it, it may be possible to actually to set the clear mask on the OSG render stage instead of calling `glClear()` directly ... Let me try something before merging ;)

**Comment by anotheruserofgithub** [comment]
I tried both ideas but could not make them work. Anyway, how I did is probably the most efficient way (despite having to explicitly link GL) so let's keep it like that.

**Comment by anotheruserofgithub** [comment]
And because the first commit changed the dumping of `BCONST` I also have to update the test models, let me take care of that.

**Comment by adeas31** [comment]
Maybe you need to fix the Windows libs linking as well. I added the Windows build. Lets see.

**Comment by anotheruserofgithub** [comment]
It passed all the builds, but I don't have a Windows installation to check that it works in practice.

**Comment by anotheruserofgithub** [comment]
> So the pending messages thing is only for debugging and is not actually used at the moment, right?

Exactly. I could have been more explicit in the documentation but it would have become a bit verbose.

This would typically be used for dumping the values of computed scales, or also (I had not thought about this before, but it is very unlikely) to raise warnings for the user and give hints on how to solve a problem.

Basically, it is crucial that the AutoTransform's scale is not changed during the whole adjustment process. Meaning, we must not go through a cull traversal, thus we must not render any new frame (except, of course, when triggering it explicitly with the `frame` argument). And the problem with GUI messages is that if the "Messages Browser" is not yet open, it will open, thus changing the aspect ratio of the animation window, therefore firing a Qt paint event hence a new OSG frame. This was one of the key issues I had with AutoTransform.

Of course, because we run single-threaded, the mutex is not necessary, but I think it is very much worth it because if someone does not know or forgets about this issue with GUI messages, then instead of seeing weird length scales (difficult to debug) they will actually encounter a deadlock, which is easy to spot directly in the code or with a debugger. Also, if one day the scene initialization or scale adjustment is decoupled from the frame rendering in separate threads, this should work straight away.

**Comment by adeas31** [comment]
I added the MINGW label that will trigger the Windows build.

**Comment by anotheruserofgithub** [comment]
Argh, I did something wrong... (removed/repushed all the commits to have a clean state)
Could you reopen this PR, would it work? Or do I really need to open a new one?

**Comment by anotheruserofgithub** [comment]
What a nightmare ... Sorry for the mess, I'm not used to github PRs yet.
I think it's good now, right?

**Comment by adeas31** [comment]
@anotheruserofgithub its failing again. I restarted the job.

**Comment by anotheruserofgithub** [comment]
```
Error: Curl error for URL https://github.com/modelica-3rdparty/Modelica_DeviceDrivers/archive/61247667adad45a1b769bfa0cd5011e33eafa513.zip: SSL connect error
Makefile:11: recipe for target '.openmodelica/libraries/20200610130629.stamp' failed
make[1]: *** [.openmodelica/libraries/20200610130629.stamp] Error 1
```
I guess it's not my fault ... Is it possible to rerun only the failing test or do you have to restart from the beginning?

**Comment by adeas31** [comment]
We have to rerun the whole thing. I restarted the job. We will see.

**Comment by adeas31** [comment]
Looks good now. Do you want me to merge or you have more changes?

**Comment by anotheruserofgithub** [comment]
It's OK, you can merge, please :)

**Pull request merged**
