### PR TITLE
No need to match special call

### PR DESCRIPTION
**Pull request by phannebohm**
Related to #12259 and #12133

### CODE REVIEW

**Comment by perost** [comment]
As the tests show this doesn't work, because a function call with literal arguments is not a literal expression. But actually I think it's `Call.isLiteral` that's wrong, I added cases for normal calls and reductions for the sake of completeness but on second thought that's not correct for what the function is meant to do.

I think you can just remove the first two cases from `Call.isLiteral` and only keep the array constructor one, along with this change, and if you need that functionality for something else you can just add e.g. `Call.hasLiteralArgs` or something instead.

**Comment by phannebohm** [comment]
Many of the failing tests involved impure functions, which shouldn't be literals. I want to see if excluding impure functions already fixes the tests.

**Comment by perost** [comment]
> Many of the failing tests involved impure functions, which shouldn't be literals. I want to see if excluding impure functions already fixes the tests.

I hope not, because function calls are still not literals regardless of purity. Even considering array constructors to be literals is a bit of a stretch honestly.

**Comment by perost** [comment]
Here's a model that's broken because `isLiteral` considers array constructors to be literals:
```Modelica
model M
  Real x[:] = -{1 for i in 1:3};
end M;
```
Array constructors could be considered literals if they were treated as such everywhere in the compiler, but that's not the case right now.

**Comment by phannebohm** [comment]
Okay, good point.

I think we did #12133 so that only start values that can be written into `init.xml` are removed from the initial system. Maybe that's the wrong way and we need to instead generate initial equations always. But then I guess modelers can't overwrite those start values, right?

**Comment by phannebohm** [comment]
With the current master omc, the model
```modelica
model M
  parameter Real p[:] = -{sin(i) for i in 1:3};
end M;
```
evaluates `sin(i)` and writes the correct values `-0.8414709848078965`, `-0.9092974268256817` and `-0.1411200080598672` in the `init.xml`. So this part at least is working both for the new and old backend.

**Comment by perost** [comment]
> Okay, good point.
> 
> I think we did #12133 so that only start values that can be written into `init.xml` are removed from the initial system. Maybe that's the wrong way and we need to instead generate initial equations always. But then I guess modelers can't overwrite those start values, right?

Maybe you just need some other criteria than if the expression is a literal? Maybe it's fine doing that for actual literals, but array constructors might need special handling? I don't really know.

But I see now that you added more cases to `isLiteral` that probably also shouldn't be there. To be clear, a literal expression is an expression that's evaluated to itself, so e.g. 2 is a literal but 1+1 isn't. So cast expressions are not literal since evaluating such an expression results in a different expression. Box/unbox expressions could technically be literals I guess, but I'm not sure what the implications of that would be.

**Comment by phannebohm** [comment]
True, then what we need is something like `canBeEvaluatedToALiteralElementwise`.

**Pull request merged**
