### PR TITLE
Update OMSimulator (arm64 support, etc)

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by lochel** [comment]
@sjoelund don't update OMSimulator without requesting a review. Those changes are not yet approved for the OpenModelica package.

**Comment by sjoelund** [comment]
It must be merged or the nightly builds fail

**Comment by lochel** [comment]
@sjoelund Who do you try to fool? The issue with the nightly build is that you enabled an unsupported target. Introducing potential regressions is not a reasonable approach. Start communicating, and stop sabotaging.

**Comment by sjoelund** [comment]
Then which branch should we merge/pull bugfixes to/from?

**Comment by lochel** [comment]
As I wrote earlier: You should make a pull request and request a review.

**Comment by sjoelund** [comment]
But it was reviewed: https://github.com/OpenModelica/OMSimulator/pull/1032 and we typically don't review in OpenModelica.git since the test suite is supposed to cover everything.

**Comment by lochel** [comment]
@sjoelund stop playing stupid. This pull request was not reviewed and you pushed changes that were not approved to work with OpenModelica.

**Comment by sjoelund** [comment]
Then which branch do we push simple bug fixes to in order to merge if you don't want things in OM? Do you need to have a develop branch in OMSimulator for things you didn't test?

**Comment by lochel** [comment]
Don't worry, the OMSimulator teams will take care of it. You should just create pull requests as always but then wait for a review :+1:

**Pull request merged**
