### PR TITLE
fixes for MacOS 

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

**Comment by lochel** [comment]
@adrpo do we still support mac?

**Comment by adrpo** [comment]
@lochel: not officially :)

**Comment by hkiel** [comment]
Do "port install findutils" and put /opt/local/libexec/gnubin first in your PATH
Should make this PR superfluous!?

**Comment by adrpo** [comment]
@hkiel I fixed that, then sundials could not find -lopenblas, i fixed that, now the compiler doesn't find `include <regex>`, I guess is some configure issue.

**Comment by adrpo** [comment]
Funny one: `CFLAGS=-stdlib=libstdc++ -std=c++11` that we seem to configure with will not find `#include <regex>`, remove -`stdlib=libstdc++` and regex will be found.

**Comment by adrpo** [comment]
> Do "port install findutils" and put /opt/local/libexec/gnubin first in your PATH
> Should make this PR superfluous!?
We really need to make some sort of howto for MacOS as there is a lot of information that is missing, like this one.

**Comment by adrpo** [comment]
Latest issue: omc links fine but then it doesn't run with undefined symbol _ffi_type_double.

**Comment by hkiel** [comment]
Strange enough: doing `configure` & `make` on a shell gives a fully working version, whereas doing `port mpkg openmodelica` leads to
```
record SimulationResult
    resultFile = "",
    messages = "Simulation execution failed for model: DGL
dyld: _dyld_bind_fully_image_containing_address() error
dyld: Symbol not found: _dgetrf
  Referenced from: /opt/local/var/macports/build/_opt_local_var_macports_sources_build.openmodelica.org_macports_lang_openmodelica/openmodelica/work/openmodelica_1.17.0~dev.beta1-3-gb286656/build/lib/x86_64-darwin18.7.0/omc/libsundials_sunlinsollapackdense.3.dylib
  Expected in: flat namespace
 in /opt/local/var/macports/build/_opt_local_var_macports_sources_build.openmodelica.org_macports_lang_openmodelica/openmodelica/work/openmodelica_1.17.0~dev.beta1-3-gb286656/build/lib/x86_64-darwin18.7.0/omc/libsundials_sunlinsollapackdense.3.dylib
/bin/sh: line 1: 31776 Abort trap: 6           ( \"/private/var/folders/v0/jwlb2_z56gzfjhxrxdd_0q2r0000gn/T/OpenModelica/DGL\" )
"
end SimulationResult;
```

**Comment by adrpo** [comment]
Yeah, I'm baffled by this symbol not found:
```
dyld: Symbol not found: _ffi_type_double
  Referenced from: /Users/hudson/jenkins-slave/ws/OpenModelica_PR-7238/OMCompiler/Compiler/runtime/libomcruntime-boot.dylib
  Expected in: flat namespace
 in /Users/hudson/jenkins-slave/ws/OpenModelica_PR-7238/OMCompiler/Compiler/runtime/libomcruntime-boot.dylib
```
Somehow the linker decides to not link *any* symbol from libffi.a in libOpenModelicaCompiler.dylib but doesn't report any error.

**Comment by adrpo** [comment]
Unfortunately this is mac, you fix everything, it compiles, it links, but then it still doesn't work :)

**Comment by hkiel** [comment]
@adrpo Seems to be a linking problem / library instance clash: the first ist the macports and links to `/opt/local/lib/libopenblas-r1.dylib`
```
$ otool -L /opt/local/var/macports/build/_opt_local_var_macports_sources_build.openmodelica.org_macports_lang_openmodelica/openmodelica/work/openmodelica_1.17.0~dev.beta1-3-gb286656/build/lib/x86_64-darwin18.7.0/omc/libsundials_sunlinsollapackdense.3.dylib
/opt/local/var/macports/build/_opt_local_var_macports_sources_build.openmodelica.org_macports_lang_openmodelica/openmodelica/work/openmodelica_1.17.0~dev.beta1-3-gb286656/build/lib/x86_64-darwin18.7.0/omc/libsundials_sunlinsollapackdense.3.dylib:
	@rpath/libsundials_sunlinsollapackdense.3.dylib (compatibility version 3.0.0, current version 3.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	@rpath/libsundials_sunmatrixdense.3.dylib (compatibility version 3.0.0, current version 3.4.0)
	/opt/local/lib/libopenblas-r1.dylib (compatibility version 0.0.0, current version 0.0.0)
```
This one is my own compiled (working) version, obviously linked to `/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib`
```
$ otool -L src/OpenModelica/build/lib/x86_64-darwin18.7.0/omc/libsundials_sunlinsollapackdense.3.dylib
src/OpenModelica/build/lib/x86_64-darwin18.7.0/omc/libsundials_sunlinsollapackdense.3.dylib:
	@rpath/libsundials_sunlinsollapackdense.3.dylib (compatibility version 3.0.0, current version 3.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
	@rpath/libsundials_sunmatrixdense.3.dylib (compatibility version 3.0.0, current version 3.4.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by adrpo** [comment]
@hkiel yeah, at least in your case you know what the problem is so hopefully can be solved. The libffi issue I have is really strange. I gave up on it and changed the code to use the system libffi and that works. Now it seems it doesn't build the qt clients somehow, I'll continue to investigate later, now I need a break.

**Comment by hkiel** [comment]
In configure you set `LDFLAGS=-L/opt/openmodelica/lib CPPFLAGS=-I/opt/openmodelica/include`
Is this good? Or does it mean that building the new version depends on a possibly old installation?
Same for your path. You set that to use /opt/openmodelica/bin and QTDIR to /opt/openmodelica/libexec/qt4

**Comment by hkiel** [comment]
> Now it seems it doesn't build the qt clients somehow, I'll continue to investigate later, now I need a break.

Maybe that is because they are not compiled?
`gmake -j16 --output-sync=recurse omc omc-diff omsimulator`

**Comment by adrpo** [comment]
They should be if you just call gmake without any targets (maybe configure on Mac is different, on Linux it works like that).
I'll investigate. As for the paths to `/opt/openmodelica/` they are (as far as I know) to required dependencies and software needed to compile stuff.

**Comment by adrpo** [comment]
Found the issue, @sjoelund added a make install test after building omc but it needs to be done after building the qt clients as the install target expects build/Applications directory to exist on MacOS. Let's see how far we get this time.

**Comment by hkiel** [comment]
> They should be if you just call gmake without any targets

Yes but you call gmake with the above targets. I copied that from your jenkins job.

**Comment by hkiel** [comment]
`/opt/openmodelica` should be empty on a pristine macports installation. It gets only populated when you install the mpkg. So it should also be empty when you build the mpkg, so why put it in LDFLAGS and friends? It can only cause problems when it is not empty at mpkg creatin time...

**Comment by adrpo** [comment]
> > They should be if you just call gmake without any targets
> 
> Yes but you call gmake with the above targets. I copied that from your jenkins job.

I know. That is the first stage that builds omc and then it should be followed by another that builds the qt clients where make without targets is called. I have now found why the second stage did not work and fixed it. Then i fixed some more rpath issues for libsundials*. Still some more rpaths remain to be fixed. I'll look into that.

**Comment by adrpo** [comment]
> `/opt/openmodelica` should be empty on a pristine macports installation. It gets only populated when you install the mpkg. So it should also be empty when you build the mpkg, so why put it in LDFLAGS and friends? It can only cause problems when it is not empty at mpkg creatin time...

Ok. I'll see what i can do about removing it.

**Pull request merged**
