### PR TITLE
Change OMEdit, OMPlot, OMNotebook, OMShell into git subtree

### PR DESCRIPTION
**Pull request by sjoelund**
The old git submodules have been removed since there is tight integration with the clients and it will be easier to use a Jenkins pull request workflow if the code in one repository.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-04-01_13-27-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6581/console).

**Comment by hkiel** [comment]
What about OMOptim and OMSimulator???

**Comment by sjoelund** [comment]
OMSimulator is developed as a mostly independent product. OMOptim is more likely to be removed from the repo as well, I think. It's still using only CORBA

**Comment by lochel** [comment]
The merged repositories should be made read-only.

**Comment by sjoelund** [comment]
We do need to create commits in the maintenance branches so the repositories shouldn't be archived. But I guess the master branches should be protected at least.

**Comment by sjoelund** [comment]
OK, talking to @adeas31 I guess we should archive the repositories and unarchive if we need to push to maintenance branches.

**Pull request closed without merging**
