### PR TITLE
Install OMEdit translation files with CMake

### PR DESCRIPTION
**Pull request by perost**

### CODE REVIEW

**Comment by adeas31** [comment]
You need to generate the *.qm files and they should be copied to `@OMBUILDDIR@/share/omedit/nls/`

See https://github.com/OpenModelica/OpenModelica/blob/master/OMEdit/Makefile.unix.in#L15

**Comment by perost** [comment]
> You need to generate the *.qm files and they should be copied to `@OMBUILDDIR@/share/omedit/nls/`
> 
> See https://github.com/OpenModelica/OpenModelica/blob/master/OMEdit/Makefile.unix.in#L15

I think they're generated automatically due to being listed in the `OMEdit.pro` file, at least they're generated for me when using CMake. And that is the location they're copied to, at least on Linux.

**Comment by adeas31** [comment]
I am confused now. If you are using CMake then .pro file is not used, right?

Have you tried regenerating them?

**Comment by adeas31** [comment]
https://doc.qt.io/qt-6/qtlinguist-cmake-qt-add-translations.html

**Comment by perost** [comment]
> I am confused now. If you are using CMake then .pro file is not used, right?
> 
> Have you tried regenerating them?

It's been so long since I used the autotools build that I assumed they must've been generated by CMake, but it seems you're right that they are not actually generated when using CMake. I'll see if I can add that.

**Comment by adeas31** [comment]
I don't see [lupdate](https://doc.qt.io/qt-6/linguist-lupdate.html#lupdate) and [lrelease](https://doc.qt.io/qt-6/linguist-lrelease.html#lrelease) being called for CMake build.

**Comment by perost** [comment]
#13093 should hopefully fix the issue that the translations files are not generated with CMake. Maybe there are better ways to do it, but it seems to work fine now and works with both Qt5 and Qt6.

**Comment by perost** [comment]
> #13093 should hopefully fix the issue that the translations files are not generated with CMake. Maybe there are better ways to do it, but it seems to work fine now and works with both Qt5 and Qt6.

And of course we don't have Qt5LinguistTools on Jenkins...

**Pull request merged**
