### PR TITLE
OMEdit: Qt6 compatibility

### PR DESCRIPTION
**Pull request by jschueller**
this is the first part of the qt6 port
/cc @adeas31

### CODE REVIEW

**Comment by adeas31** [comment]
When calling `cmake -S . -B build_cmake -DOM_QT_MAJOR_VERSION=6` I get,

```
Could NOT find Qt6Svg (missing: Qt6Svg_DIR)
CMake Error at OMEdit/CMakeLists.txt:13 (find_package):
```

What am I missing? I installed qt6 with `apt install qt6-base-dev` on WSL.

```
qmake6 --version
QMake version 3.1
Using Qt version 6.2.4 in /usr/lib/x86_64-linux-gnu
```

**Comment by jschueller** [comment]
try libqt6svg6-dev

**Comment by adeas31** [comment]
I managed to install all sub-packages. The CMake configuration still fails,

```
-- Configuring done
CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt5::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "OMEditLib".

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by jschueller** [comment]
maybe it requires the port of OMPlot first

**Comment by perost** [comment]
> ah maybe it requires the port of OMPlot first from #11581

It seems to work fine for me on Arch Linux at least (with both qt5 and qt6 installed), so it's probably something else.

**Comment by adeas31** [comment]
Seems its related to https://github.com/OpenModelica/OpenModelica/pull/11581. I can configure https://github.com/OpenModelica/OpenModelica/pull/11581 but not this PR.

**Comment by jschueller** [comment]
yes, it looks like the commits are interdependent so I cannot isolate this one from #11581

**Pull request closed without merging**
