### PR TITLE
[BE] update ASSC algorithm

### PR DESCRIPTION
**Pull request by kabdelhak**
- add support for real valued coefficients
 - switch from list to hash map structures for more efficient value searches

### Related Issues
Trac ticket #5817
- some more ASSC and scalable testsuite stuff

### Purpose
Supporting real valued coefficients and fixing performance issues.

### Approach
Using UnorderedMap instead of lists

### CODE REVIEW

**Review by adrpo — APPROVED** [review]
As far as I can see seems fine. 
Did you wanted to update OMOptim as well?

**Comment by kabdelhak** [comment]
> As far as I can see seems fine.
> Did you wanted to update OMOptim as well?

No... did i update a submodule by accident again? :/

**Comment by casella** [comment]
> 
> 
> > As far as I can see seems fine.
> > Did you want to update OMOptim as well?
> 
> No... did i update a submodule by accident again? :/

It's weird, it seems that OMOptim was updated, but the diff file is empty

I'm eager to see this merged in and see what the effects are, though 😄

**Comment by adrpo** [comment]
I merged it, if there are issues I'll sort them later.

**Pull request merged**
