### PR TITLE
Be nice to the cache

### PR DESCRIPTION
**Pull request by phannebohm**
Change the order of several for loops involved in calculating matrix
products where the matrix is in column-major form.

Fixes issue addressed by 78e98dab18f7b855c50a88cd4c5890ec14927ef2

### CODE REVIEW

**Comment by AnHeuermann** [comment]
Is there really a point in trying to fix our own basic matrix multiplication? We are using BLAS and LAPACK in omc already and they do quiet a good job with this kind of things.

Sure for a small matrix we can use a simple implementation to do some matrix vector multiplication but when they get bigger we should really use BLAS. E.g replacing matVecMult with [sgemv](http://www.netlib.org/lapack/explore-html/d6/d30/group__single__blas__level2_gafc92361b74c6d41c7e5afa0aa5d13ec9.html#gafc92361b74c6d41c7e5afa0aa5d13ec9).
And if the matrices get really big you could even use a BLAS optimized for your compiler.

**Comment by phannebohm** [comment]
> Is there really a point in trying to fix our own basic matrix multiplication? We are using BLAS and LAPACK in omc already and they do quiet a good job with this kind of things.
> 
> Sure for a small matrix we can use a simple implementation to do some matrix vector multiplication but when they get bigger we should really use BLAS. E.g replacing matVecMult with [sgemv](http://www.netlib.org/lapack/explore-html/d6/d30/group__single__blas__level2_gafc92361b74c6d41c7e5afa0aa5d13ec9.html#gafc92361b74c6d41c7e5afa0aa5d13ec9).
> And if the matrices get really big you could even use a BLAS optimized for your compiler.

Yeah that's a good point. And for the matrix size where my changes matter, BLAS is probably better in any case. No idea what the optimized BLAS would do. Is it adjusting to the hardware?
In the future, it might potentially be a good idea to write some kind of interface for these instances, so we can swap the underlying library without pain...

I was just trying to get some low hanging fruit.

**Comment by casella** [comment]
I'd merge this in and see if we get improvements on the testsuite.

**Comment by casella** [comment]
@phhannebohm, are these corrections only involving dense Jacobians?

**Comment by phannebohm** [comment]
> @phhannebohm, are these corrections only involving dense Jacobians?

As far as I can see, yes. Those functions can't operate on sparse matrices, unless they are made dense somewhere.

**Comment by casella** [comment]
OK. I'm still struggling to make sense of @sjoelund's comments about the huge dense matrix handled by the simulation executable of the large grid test case. I guess that was because he didn't set `--daeMode` as compiler flag and `-nls=kinsol` as simulation flag, which is essential to get the proper solvers used, as of today.

Regarding simulation, I understand `--daeMode` only generates code for the sparse solver. I'm not sure about initialization code, though. Is the same C code reused for sparse and dense solvers, depending on which solver is selected at runtime, or are two separate sets of C functions generated for the former and the latter?

**Comment by phannebohm** [comment]
> OK. I'm still struggling to make sense of @sjoelund's comments about the huge dense matrix handled by the simulation executable of the large grid test case. I guess that was because he didn't set `--daeMode` as compiler flag and `-nls=kinsol` as simulation flag, which is essential to get the proper solvers used, as of today.
> 
> Regarding simulation, I understand `--daeMode` only generates code for the sparse solver. I'm not sure about initialization code, though.

To be honest, I have little to no knowledge about the specifics of `--daeMode` and also about initialization. :innocent: 

> Is the same C code reused for sparse and dense solvers, depending on which solver is selected at runtime, or are two separate sets of C functions generated for the former and the latter?

What I edited here are low level functions. By design they have to be different for sparse and dense systems. I don't know about the rest...

**Comment by phannebohm** [comment]
I looked a little deeper. Specifically in this function:
https://github.com/OpenModelica/OpenModelica/blob/a1c10032e83c97189b081f0fec44c5eb769692c4/OMCompiler/SimulationRuntime/c/simulation/solver/nonlinearSolverHomotopy.c#L817
If I understand this correctly, from the sparse matrix representation we create a dense matrix for the nonlinear solver. That means the equations to calculate the entries in the sparsity pattern are nice and sparse. But we end up with a big dense matrix with `double` entries, many of them being zero I guess.

**Comment by casella** [comment]
OK, so the big dense matrix is only malloc'ed and filled in if a dense solver is picked at runtime, otherwise it's not really there. I understand the internal representation of Jacobians is always sparse, coming from structural analysis. Do i get this right?

**Comment by phannebohm** [comment]
I think so

**Comment by casella** [comment]
Sounds good

**Pull request merged**
