### PR TITLE
Create CITATION.bib

### PR DESCRIPTION
**Pull request by JKRT**
Added a citation file to the repository

### Purpose

The purpose is to add citation metadata to the OpenModelica repository.

### CODE REVIEW

**Comment by sjoelund** [comment]
We already have https://github.com/OpenModelica/OpenModelica/blob/master/doc/bibliography/openmodelica.bib

**Comment by JKRT** [comment]
> We already have https://github.com/OpenModelica/OpenModelica/blob/master/doc/bibliography/openmodelica.bib (which is used to update the webpage https://www.openmodelica.org/research/journal-papers)

Right, I know. 
The reason for this file is to get a quick link in the Github UI:
image

I have updated the file to provide a link to:  https://github.com/OpenModelica/OpenModelica/blob/master/doc/bibliography/openmodelica.bib

**Comment by sjoelund** [comment]
Wouldn't CITATION.cff make more sense then? It has support for custom message at the top...

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by JKRT** [comment]
> CITATION.cff

Agreed I'll change it to .cff 💯 and update the PR

**Comment by sjoelund** [comment]
Why close the PR? You could just push force a new commit :)

**Comment by JKRT** [comment]
> Why close the PR? You could just push force a new commit :)

I made a weird branch by mistake. Used to have my own repositories. In a meeting now will create a new one soon and add you as reviewer:)

**Comment by sjoelund** [comment]
Why change it to software? It's an article, right?

**Comment by JKRT** [comment]
> 
I just fixed it. Typically CFF is for specific variants of software if one wants a user to cite an article instead the CFF file needs to be modified slightly. My latest commit should address this 

This is a quite useful excursion for me into the land of cff files 🤓 
Will ping you when I am done

**Comment by JKRT** [comment]
@sjoelund I think this is as far as I can go. There seem to be a bug with the custom message on the GitHub side for now.. for now I point to the extended bibliography in the .CFF file instead

**Comment by AnHeuermann** [comment]
Ups, I added an `CITATION.cff` in #10744 without noticing this PR.

**Comment by JKRT** [comment]
> Ups, I added an `CITATION.cff` in #10744 without noticing this PR.

Maybe we should close it then I think both me and Martin forgot about it:)

**Pull request closed without merging**
