### PR TITLE
FreeBSD fixes

### PR DESCRIPTION
**Pull request by yurivict**
### Purpose

Upstream FreeBSD build fixes from the FreeBSD port.

### CODE REVIEW

**Comment by adrpo** [comment]
After we fix it, I think we should add a FreeBSD job so we can detect is we break things. Do you have some info on how you build OM on FreeBSD?

**Comment by adrpo** [comment]
It seems you cannot have a docker image with FreeBSD on a non-FreeBSD host ... too bad, we would need to install a computer with it or run it in a VM.

**Comment by yurivict** [comment]
> Do you have some info on how you build OM on FreeBSD?

Additionally, shebangs should be fixed in 2 places:
* [here](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Examples/GenerateDoc.mos#L370C27-L370C38)
* [and here](https://github.com/OpenModelica/OMCompiler-3rdParty/blob/4bcf74abed8846a407e8d5fa1344749003a75f38/tbb/build/generate_tbbvars.sh#L1)

(they should be ```#!/usr/bin/env bash```)

Then OpenModelica should just build.


> It seems you cannot have a docker image with FreeBSD on a non-FreeBSD host ... too bad, we would need to install a computer with it or run it in a VM.

GitHub has a way to test projects under FreeBSD:
https://github.com/marketplace/actions/freebsd-vm
As an example, this project has FreeBSD tests setup this way:  https://github.com/celtera/libremidi/

Additionally, Cirrus CI supports FreeBSD: https://cirrus-ci.org/guide/FreeBSD/

**Comment by adrpo** [comment]
I will continue the other changes in PR #13429.

**Pull request merged**
