### PR TITLE
Make it possible to use a label to force OSX builds in PR

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by sjoelund** [comment]
@adrpo @lochel any thoughts on the name of the label? Maybe PR_BUILD_OSX instead? It seems to work as expected, but required an additional plugin to be installed (Pipeline: GitHub, but this might be very useful to do things like notifying users of build status, etc if we want it)... (Now up to 131931288318318093109 Jenkins plugins)

**Comment by sjoelund** [comment]
Actually, one thing is wrong: it needs to allocate the slave in order to skip the job. I have some ideas on fixing that though.

**Comment by lochel** [comment]
That's nice! If it works well then we want it for the OMSimulator project too.

**Comment by lochel** [comment]
Regarding the naming: It is of course a matter of taste. Another idea would be to use `Jenkins` as prefix, followed by a slash, e.g. `Jenkins/tests-osx`, `Jenkins/update-submodules` and so on.

**Comment by sjoelund** [comment]
So it seems that by introducing global variables, we can make the check before the agent is allocated (so no Mac/Windows machines need to be available to skip the task)

**Pull request merged**
