### PR TITLE
Fix DynamicSelect for nfAPI

### LINKED ISSUE #5631: Fix DynamicSelect for new API

### PR DESCRIPTION
**Pull request by perost**
- Remove constant evaluation of DynamicSelect, since DynamicSelect is
  impure anyway and should never be constant evaluated.
- Implement the same simplification rules for DynamicSelect that the OF
  uses:
    DynamicSelect("%y", String(y, significantDigits = 3)) => {"%y", y, 3}
    DynamicSelect(true, y) => {true, y}
    DynamicSelect(arg, ...) => arg

Fixes #5631

### CODE REVIEW

**Comment by perost** [comment]
With this fix the nfAPI should give almost identical output for DynamicSelect as the old API. The only real difference is that we handle this during simplification, at which point we don't know if the significantDigits argument to String was given by the user or from the default argument. But I guess always including significantDigits in the array doesn't matter.

**Comment by perost** [comment]
I missed that there was already a test case for nfAPI, so I updated that one instead of changing another to use the nfAPI.

**Review by adrpo — APPROVED** [review]
OK by me, small typo in commit message could be fixed "Dynamci"

**Comment by adrpo** [comment]
Note that one might need to constant evaluate the first argument of DynamicSelect.

**Comment by perost** [comment]
> OK by me, small typo in commit message could be fixed "Dynamci"

Not sure where you see that, I can't find it.

> Note that one might need to constant evaluate the first argument of DynamicSelect.

The first argument to DynamicSelect must be a literal value according to the specification. It seems we don't check that, but there shouldn't be any reason to constant evaluate it at least.

**Comment by adrpo** [comment]
Hm, I think I've seen cases where parameters or constants were used in the annotations.

**Pull request merged**
