### PR TITLE
Replaceable redeclare support squashed 4

### PR DESCRIPTION
**Pull request by mahge**
Attempt to rebase Adrian's changes on master.

At least it is merged whole now. There might be changes from Adrian that got lost through the conflicts. But this way we can be sure that we have not missed commits from master.

### CODE REVIEW

**Comment by casella** [comment]
It seems @mahge's efforts were successful 👍 

@adrpo, can we merge this into master?

**Comment by mahge** [comment]
@casella Okay I just noticed that some recent changes from master OMEdit are missing. I am gonna add them. This still needs some manual checkup before merging.

**Comment by casella** [comment]
> 
> 
> @casella Okay I just noticed that some recent changes from master OMEdit are missing. I am gonna add them. This still needs some manual checkup before merging.

OK

**Comment by casella** [comment]
@adrpo, is this PR from @mahge still relevant? Can it help you resolving the pending issues with 1.15.0 and finally merge it?

**Pull request closed without merging**
