### PR TITLE
Add WIP README, update conf.py to Python3

### PR DESCRIPTION
**Pull request by AnHeuermann**
- Added README to doc/ (because I was to stupid to find doc/UsersGuide/README.md)
- Used [2to3](https://docs.python.org/3/library/2to3.html ) to update doc/UsersGuide/source/conf.py.
- Updated User's Guide on homotopy initialization.
- Fixed broken disbplay of example in User's Guide

### CODE REVIEW

**Comment by AnHeuermann** [comment]
@casella I updated the homotopy description.
You can find the generated User's Guide with my changes at https://test.openmodelica.org/jenkins/job/OpenModelica/job/PR-6991/3/artifact/OpenModelicaUsersGuide-latest.html.tar.xz.
Just unpack `OpenModelicaUsersGuide-latest.html.tar.xz` and open `index.html` with your favorite browser and browse to OpenModelicaUsersGuide/solving.html#homotopy-method

**Comment by casella** [comment]
Thanks @AnHeuermann! Good that we now have all the homotopy flags collected at one place :)

There are still a few minor issues:

- The footnote 3 is very generic, citing the whole Modelica Specification is a bit obvious. Maybe you can be more specific and cite Section 3.7.2.4 of Modelica 3.4. You may actually put a [link](https://specification.modelica.org/maint/3.4/Ch3.html#homotopy) to that. 
- Reference OB13 is a bit old and could be quite confusing, because it mostly discusses "start value homotopy" which is a default homotopy defined inside our in-house nonlinear solver. This has _nothing_ to do with the `homotopy()` operator, which is actually not discussed much (if at all) in that paper. I would suggest to also cite the Modelica Conference paper by Sielemann et al "Robust Initialization of Differential-Algebraic Equations Using Homotopy", that gives a nice introduction to the topic.
- Regarding local/global and fixed step/adaptive homotopy, the description is a bit concise. That's ok, at least I would say what is the default behaviour. BTW, the non-normative part of the specification says: "It is recommended to perform (conceptually) one homotopy iteration over the whole model, and not several homotopy iterations over the respective non-linear algebraic equation systems" and explains why, so I'm not even sure why we provid local homotopy at all.
- In the case of adaptive lambda, it would be good to have some reference at the used algorithm. Is it an in-house implementation, or does it use an existing solver? Is it using a continuation solver, that can get over bends? Is there any paper or presentation that we can link to?
- There are several typos: methos->methods, eqidistant->equidistant, effects->affects (this is within `--homotopyApproach`)

One last comment - I understand that the current default for `--homotopyApproach` is equidistantGlobal. Maybe we should add some logic that tries adaptiveGlobal if that fails, e.g. because the first steps are too large.

I guess at some point we could also try to switch the default to adaptiveGlobal and see what happens, but that's not urgent

-

**Comment by AnHeuermann** [comment]
Thanks for the feedback, I'll change it today.

> I guess at some point we could also try to switch the default to adaptiveGlobal and see what happens, but that's not urgent

I tried that at one point some time ago and noticed that most (if not all) models that are running with equidistant are using more then the 4 steps (which are actually only 3 reals steps) used more homotopy steps during initialization.

Do you have an example where equidistant homotopy fails bur adaptive works? I didn't searched for one yet.

**Comment by casella** [comment]
> Thanks for the feedback, I'll change it today.

OK, great!
 
> > I guess at some point we could also try to switch the default to adaptiveGlobal and see what happens, but that's not urgent
> 
> I tried that at one point some time ago and noticed that most (if not all) models that are running with equidistant are using more then the 4 steps (which are actually only 3 reals steps) used more homotopy steps during initialization.

So it seems that the current option is the best. Only, we'd need an automatic fallback to adaptive in case fixed step fails. Can we do that easily?
 
> Do you have an example where equidistant homotopy fails bur adaptive works? I didn't searched for one yet.

No. I tried to build one
```
model DifficultHomotopy
  Real w,p;
  parameter Real p0 = 1;
equation
  w = homotopy(1e4*sqrt(p0 - p), p0 - p);
  w = homotopy(sqrt(p), p);
  annotation(__OpenModelica_simulationFlags(lv = "LOG_INIT,LOG_NLS_V"));
end DifficultHomotopy;
```
but it fails with
```
[1] 11:46:25 Translation Error
[C:/dev/OM64bit/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 342:7-342:48]: Internal error BackendDAETransform.analyseStrongComponentBlock failed
variables:
  p
  w
equations:
  w = p
  w = p0 - p
```
which is kind of weird. What's wrong with those equations? The solution is obviously `w = p = p0/2`

**Comment by AnHeuermann** [comment]
>So it seems that the current option is the best. Only, we'd need an automatic fallback to adaptive in case fixed step fails. Can we do that easily?

Probably, I'll try it in a different PR

**Comment by casella** [comment]
@AnHeuermann I looked at the documentation and it's good now.

The only remaining issue is that you now actually mention 3 steps by default, which is fine, but that corresponds to `-ils = 4`, which is weird, see [ticket:5766#comment:9](https://trac.openmodelica.org/OpenModelica/ticket/5766#comment:9).

Three steps are fine, but the the argument of `-ils` should really means "number of steps", not "number of lambda values", as it is today.  As required in [#5766](https://trac.openmodelica.org/OpenModelica/ticket/5766), I would suggest to update `ils` to really mean number of steps, and to set its default to 3, so we keep the same results as we have now.

**Comment by AnHeuermann** [comment]
@casella Yeah you are right and I ignored that for to long now. So I present PR #7033 🎉 
I hope I found all locations where this was wrong.

**Pull request merged**
