### PR TITLE
Ask the user which version of MSL to load and save that settings

### LINKED ISSUE #6379: Placeholder
This is a placeholder created during migration to preserve original issue numbers.

----

Migrated-From: https://trac.openmodelica.org/OpenModelica/ticket/6379

### PR DESCRIPTION
**Pull request by adeas31**
Fixes #6379
OMEdit shows a window on start up that asks the user which version of MSL to use.
The window is only shown once and the settings are saved for future use.

### CODE REVIEW

**Comment by adeas31** [comment]
@casella the following pop-up is shown on OMEdit start now,

image

**Comment by adeas31** [comment]
The pop-up is triggered based on the setting `MSLVersion` in `omedit.ini` file. The reset of settings file will trigger the pop-up again.

**Comment by lochel** [comment]
Is msl 3.2.3 the preselected choice as shown in the screenshot? Maybe none of the options should be preselected to force the user to make a initial choice.

**Comment by sjoelund** [comment]
I would write it as v3.2.3 v4.0.0. Don't write officially released: we modify the MSL slightly for OpenModelica (especially ModelicaServices). "pre-installed version modified for OpenModelica" perhaps?

**Comment by adrpo** [comment]
are -> is: Conversion script support *is* planned

**Comment by adrpo** [comment]
Wait, no, that one is weird, remove "support" -> Conversion scripts are planned to be supported ...

**Comment by adeas31** [comment]
image

**Review by adrpo — APPROVED** [review]
LGTM!

**Comment by adeas31** [comment]
We should update the options text as well. `when starting OMEdit` in each option is not nice. Maybe something like,

> Please choose one startup option:
> - [ ] Load MSL v3.2.3
> - [ ] Load MSL v4.0.0
> - [ ] Do not load MSL

**Comment by sjoelund** [comment]
Maybe not say `apt-get` because we have RPMs, too. Or Arch/etc... `On Linux, follow the instructions on the download page.`

And I suppose the user might want to install MSL v4.1.0. Then explain that other versions installed by the user can be set in the Options dialog. `which version you want to load (including older or newer MSL versions installed manually).`

`; see link for further information` -> `(further information)`

**Comment by casella** [comment]
> 
> 
> Wait, no, that one is weird, remove "support" -> Conversion scripts are planned to be supported ...

Conversion script support is planned in v1.18.0.

**Comment by casella** [comment]
> Maybe not say `apt-get` because we have RPMs, too. Or Arch/etc... `On Linux, follow the instructions on the download page.`

SGTM
 
> And I suppose the user might want to install MSL v4.1.0. Then explain that other versions installed by the user can be set in the Options dialog.

There is currently no such version available. Only as development version. I'm not sure when it will be released, because Thomas and Dietmar resigned and MAP-LIB is currently without a leader, but I guess it won't be before we release v1.18.0.

I would suggest to KISS for the time being :)
 `which version you want to load (including older or newer MSL versions installed manually).`
> 
> `; see link for further information` -> `(further information)`

**Comment by sjoelund** [comment]
> @sjoelund, I'm not sure which link you refer to here

There's a blue text that says `link`. That just looked weird to me

**Comment by casella** [comment]
> > @sjoelund, I'm not sure which link you refer to here
> 
> There's a blue text that says `link`. That just looked weird to me

Ah, ok, I agree. I always struggle with this meta-issue :)

**Comment by adeas31** [comment]
Here is how it looks like now,

image

**Comment by casella** [comment]
LGTM. 

Maybe we could change "pre-installed version modified for OpenModelica" into "pre-installed version customized for OpenModelica". But that's no big deal.

**Comment by adeas31** [comment]
Hopefully the final outcome,

image

**Review by lochel — APPROVED** [review]
Looks good to me. The only complaint might be that one is forced to read a lot of text in a pop-up window which generally isn't appreciated.

**Comment by casella** [comment]
> Looks good to me. 

Same to me

>The only complaint might be that one is forced to read a lot of text in a pop-up window which generally isn't appreciated.

I am painfully aware of that. This looks like borderline legalese and is for sure too long, though I don't know how to make it significantly shorter without loosing essential information.

The truth is, transitioning from MSL 3.2.3 to 4.0.0 requires some understanding of a few facts in order to be done right. We know them well, but some (most?) users who are not well versed in the the rituals and arcana of the Modelica community have no idea. They may just end up with all their stuff apparently broken, no models working anymore, and completely clueless. The next step would be to blame OpenModelica for the mess and stop using it outright. We really need to avoid that...

As I see it, there is no way to hide this transition from the users, which have to be well aware of that.

So, this is deliberatly annoying, because people must pay attention. I guess they can do that once every 10 years :)

And there is no default choice, because you really need to take a decision yourself.

**Comment by casella** [comment]
@adeas31, please also push this into maintenance/1.17

**Pull request merged**
