### PR TITLE
Fixed illegal use of pre(continuous_var)

### PR DESCRIPTION
**Pull request by casella**

### CODE REVIEW

**Comment by casella** [comment]
As required after discussion at the 01 Dec 2020 devmeeting

**Review by AnHeuermann — APPROVED** [review]
LGTM

**Comment by casella** [comment]
Wooo, my first pull request went fine 🥇

**Comment by perost** [comment]
Thank you! Now you can start fixing your own issues :smile:

**Comment by casella** [comment]
Ops... :P

**Pull request merged**
