### PR TITLE
Fix for OMSICpp msvc build

### PR DESCRIPTION
**Pull request by AnHeuermann**
Fix failing build for Cpp runtime with MSVC.

The Error message on Jenkins for msvc looks like
```
-- A library with LAPACK API not found. Please specify library location.
-- Lapack Libraries
-- C:\OMDev/lib/3rdParty/Lapack/Lib/lapack_win32.libC:\OMDev/lib/3rdParty/Lapack/Lib/blas_win32.lib
-- Sundials include:
-- C:/dev/jenkins/ws/OpenModelica_PR-243/OMCompiler/SimulationRuntime/OMSICpp/../../3rdParty/sundials/build_msvc/include/
-- Sundials library for omsicpp:
-- C:/dev/jenkins/ws/OpenModelica_PR-243/OMCompiler/SimulationRuntime/OMSICpp/../../3rdParty/sundials/build_msvc/lib/
-- ./tmp/
-- Found config file C:/dev/jenkins/ws/OpenModelica_PR-243/OMCompiler/SimulationRuntime/OMSICpp/../../3rdParty/sundials/build_msvc/include//sundials/sundials_config.h
-- Using sundials 2.6.2
-- Sundials Libraries for omsicpp:
-- C:/dev/jenkins/ws/OpenModelica_PR-243/OMCompiler/3rdParty/sundials/build_msvc/lib/sundials_nvecserial.lib;C:/dev/jenkins/ws/OpenModelica_PR-243/OMCompiler/3rdParty/sundials/build_msvc/lib/sundials_cvode.lib;C:/dev/jenkins/ws/OpenModelica_PR-243/OMCompiler/3rdParty/sundials/build_msvc/lib/sundials_cvodes.lib;C:/dev/jenkins/ws/OpenModelica_PR-243/OMCompiler/3rdParty/sundials/build_msvc/lib/sundials_idas.lib;C:/dev/jenkins/ws/OpenModelica_PR-243/OMCompiler/3rdParty/sundials/build_msvc/lib/sundials_kinsol.lib
-- FMI lib include:
-- C:/dev/jenkins/ws/OpenModelica_PR-243/OMCompiler/SimulationRuntime/OMSICpp/../../3rdParty/FMIL/install_msvc/include
-- FMI lib library:
-- C:/dev/jenkins/ws/OpenModelica_PR-243/OMCompiler/SimulationRuntime/OMSICpp/../../3rdParty/FMIL/install_msvc/lib
-- OMSI lib library:
-- ./tmp/lib/omc/omsi/msvc
-- LIB_OMC = 
CMake Error at CMakeLists.txt:707 (MESSAGE):
  Could not find omsi base library in: ./tmp/lib/omc/omsi/msvc
```

### CODE REVIEW

**Comment by adrpo** [comment]
Ah, you were faster than me, I also fixed this :)

**Comment by AnHeuermann** [comment]
Well I'm not shure it realy solves the msvc problem... Maybe we need to merge our fixes

**Comment by adrpo** [comment]
Probably, I already merged yours into mine, I will check it msvc stuff works and open a PR with it.

**Comment by AnHeuermann** [comment]
Then I'll close this PR and let it rest for the weekend

**Pull request closed without merging**
