### PR TITLE
Fix for CircuitDC

### PR DESCRIPTION
**Pull request by TeusvanderStelt**

### CODE REVIEW

**Comment by adrpo** [comment]
@TeusvanderStelt please remove the change to `OMCompiler/3rdParty` submodule and then resolve conflicts in the `newton_diagnostics.c`

**Comment by adrpo** [comment]
Looks like you somehow kept the changes from previous commit and piled some more changes on top of them. 
After you integrate a PR in master you should update you working copy to the master (from origin) then make a new branch where you do the new modifications.

So the usual workflow is like this:

First you clone the repo and set your remote:
```
# clone the original repo
git clone https://github.com/OpenModelica/OpenModelica.git
cd OpenModelica
# add your repo on github (I named it tvs)
git remote add tvs https://github.com/TeusvanderStelt/OpenModelica
```
Then you can just do this for each change:
# update master from origin, I usually use this script, you can reuse it if you want.

```
#!/bin/bash -x
git checkout master
git fetch origin && git submodule foreach git fetch origin
git pull --recurse-submodules && git submodule update --init --recursive
git submodule foreach --recursive "git checkout master"
git submodule foreach --recursive "git pull"
git submodule update --init --recursive
git status
git submodule status --recursive
```

Now make your own branch from master:
```
git checkout -b YourNewBranch
# change what you want if the code and add only the files you need to change
git add file or directory
git commit -m "message"
# now you push to your repository remote on github
git push tvs YourNewBranch
# this will tell you a link which you can use to create a PR on github web interface
```

After your PR is merged you can delete your branch, update your repo from origin/master and make a new branch.

If you need to update your branch with some recent changes from master before you push your PR you can do:

```
# switch to your branch
git checkout YourNewBranch
# change what you want if the code and add only the files you need to change
git add file or directory
git commit -m "message"
# now switch to master and update master to origin/master
# then switch back to your branch
git checkout YourNewBranch
# rebase the changes from master
git rebase master
```

Of course you can find your own workflow but you should make sure you always start from origin/master, not your own remote master or previous branches.

**Comment by casella** [comment]
I made it into a draft so we are not merging in the old OMDev again.

**Comment by adrpo** [comment]
Ported to another PR.

**Pull request closed without merging**
