### PR TITLE
CMake FMU export on M1 Apple

### PR DESCRIPTION
**Pull request by AnHeuermann**
### Related Issues

Fixes https://github.com/OpenModelica/OpenModelica/issues/10238.

### Purpose

Enable CMake FMUs on M1 Apple machines.

### Approach

  - Disable linker flag `--no-undefined` on APPLE.

### CODE REVIEW

**Comment by AnHeuermann** [comment]
@mahge Can you test this PR on a M1 machine?

## Test
```
loadModel(Modelica); getErrorString();
setCommandLineOptions("--fmuCMakeBuild=true --fmuRuntimeDepends=none"); getErrorString();
buildModelFMU(Modelica.Blocks.Examples.PID_Controller, platforms={"dynamic"}); getErrorString();
```

and afterwards simulate with OMSimulator

```bash
OMSimulator Modelica.Blocks.Examples.PID_Controller.fmu
```

**Comment by mahge** [comment]
Sure. I will check and let you know.

**Comment by mahge** [comment]
Works fine.
```sh
% omc test.mos
true
""
true
""
"/Users/jenkins/mahge/OpenModelica/working/issue_10293/Modelica.Blocks.Examples.PID_Controller.fmu"
""
```

```
% OMSimulator Modelica.Blocks.Examples.PID_Controller.fmu
info:    maximum step size for 'model.root': 0.001000
info:    Result file: model_res.mat (bufferSize=10)
info:    Final Statistics for 'model.root':
         NumSteps = 506 NumRhsEvals  = 511 NumLinSolvSetups = 29
         NumNonlinSolvIters = 510 NumNonlinSolvConvFails = 0 NumErrTestFails = 0
```

**Comment by mahge** [comment]
BTW the issue with `--no-undefined` is technically not an apple issue but rather a `clang`  and `AppleClang` one (or the actual linker clang uses). Maybe it is better to check if the compiler is `clang` or `AppleClang` instead of checking if the OS is APPLE? I have never tried compiling FMUs on Linux/Windows using clang, maybe someone else has.

I had to remove the flag from simulation flags due to this issue (#8792). If you need it, the `clang` equivalent of this option is  `-Wl,-undefined,error`

**Comment by mahge** [comment]
CMake has added a [function](https://cmake.org/cmake/help/latest/module/CheckLinkerFlag.html) for checking linker flags. Unfortunately, it is only available in versions 3.18+.  Something to keep in mind if we update the requirements.

**Review by mahge — APPROVED** [review]

**Pull request merged**
