### PR TITLE
Utilize max and initial step size

### PR DESCRIPTION
**Pull request by bernhardbachmann**
### Related Issues

#10258

### Purpose

Utilize the simulation flags `-maxStepSize` and `-initialStepSize` for the single-rate and bi-rate mode.

### CODE REVIEW

**Review by AnHeuermann — APPROVED** [review]

**Comment by bernhardbachmann** [comment]
You never know😏 Please feel free to test the options!

**Comment by casella** [comment]
I tested `-maxStepSize` and it works fine

**Comment by casella** [comment]
I tested -initialStepSize but it doesn't seem to work as expected.

I ran the following MWE:
```modelica
model TestFlags
  Real x;
equation
  der(x) = sin(100*time);
end TestFlags;
```
setting `-noEquidistantTimeGrid` and `-initialStepSize=1e-7`. The initial step size turned out to be 5e-13. I guess there are some factors in-between that are not handled correctly

**Comment by bernhardbachmann** [comment]
The model works fine for me:
```
call solver from 0 to 0.002 (stepSize: 0.002)
  Start gbode (single-rate integration)  from 0 to 1
    Initial step size = 1.000000e-07 at time 0
    Accept step from          0 to      1e-07, error 3.27611e-18 interpolation error 2.60791e-19, new stepsize    3.5e-07
    Accept step from      1e-07 to    4.5e-07, error 4.91689e-16 interpolation error 3.90802e-17, new stepsize  1.225e-06
    Accept step from    4.5e-07 to  1.675e-06, error 7.37847e-14 interpolation error 5.86431e-15, new stepsize 4.2875e-06
    Accept step from  1.675e-06 to 5.9625e-06, error 1.10723e-11 interpolation error 8.80006e-13, new stepsize 1.50063e-05
    Accept step from 5.9625e-06 to 2.09688e-05, error 1.66154e-09 interpolation error 1.32056e-10, new stepsize 5.25219e-05
    Accept step from 2.09687e-05 to 7.34906e-05, error 2.49332e-07 interpolation error 1.98164e-08, new stepsize 0.000183827
```

**Pull request merged**
