### PR TITLE
Check for div-by-zero at compile time

### PR DESCRIPTION
**Pull request by phannebohm**
### Related Issues

#12730

### CODE REVIEW

**Comment by phannebohm** [comment]
Apparently there were already about 20 models with `x / 0.0` which are now failing, see [this report](https://libraries.openmodelica.org/branches/history/master/2024-07-20%2010:04:00..2024-07-22%2011:30:28.html).

**Comment by casella** [comment]
@phannebohm I guess this commit broke some models, see e.g. the ClaRa models in https://libraries.openmodelica.org/branches/history/master/2024-07-20%2010:04:00..2024-07-22%2011:30:28.html

Is #12745 meant to address that?

**Comment by phannebohm** [comment]
Yes, I also saw that and reverted the problematic part.

I looked a little into one of the broken models in Clara. It seems there are expressions similar in spirit to
```modelica
{if (i-1) < 1 then 1 else x/(i-1) for i in 1:N}
```
and of course they don't cause real problems. But we can't detect that very well.

**Comment by casella** [comment]
Why should that be problematic? I mean, this is unrolled by the backend, so there should never be any division by zero.

**Comment by phannebohm** [comment]
The actual condition was not quite as trivial and thus not constant-evaluated. I think it contained parameters and those should have appropriate min/max attributes but didn't, if I remember correctly. So it's both a library and compiler issue.

**Comment by casella** [comment]
Maybe we could ask to add those attributes to the parameter declarations, they won't hurt 😃

**Pull request merged**
