### PR TITLE
fix UTF-8 detection in parser

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by hkiel** [comment]
This build error cannot be caised by the PR!?
`bash: /usr/local/bin/fmuCheck.darwin64: No such file or directory`

**Comment by sjoelund** [comment]
It's probably because we enabled our second Mac to run jobs, but it doesn't have that program installed...

**Comment by hkiel** [comment]
> It's probably because we enabled our second Mac to run jobs, but it doesn't have that program installed...

Can you start the job again, please?

**Comment by hkiel** [comment]
@sjoelund Can you trigger a new run of the PR please?

**Comment by casella** [comment]
There you go

**Pull request merged**
