### PR TITLE
Use the system's Ipopt and qwt, because they don't cleanly compile on (newest?) Qt5.15

### PR DESCRIPTION
**Pull request by ppenguin**
Current `master` doesn't compile on (cutting edge) Manjaro install, due to the following:

- `qwt` doesn't compile on `Qt5.15+`, because of changes to `QtPainter`
- OM 3rd party `Ipopt` doesn't compile because its included dependency `mumps` doesn't compile.

At least on Linux, why wouldn't we require all normally available packages (`mumps`, `ipopt`, `qwt`, `sundials`(?), ...) as an external dependency? It reduces maintenance overhead and apparently works.

This fork compiles and runs cleanly on my Manjaro system (with above packages already installed with the package manager) like so:
```
# after cloning ppenguin/OpenModelica
./upd-submod.sh
./build.sh
make -j18
```
I also needed to modify several submodules, to remove OM's `qwt` from all configs/Makefiles, see repo...

Warning: my mods are quick&dirty fixes only for Linux, so for merging scrutiny is required.

### CODE REVIEW

**Comment by kabdelhak** [comment]
> Current `master` doesn't compile on (cutting edge) Manjaro install, due to the following:
> 
>     * `qwt` doesn't compile on `Qt5.15+`, because of changes to `QtPainter`
> 
>     * OM 3rd party `Ipopt` doesn't compile because its included dependency `mumps` doesn't compile.

Seems bad, we should try to find out why this happens.

> 
> 
> At least on Linux, why wouldn't we require all normally available packages (`mumps`, `ipopt`, `qwt`, `sundials`(?), ...) as an external dependency? It reduces maintenance overhead and apparently works.

Sure but that is hard to ensure to work on all systems and different external libraries/packages and different versions. I am no expert on this we should see what @adrpo, @sjoelund, @AnHeuermann  have to say about this.  Did you test this with Windows?

> 
> This fork compiles and runs cleanly on my Manjaro system (with above packages already installed with the package manager) like so:
> 
> ```
> # after cloning ppenguin/OpenModelica
> ./upd-submod.sh
> ./build.sh
> make -j18
> ```
> 

Our current building system on Jenkins does not work with your routine so it is not able to test this rn.

> I also needed to modify several submodules, to remove OM's `qwt` from all configs/Makefiles, see repo...
> 
> Warning: my mods are quick&dirty fixes only for Linux, so for merging scrutiny is required.

Yea... that could take a lot of time to merge. I am still not quite sure if we really want this to happen, did you present this to someone already? If it is really viable we should have a meeting about this.

But we definitely need to wait for version 1.16, before we cannot think about doing such a major change.

**Comment by ppenguin** [comment]
@kabdelhak 

Thanks for your quick reply!

First of all, I was not really expecting a "quick merge" (aslo seeing the `jenkings` fail), just wanted to bring this issue to the attention, and couldn't find a place to post issues other than pull requests.

I don't have experience with Jenkins,  I'm not surprised that my build doesn't work (it's a bit too specific for that), but I guess the `master` builds work because older `Qt5` versions are used?

Still surprised about the `mumps` issue though, since this appears to happen at least for Archlinux/Manjaro users, and not in Jenkins.

The `qwt` issue is related to a change in `Qt5.15`, for which the fix is similar to [this one](https://github.com/RPCS3/rpcs3/pull/7832). Since I didn't notice any special features in `omqwt` vs `qwt` for me it was the easiest just to take an external `qwt`.

All in all that was the rationale to just remove the internal dependencies where external dependencies could be easily satisfied on my platform.

As a takeway from this, I guess a good middle ground would be to just update OM's `configure` to support a direct choice to use system-libraries where available or wanted, i.e. "translate" this PR to:
- a bug report (doesn't compile on current `Qt` and possibly other dependencies)
- an enhancement request: control the considered dependencies (especially all that are usually available through package managers on linux)  with configure.

That would probably be the most elegant and also the easiest solution, but I'm not versed enough in `autoconf` to effectively do this.

**Comment by kabdelhak** [comment]
@ppenguin 

No problem! As i see you are first contributor, so thanks for your contribution as well!

We currently use [Trac](https://trac.openmodelica.org/OpenModelica/) to handle tickets regarding bugs and enhancements, but we plan on porting that to github in the future. For now it would be great if you could create a ticket on Trac with the short explanation and link to this PR.  

An option for configure sounds way more realistic but we have to think about what it should cover. It sounds like that could be a lot of implementation work for only few benefits.

I will address this in tomorrows developer meeting.

**Comment by ppenguin** [comment]
@kabdelhak 

I will post the report on trac!

As for the "few" benefits, could be, although I think potentially all Linux source distributions (*Arch*, *Manjaro*, *Funtoo*, *Gentoo*, *LFS*, just to name a few) are probably significantly affected by this more-or-less structural issue. Basically exactly the cases that a "CI" such as Jenkins would have a hard time covering. Possibly many OM-pro's or enthusiasts are more generally computing enthusiasts as well, and as such more likely to run said distro's. So that would at least put some more weight on the issue ;)

Thanks and a fruitful dev-meeting!

**Comment by adrpo** [comment]
Just a bit of context here, we have our own versions of packages in the repositories for several reasons:

- to have our own changes to these packages
- to avoid incompatibilities with system libraries
- to fix a certain version of a package because (any of)
   * it has a license we agree with
   * we don't have resources to update our code to the latest version
   * the latest version has issues with our code

I guess @sjoelund might add more items to this list.
From  my side, configuring to use the system libraries, if possible, is a good compromise.

**Comment by sjoelund** [comment]
https://trac.openmodelica.org/OpenModelica/ticket/6024#comment:2 - if there is a newer, working mumps... We should update to use that, I suppose.

I'm surprised this didn't just include a log of the error-message when compling. https://github.com/coin-or-tools/ThirdParty-Mumps seems to suggest a possible work-around:

> NOTE for GFortran 10 users
> MUMPS source does not compile out of the box when using GFortran 10, probably due to some incompatibilities between assumed Fortran language standards, see also issue #4.
> 
> A possible workaround is to call configure with the additional argument ADD_FCFLAGS=-fallow-argument-mismatch.

**Comment by perost** [comment]
> > A possible workaround is to call configure with the additional argument ADD_FCFLAGS=-fallow-argument-mismatch.

Didn't work for me, I assume ADD_FCFLAGS is specific for COIN-OR. What did work was to run `FFLAGS=-fallow-argument-mismatch ./configure` in the mumps folder.

**Comment by hkiel** [comment]
I've also got a problem compiling `OMEditLIB/MainWindow.cpp` with Qt5.15

```
:info:build In file included from MainWindow.cpp:63:
:info:build In file included from ./TransformationalDebugger/TransformationsWidget.h:44:
:info:build ./TransformationalDebugger/OMDumpXML.h:192:27: warning: 'QXmlDefaultHandler' is deprecated [-Wdeprecated-declarations]
:info:build class MyHandler : private QXmlDefaultHandler {
:info:build                           ^
:info:build /opt/local/libexec/qt5/lib/QtXml.framework/Headers/qxml.h:407:7: note: 'QXmlDefaultHandler' has been explicitly marked deprecated here
...
:info:build In file included from MainWindow.cpp:63:
:info:build In file included from ./TransformationalDebugger/TransformationsWidget.h:44:
:info:build ./TransformationalDebugger/OMDumpXML.h:218:25: warning: 'QXmlParseException' is deprecated [-Wdeprecated-declarations]
:info:build   bool fatalError(const QXmlParseException & exception);
:info:build                         ^
:info:build /opt/local/libexec/qt5/lib/QtXml.framework/Headers/qxml.h:226:7: note: 'QXmlParseException' has been explicitly marked deprecated here
...
:info:build MainWindow.cpp:2709:1: error: function definition is not allowed here
:info:build {
:info:build ^
:info:build MainWindow.cpp:2723:1: error: function definition is not allowed here
...
:info:build fatal error: too many errors emitted, stopping now [-ferror-limit=]
:info:build 2 warnings and 20 errors generated.

```

**Pull request closed without merging**
