### PR TITLE
Invent nominal values for derivatives

### PR DESCRIPTION
**Pull request by phannebohm**
The current heuristic is to just copy the nominal value from the
corresponding state. We want to divide that by the simulation
time, but I don't know where to get those values at the moment.

See issue #7794 for the discussion.

### CODE REVIEW

**Review by rfranke — COMMENTED** [review]
This looks like a good place to introduce nominal values for state derivatives. I would remove startTime/stopTime though, because they are hardly related. One might want to have a sensitivity of derivatives with respect to states -- 1 being a reasonable guess.
Meaning that just comment out the line
  //deriv.nominalValue := NONE();
and maybe leaving a comment why might suffice.

**Comment by phannebohm** [comment]
True. At least for the models in ModelicaTest.Fluid this seems to be the right solution as you pointed out in #7794.

But I'm not sure the discussion on what a good heuristic is has come to any satisfying conclusion. As far as I understand, a state and its derivative can have very unrelated orders of magnitude, e.g. a small, high-frequency or large, low-frequency oscillation. In that case simulation time could hint on the relevant time scales. Or do I miss something?

**Comment by casella** [comment]
@phannebohm, as discussed during the devmeeting, my proposal is to use the simulation reporting interval (i.e. the value of Interval in the experiment annotation, or (stopTime-startTime)/numberOfIntervals

**Comment by casella** [comment]
@AndreaBartolini, you can check your models on the nightly once this PR is merged in

**Comment by casella** [comment]
Great! I'm eager to see the impact on the library testsuite.

**Pull request merged**
