### PR TITLE
Add new debug flag combineSubscripts

### PR DESCRIPTION
**Pull request by perost**
- Add new debug flag combineSubscripts that when used together with
  newInst moves all subscripts to the end of component references.

### CODE REVIEW

**Comment by kabdelhak** [comment]
Hmmm another debug flag? Could get messy ... i suppose we should figure out if this can become a default option for the unscalarized new backend.

**Comment by perost** [comment]
> Hmmm another debug flag? Could get messy ... i suppose we should figure out if this can become a default option for the unscalarized new backend.

Sure, but at the moment it needs to be optional.

**Comment by kabdelhak** [comment]
> > Hmmm another debug flag? Could get messy ... i suppose we should figure out if this can become a default option for the unscalarized new backend.
> 
> Sure, but at the moment it needs to be optional.

Can't it be part of `-d=-nfScalarize`? Or does that interfere with stuff that Rüdiger does?

**Comment by perost** [comment]
> > > Hmmm another debug flag? Could get messy ... i suppose we should figure out if this can become a default option for the unscalarized new backend.
> > 
> > 
> > Sure, but at the moment it needs to be optional.
> 
> Can't it be part of `-d=-nfScalarize`? Or does that interfere with stuff that Rüdiger does?

I don't really know what the consequences of this are, so this is all highly experimental at the moment. Having it as a separate flag also allows experimenting with it with scalarization turned on.

**Pull request merged**
