### PR TITLE
it seems on el7 the Qt version is higher

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

**Comment by perost** [comment]
I'm not sure if this will fix anything. The code that's using `QScreen` is still `#ifdef`:ed for Qt 5.11.0, which is the only reason why I added that version check in the first place. `QScreen` was introduced already in Qt 5.0, so any version of Qt 5 should be fine.

Also, this might break the compilation for me, since I only have Qt 5.15.13 (and 6.7.0, but I assume OMEdit is still using Qt 5).

**Comment by adrpo** [comment]
> I'm not sure if this will fix anything. The code that's using `QScreen` is still `#ifdef`:ed for Qt 5.11.0, which is the only reason why I added that version check in the first place. `QScreen` was introduced already in Qt 5.0, so any version of Qt 5 should be fine.
> 
> Also, this might break the compilation for me, since I only have Qt 5.15.13 (and 6.7.0, but I assume OMEdit is still using Qt 5).

Ouch, so what should I do, we have this problem:
https://test.openmodelica.org/jenkins/blue/rest/organizations/jenkins/pipelines/LINUX_BUILDS/runs/2704/nodes/179/steps/633/log/?start=0

**Comment by adrpo** [comment]
I guess I could keep the previous stuff and check if is EL7 somehow?!

**Comment by perost** [comment]
> > I'm not sure if this will fix anything. The code that's using `QScreen` is still `#ifdef`:ed for Qt 5.11.0, which is the only reason why I added that version check in the first place. `QScreen` was introduced already in Qt 5.0, so any version of Qt 5 should be fine.
> > Also, this might break the compilation for me, since I only have Qt 5.15.13 (and 6.7.0, but I assume OMEdit is still using Qt 5).
> 
> Ouch, so what should I do, we have this problem: https://test.openmodelica.org/jenkins/blue/rest/organizations/jenkins/pipelines/LINUX_BUILDS/runs/2704/nodes/179/steps/633/log/?start=0

That should've been fixed by #12536.

**Comment by adrpo** [comment]
geez, ok, I'll revert my stuff, build the source packages and start the Linux builds.

**Comment by adrpo** [comment]
I made #12540 and I will go to sleep :)

**Pull request merged**
