### PR TITLE
Interactive simulation for SSP models

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by adeas31** [comment]
@lochel now there are two simulation buttons in the toolbar, use the second one for interactive simulation. For now I added `pause` and `continue` buttons next to `cancel simulation` button. The simulation server seems to work fine.

**Comment by lochel** [comment]
It crashes for me on Linux/WSL2. I am not sure why though; I have to investigate more.

**Comment by lochel** [comment]
I can avoid the crash by replacing `msg = self._socket_rep.recv_json()` with `msg = str(self._socket_rep.recv())` in OMSimulatorServer.py. However, I still get broken messages. Might be a problem with encoding?

> OMEdit: button continue
> Server:  recv: b'\xc0K'

> OMEdit: button pause
> Server:  b''

**Comment by adeas31** [comment]
I changed to utf-8. Try now.

**Comment by lochel** [comment]
This looks much better. The simulation server receives the correct commands. However, there are a few issues that I have to address in the simulation server.

**Comment by adeas31** [comment]
Good! Time to add the command to fetch signals so I can continue.

**Comment by lochel** [comment]
This requires OpenModelica/OMSimulator#915 which probably will take a few more days. I'll let you know when the signals are available.

**Comment by adeas31** [comment]
@lochel getting the signals data and adding it to the variables browser works fine now. I intend to merge this PR and make a new one for sending request about which signals data is required.

If you want to test then do not pull the last 2 commits.

**Pull request merged**
