### PR TITLE
Fixed the overlapping display issue of connectors

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by adeas31** [comment]
@sjoelund I guess we need to make a new pip version of OMPython OR maybe update the docker image.

**Comment by sjoelund** [comment]
But why should you need to manually clear the results? Shouldn't it be done automatically?

**Comment by adeas31** [comment]
Its not done automatically. From the code it seems like its intentional so I just provided a way to clear it if user wants to.

**Comment by sjoelund** [comment]
From what I can tell, OMPython 3.1.2 still works on my machine... I'm pushing a commit to see what is in those log-files on Jenkins.

**Comment by adeas31** [comment]
It works as long as you don't call `clearOMParserResult`, right?

**Comment by sjoelund** [comment]
> It works as long as you don't call `clearOMParserResult`, right?

Ah yes, I forgot to checkout your branch before running the tests...

**Pull request merged**
