### PR TITLE
Improve handling of binding expression.

### PR DESCRIPTION
**Pull request by perost**
- Subscript binding expressions with special split subscripts when
  propagating them down, instead of just saving a list of parents.
  This removes a lot of special cases for binding expressions and
  simplifies the typing and handling of such expressions.
- Remove all the old BINDING_EXP code with extreme prejudice.

### CODE REVIEW

**Comment by casella** [comment]
Good, only four test failures for each compiler. I hope they are an easy catch.

**Comment by perost** [comment]
> Good, only four test failures for each compiler. I hope they are an easy catch.

The only surprise was that the flat Modelica test broke, but I'm pretty sure I know what the issue is. I'll fix it tomorrow and finally merge this in.

**Comment by casella** [comment]
> The only surprise was that the flat Modelica test broke, but I'm pretty sure I know what the issue is. I'll fix it tomorrow and finally merge this in.

Great! I hoped that this would fix a fairly large number of issues in Buildings, but during the last devmeeting you mentioned something like 8 models, which was a bit disappointing to me. Did I get it right?

**Comment by perost** [comment]
> > The only surprise was that the flat Modelica test broke, but I'm pretty sure I know what the issue is. I'll fix it tomorrow and finally merge this in.
> 
> Great! I hoped that this would fix a fairly large number of issues in Buildings, but during the last devmeeting you mentioned something like 8 models, which was a bit disappointing to me. Did I get it right?

Yes, this is a necessary step to be able to fix many models, but in itself it won't make a huge visible impact.

**Comment by casella** [comment]
> Yes, this is a necessary step to be able to fix many models, but in itself it won't make a huge visible impact.

OK, thanks for the hint. I'll report this to Michael Wetter once it's merged in.

**Comment by perost** [comment]
> > Yes, this is a necessary step to be able to fix many models, but in itself it won't make a huge visible impact.
> 
> OK, thanks for the hint. I'll report this to Michael Wetter once it's merged in.

In terms of tickets this will fix https://trac.openmodelica.org/OpenModelica/ticket/6197, but hopefully it also makes it easier to fix several of the remaining tickets.

**Pull request merged**
