### PR TITLE
Improve handling of record bindings

### LINKED ISSUE #10812: NF fails in models with fixed = false parameters
Please run the attached Save Total model [OneBusOneLoadTotal.zip](https://github.com/OpenModelica/OpenModelica/files/11723843/OneBusOneLoadTotal.zip) with the script
```modelica
loadFile("OneBusOneLoadTotal.mo");getErrorString();
simulate(OneBusOneLoad_total);getErrorString();
```
The NF gives this error message:
```
"[C:/dev/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo:1126:9-1126:67:writable] Error: 
internal error NFCeval.evalBinaryDiv failed to evaluate loadPQ.UStart / 1.732050807568877
```
but then happily treads on and eventually leads to the production of correct simulation code. So, this issue, which affects the development version of PowerGrids, see PowerGrids/PowerGrids#62, is not a blocker, but is nevertheless quite annoying, because the end user sees an error message and has no clue what it implies and what to do with it.

Now, `loadPQ.UStart` is a `final parameter` but also has `fixed = false`, which means it can only be computed by solving the initializazion problem by means of initial equations, which are handled by the backend. The NF has no business trying to constant-evaluate it

### Expected Behavior

The NF should not try to constant-evaluate `loadPQ.UStart`, and leave it to the backend and runtime.

In fact, unless I am missing something, the NF should never try to constant-evaluate parameters with `fixed = false` attribute.

### PR DESCRIPTION
**Pull request by perost**
- Don't evaluate non-structural parameters.
- Use `tryEvalExp` instead of `evalExp` when trying to evaluate record bindings, to hide any eventual error messages since failure is ok.
- Improve the function inlining by merging the inlining of record constructors with the inlining of normal function calls, and allowing forced inlining regardless of annotation.

Fixes #10812

### CODE REVIEW

**Comment by mahge** [comment]
This has not yet gone through the master regression tests (there is a bit of [queue](https://test.openmodelica.org/jenkins/blue/organizations/jenkins/LibraryTesting%2FLibraryTest/activity/) unfortunately), but I think it broke some Buildings models. 

You can check the `Buildings.Examples.Tutorial.Boiler.System1` model for example. There quite a few more Buildings models that fail the same way. 

The issue is around this algorithm
```c
vol.state_start := if size({vol.X_start[1:vol.Medium.nXi]}, 1) == 2 then
 Buildings.Examples.Tutorial.Boiler.System1.vol.Medium.ThermodynamicState(vol.p_start, vol.T_start, {vol.X_start[1]}) else
 Buildings.Examples.Tutorial.Boiler.System1.vol.Medium.ThermodynamicState(vol.p_start, vol.T_start, {vol.X_start[1], 1.0 - vol.X_start[1]});
```

Specifically, the problem is the `{vol.X_start[1:vol.Medium.nXi]}` expression which is a matrix. 

The following model, which is as close as possible I can make it to the issue without `omc` optimizing away things, compiles fine

```mo
model Test
  Real a[2] = {time + 1, time + 2};
  Real b[1,2];
  Integer i;
algorithm
  i := if time < 1 then 2 else 3;
  b := {a[i-1:i]};
end Test;
```

Is there anything that you can see that might suggest that the expression `{vol.X_start[1:vol.Medium.nXi]}` is not getting the correct type? 

I thought we were also replacing all slices on the RHS with `for-iterator-array` expressions. Maybe we are not traversing expressions inside an array ({...}) expression?

**Comment by perost** [comment]
@mahge: I disabled the part that seems to be causing the issue in #10842. It seems inlining normal functions is causing some issue in this case, it creates the if-expression you mentioned which it then fails to evaluate and moves it to an initial equation because it can't split it.

I don't know what's going wrong, maybe the inlining is incorrect somehow. But that part isn't actually necessary for fixing the issue so I disabled it for now until I have time to take a better look at it.

**Comment by mahge** [comment]
Thanks. Hopefully, this makes it to tonight's nightly build and regression test so we can see the effect tomorrow. 

The PR build for #10842 was failing due to the `wget` failure. I have restarted it manually. I will keep an eye on it.

**Comment by perost** [comment]
#10844 should fix the issues that occured due to the inlining. The issue was that `size({vol.X_start[1:vol.Medium.nXi]}, 1)` was constant evaluated to `vol.nX`, because the evaluation of `size` didn't actually evaluate the dimension size. With that fixed it now properly evaluates everything and there's no equation being created.

**Pull request merged**
