### PR TITLE
Free synchronus data again

### PR DESCRIPTION
**Pull request by AnHeuermann**
This should fix two memory leaks around clocks and interval timers.

### CODE REVIEW

**Comment by AnHeuermann** [comment]
@lochel Do you know why it is possible for the DualMassOscillator test with OMSimulator that the initalization is called twice in a row (after fmi2GetReal)?
See error message from test in https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-7141/4/tests

I changed my code a bit to not check if synchronus data was already allocated, but simply always free before allocating. Not pretty but at least it fixes a few memory leaks.

**Comment by lochel** [comment]
@AnHeuermann What the heck? 😮

**Comment by AnHeuermann** [comment]
`initialization()` in [initialization.c#L654-L663](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/solver/initialization/initialization.c#L654-L663) get's called two times for each system. First during `fmi2GetReal` and then during `fmi2ExitInitializationMode`. I guess this is correct behavior and I should move everything that allocates memory to be called during `fmi2Instantiate`.

**Review by lochel — APPROVED** [review]
LGTM

**Pull request merged**
