### PR TITLE
small speedup of API updateConnection #5620

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

**Comment by perost** [comment]
Does the code need to handle duplicate connections? Otherwise you could also just return once a matching connection is found.

**Comment by adrpo** [comment]
> Does the code need to handle duplicate connections? Otherwise you could also just return once a matching connection is found.
You cannot return as you need to make the list again. You don't have the rest of the list to append in the for loop.

**Comment by perost** [comment]
> > Does the code need to handle duplicate connections? Otherwise you could also just return once a matching connection is found.
> 
> You cannot return as you need to make the list again. You don't have the rest of the list to append in the for loop.

True, should probably just use List.findMap then.

**Comment by adrpo** [comment]
Yes, that would be better I think. Especially if you have a huge number of equations.

**Pull request merged**
