### PR TITLE
Parse the enumerations like LinePattern and FillPattern

### PR DESCRIPTION
**Pull request by adeas31**
Added new annotation classes for enumerations
Added the license text to some files

### CODE REVIEW

**Comment by adeas31** [comment]
@perost I am not sure what to do in `Enum::eval`.

**Comment by perost** [comment]
> @perost I am not sure what to do in `Enum::eval`.

Just returning the same expression like you do should be fine, an enumeration literal is already an evaluated value.

**Review by perost — APPROVED** [review]

**Comment by adeas31** [comment]
> > @perost I am not sure what to do in `Enum::eval`.
> 
> Just returning the same expression like you do should be fine, an enumeration literal is already an evaluated value.

Maybe then there is no point calling `evaluate` on them.
If I understand correctly this also means that they don't have any variable binding or DynamicSelect.

**Comment by perost** [comment]
> > > @perost I am not sure what to do in `Enum::eval`.
> > 
> > 
> > Just returning the same expression like you do should be fine, an enumeration literal is already an evaluated value.
> 
> Maybe then there is no point calling `evaluate` on them. If I understand correctly this also means that they don't have any variable binding or DynamicSelect.

They might be part of some bigger expression, so it's much easier if every expression can be evaluated even if they just evaluate to themselves so we don't have to check everywhere if an expression is already a literal or not.

But yes, enumeration literals have both a name and integer value, but the value is static unlike variables.

**Pull request merged**
