### PR TITLE
Remove unnecessary version checks for QScreen

### PR DESCRIPTION
**Pull request by adeas31**
OMEdit requires Qt 5 for compilation and QScreen is available since Qt 5.0.

### CODE REVIEW

**Comment by adeas31** [comment]
@perost and @anotheruserofgithub can you please check if this compiles for you guys?
@adrpo please check if this work on el7.

**Comment by perost** [comment]
Works fine for me, but that's of course expected since I have a newer version of Qt than 5.11 so it doesn't really change anything.

**Comment by perost** [comment]
> @adeas31 In `ElementProperties.cpp` there are still two `ifdef`-ed calls to `QApplication::desktop()`, which don't work if you remove `#include <QDesktopWidget>` L49 in that file.
> 
> If instead I try to remove them and keep only the `#if (QT_VERSION >= QT_VERSION_CHECK(5, 11, 0))` branch, I get the error that `QFontMetrics.horizontalAdvance()` does not exist:
> 
> ```
> Element/ElementProperties.cpp: In member function ‘void Parameter::setValueWidget(QString, bool, QString, bool, bool, bool)’:
> Element/ElementProperties.cpp:491:55: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
>   491 |         mpValueComboBox->setMinimumWidth(qMin(qMax(fm.horizontalAdvance(value), mpValueComboBox->minimumSizeHint().width()), screenWidth) + 50);
>       |                                                       ^~~~~~~~~~~~~~~~~
> Element/ElementProperties.cpp:514:49: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
>   514 |         mpValueTextBox->setMinimumWidth(qMin(fm.horizontalAdvance(value), screenWidth) + 50);
>       |                                                 ^~~~~~~~~~~~~~~~~
> Makefile:7781: recipe for target 'ElementProperties.o' failed
> ```
> 
> I have Qt version 5.9.5 on Ubuntu 18.04.

`QFontMetrics::horizontalAdvance` was added in Qt 5.11, so at least that version check is necessary.

**Comment by adeas31** [comment]
Please try again. Should work now.

**Comment by adeas31** [comment]
> Yes, I can confirm compilation works for me. ;) Thanks!

Good!
> 
> Though if I double-click on a component, it seems to take _by default_ ~70%~ [EDIT: It's surely more than 70%... but I'm not sure if I'm testing the right widget] of the screen size, is that expected? I'm able to increase the width to 100%, but not to reduce it. image

The 70% width is allowed for the textedit/dropdown and not the whole window. There are other controls that add to the width. There is another ticket about how to handle this in a better way #10395.

**Pull request merged**
