### PR TITLE
Enum connectors

### PR DESCRIPTION
**Pull request by lochel**
@adeas31 The enum connectors do not yet have an icon in the libraries browser. I don't know how to do that.

### CODE REVIEW

**Comment by adeas31** [comment]
So you want to handle the enum same as integer, right?

**Comment by lochel** [comment]
Not really, but sort of. They are compatible but not the same. Do you have a good idea how to handle enums? If we don't know better, then we can treat them similar to integers.

**Comment by adeas31** [comment]
For now I updated to handle enum same as integers. We will see if this leads to any problem.

**Comment by adrpo** [comment]
If you have `EnumType arr[EnumType]` you will get an error if you use an integer to index it, you need to index it with `EnumType(integerIndex)`. 
If you have `EnumType arr[someIntegerSize]` and try to index it with the EnumType you will gen an error, you need to index it with `Integer(EnumType)`

**Comment by lochel** [comment]
This will just affect SSP connection...

**Comment by adrpo** [comment]
> This will just affect SSP connection...

Geez, nevermind then, just ignore my comment :)

**Pull request merged**
