### PR TITLE
Changed Upgrade installed libraries to Update installed libraries

### PR DESCRIPTION
**Pull request by adeas31**
### Purpose

Explain users about update installed libraries.

### Approach

Added a dialog to File | Update installed libraries explaining what it does.

### CODE REVIEW

**Comment by adeas31** [comment]
@casella this is how it looks like,

image

**Comment by casella** [comment]
@adeas31, I still see a problem, that it is not immediately clear what this update/upgrade (the word upgrade is still in the explanatory text) actually does. 

What I understand is that it actually only updates the index for already installed libraries, and it also downloads and installs newer available versions if the checkbox is ticked. If that is the case, then we may write something like this:

> Clicking on Update updates the information about available released versions for all libraries installed with the package manager. Tick the checkbox if you also want to download and install the newest available versions.
>
> Newer versions of libraries that are backwards compatible with already installed ones will be loaded automatically when opening a package or model that uses them. 
> 
> Upgrading your libraries or models to use newer non-backwards compatible library version requires to convert them explicitly, please use the context menu in the library browser to perform that operation.

It's a bit long, but I hope it makes everything clear. What do you think?

**Comment by adeas31** [comment]
I will take an approval from @sjoelund as he knows better what this update actually does.

One thing I noticed is that the update downloads even the libraries that have experimental support level. For example, I had Power Grids 1.0.1 installed and if I do update then 1.0.2 is downloaded.

**Comment by sjoelund** [comment]
I used the same terminology as for `apt`. Update downloads a new package index and upgrade installs new packages.

I suppose we would need a flag to only upgrade if the support level is the same or better for the newer package though.

**Comment by adeas31** [comment]
> I used the same terminology as for apt. Update downloads a new package index and upgrade installs new packages.

That's fine. We do the update magic without telling the user. And rephrased updrage to update. The question is do you agree with the text that Francesco posted above?

> I suppose we would need a flag to only upgrade if the support level is the same or better for the newer package though.

For sure. Do not install experimental version when user is using a stable/release one.

**Comment by sjoelund** [comment]
Ah, the API newer updates the index.json. I think what the newest does is install the newest version even if not backwards compatible. I can't tell without checking the code, and don't have time for that.

**Comment by casella** [comment]
> I used the same terminology as for `apt`. Update downloads a new package index and upgrade installs new packages.

That's also what I had in mind, better stick to that to avoid confusion.

**Comment by adeas31** [comment]
@casella I am consfused now. What should we use? `Update` or `Upgrade`?

**Comment by casella** [comment]
If the checkbox is unchecked, we only do update i.e. update the index, we are not actually installing anything, so I'm fine at keeping "Update" as the menu item and title of the dialog window. Installing would be "upgrade", but I think that "install" in the checkbox text is clearer. 

Is that ok?

**Comment by adeas31** [comment]
I am still confused.

- There is an API [updatePackageIndex()](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.updatePackageIndex.html), that updates the index.
- And then we have [upgradeInstalledPackages()](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.upgradeInstalledPackages.html), that upgrades the installed packages.
  - What does `installNewestVersions` the argument to `upgradeInstalledPackages()` does? Btw `installNewestVersions` is `true` by default.

OMEdit calls `updatePackageIndex()` when a new packages is installed or whenever needed without letting the user know. Basically on each operation of package manager `updatePackageIndex()` is called to keep the index up to date.

`upgradeInstalledPackages()` on the other hand is more explicit operation so user has to perform it knowingly. There is a menu item for it that we changed from `Upgrade Installed Libraries` to `Update Installed Libraries`.

**Comment by casella** [comment]
> I am still confused.

I was, too. Sorry about that. Please see @8757

**Pull request merged**
