### PR TITLE
Reactivate wrapFunctionCalls for initial system

### PR DESCRIPTION
**Pull request by kabdelhak**
- apply wrap function call module on initial system
 - analyze initial lambda 0 system (homotopy) to create model info

### CODE REVIEW

**Comment by casella** [comment]
Seems something goes wrong with the fmu checker. Any idea why this happens?

**Comment by adrpo** [comment]
First there are 3k tests failing (so about 1.5k as we run both gcc and clang). 
https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-710/2/tests
Then the fmu checking fails because the tested FMU gets a division by zero.

**Comment by kabdelhak** [comment]
> First there are 3k tests failing (so about 1.5k as we run both gcc and clang).
> https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-710/2/tests
> Then the fmu checking fails because the tested FMU gets a division by zero.

Many cases are just due to different dump outputs, but there are also a lot of things wrong unfortunately. Many things fail because the initial system seems to be unable to handle `$cse` variables. 

We definitely want to activate that module for initialization, but that might take a while to find all the bugs.

**Comment by casella** [comment]
Thank you @kabdelhak for pushing so hard, welcome to the nigh owl club!

@adrpo, I have some trouble understanding the outcome of these Jenkins tests. The [BlueOcean log](https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-710/5/pipeline) only has yellow markers that refer to some `result.xml` file, where the text only says `Recording test result`.

What is still missing to merge this PR?

Thanks!

**Comment by adrpo** [comment]
The build is unstable.
https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-710/5/tests
There are 276 new tests failing, 351 existing failing and 424 skipped.

**Comment by casella** [comment]
I hadn't understood that I had to click on the Tests tab to see that info 😃

**Comment by kabdelhak** [comment]
> I hadn't understood that I had to click on the Tests tab to see that info smiley
> 
> I guess this will have to wait until after the Workhshop

Probably yes. There are multiple different cases going wrong, it looks like i need to find and update some SimCode modules which collect information for code generation. 

It seems like the possibility of variables that occur only in the initial and not in the regular system (which happens applying CSE on initial equations) was not considered implementing that.

**Comment by casella** [comment]
@kabdelhak do I understand correctly that this PR on the old backend is dead, but you are doing this in the new backend?

**Pull request closed without merging**
