### PR TITLE
Add division by zero check for function code.

### PR DESCRIPTION
**Pull request by mahge**

### CODE REVIEW

**Review by adrpo — APPROVED** [review]
LGTM!

**Comment by casella** [comment]
@mahge, this commit broke almost all the HelmholtzMedia testsuite almost completely, see [report](https://libraries.openmodelica.org/branches/history/newInst/2020-12-04%2020:34:15..2020-12-06%2013:08:04.html). 

The cause of failures is always the same
```
assert            | debug   | Division by zero T_crit / T
```
I just ran `HelmholtzMedia.Examples.Validation.idealGasLimit`, which also fails like that, and flattened it. There are several places in various functions where `T_crit / T` is computed, but I don't know which one is called with zero `T`, so it is difficult to figure out what the problem is.

Could we have a bit more information from that assert message, e.g. a stack trace?

**Comment by mahge** [comment]
It is actually this record variable.
https://github.com/thorade/HelmholtzMedia/blob/485491e5d0bf9aea8c68ee31aeeb6e979e0003c4/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/EoS/HelmholtzDerivs.mo#L13

When an instance of HelmholtzDerivs record is declared we "default construct" it. This "default construction" initializes the members of the record to their default values. In this case it tries to compute `tau = T_crit/T`, but `T` is unitialized.

The model might have been giving correct results anyway because, as far as I can tell, declared instances of the record are always "custom initialized" properly by calling the function `EoS.setHelmholtzDerivsFirst` 

https://github.com/thorade/HelmholtzMedia/blob/master/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/EoS/setHelmholtzDerivsFirst.mo

which puts the correct values. 

You can see an example of the usage pattern here: 

**Declaration** https://github.com/thorade/HelmholtzMedia/blob/485491e5d0bf9aea8c68ee31aeeb6e979e0003c4/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/package.mo#L710

**And the custom initialization** 
https://github.com/thorade/HelmholtzMedia/blob/485491e5d0bf9aea8c68ee31aeeb6e979e0003c4/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/package.mo#L774

**Comment by casella** [comment]
I see, thorny issue.

The question is, what is the semantics of those binding equations in a record definition? Are they to be enforced all the time?

@thorade, are those bindings really necessary, or could they be removed from the record definition?

**Comment by mahge** [comment]
> 
> 
> 
> The question is, what is the semantics of those binding equations in a record definition? Are they to be enforced all the time?
> 

To me it seems like it is similar to usage of variable without being assigned to in functions. It is not illegal but we should check and report it if we can. 

We need to do those "default constructions". In this case a user of the library can just declare an instance `r` of `HelmholtzDerivs`  and use `r.T_crit` without any problems. But using `r.T` or `r.tau` will give you undefined values. 

From the coverage report we can see that no other models have these problems. So it might be a good idea to fix HelmHoltzMdeia even though it can be ignored in this case.

The root issue is that Modelica made record construction and usage a little too flexible.

> @thorade, are those bindings really necessary, or could they be removed from the record definition?

I think they can be removed. There is a dedicated function `EoS.setHelmholtzDerivsFirst` that acts as a constructor to the record. It takes the needed values as input, computes and sets the rest of the record members and returns a record.

**Comment by phannebohm** [comment]
> This "default construction" initializes the members of the record to their default values. In this case it tries to compute `tau = T_crit/T`, but `T` is unitialized.

One way to avoid the division could be to check that the variables involved in the binding are uninitialized - perhaps by only looking at the denominator - and thus conclude that `tau` must also be uninitialized.
Probably for some reason this is a stupid idea, but I'm not sure why exactly.

**Comment by mahge** [comment]
You are right I think. But maybe not just for division by zero. We just got lucky in this case and caught division by zero (we also got lucky that variable was initialized to zero by default.). If it was multiplication it would have gone unnoticed. 

We do checks of variables usage before initialization in functions (in the OF. I guess it will come soon for the NF as well). We should do the same checks for records. Of course it is near impossible to do perfect checks. A function with a record variable in it probably just considers it as a whole 1 variable right now, I am not sure.

This is to be done in the FrontEnd. Once we have the checks in the front end there is no need to check in the generated code.

**Comment by adrpo** [comment]
I tried HelmholtzMedia.Examples.BaseProps_sweep with Dymola 2021 (had to unload MSL 4.0.0 and load the 3.2.3) but this model works fine without any issue.

**Comment by thorade** [comment]
I think I added that line tau=Tcrit/T to remove some other error message that I did not understand. 
Probably it can be removed, as the setHelmholtzDerivsFirst / Second / Third has be used anyways.
There may be other places where variables are not initialized, but I do not know how to find them all.

**Comment by perost** [comment]
The specification says (12.4.4): "If no binding equation is given for a non-input component the variable is uninitialized (except for record components where modifiers may also initialize that component). It is an error to use (or return) an uninitialized variable in a function."

So the record instance shouldn't be default initialized in this case, which seems to be what's causing the issue. The record instance `f` in this case is always assigned before being used in the function, so there's really nothing wrong with the model that I can see.

**Comment by mahge** [comment]
The model is not illegal. It is fine. It was just a clarity issue. Of course someone can divide by zero intentionaly in a function. That is still valid Modelica. 

The question is should we check and report such cases in general. Like we do, e.g, `sqrt(-1)` or `log(-1)`  at runtime. Because usually it is not what you intended to do. 

In this case the division by zero check happened to catch a record member that was overwritten later. But still got computed because we need to default construct the record. It is not possible to figure out if the record will be overwritten later at code generation time.

**Comment by perost** [comment]
Why do we need to default construct the record? If we do that we're not following the specification.

**Comment by mahge** [comment]
Records 🤦‍♂️. Let's see if I had this all wrong

What is the expected behavior for this model
```mo

record R
  Real a = 2;
end R;

function Func
  output Real a;
protected
  R hdr;
algorithm
  a := hdr.a;
end Func;
```

**Comment by perost** [comment]
> Records man_facepalming. Let's see if I had this all wrong
> 
> What is the expected behavior for this model. What should be the value of `a`?

Hmm, I think I might be wrong. I guess we should actually use the binding on the record components, which is equivalent to calling the record constructor I guess.

The specification uses the term "record component" everywhere, so it's not clear whether it means the record instance itself or the components in the record instance. In this case they probably mean a bit of both, so each component in the record instance should probably be initialized with its binding if it has one.

**Comment by mahge** [comment]
I think I should also clarify the difference between what I mean when I say "default construction" as opposed to "Modelica record constructor functions"

The Modelica constructors are to be used when you write 
```mo
x := R(...)
```
This constructor is formed according the Modelica rules, e.g. protected variables can not be arguments to the constructor, We can think of this as "explicit construction"

When I mean "default construction" I am talking about the case in the above example.

```mo
R r;
```

**Comment by adrpo** [comment]
```
package HelmholtzMedia.HelmholtzFluids.Butane "Butane"
  extends Interfaces.PartialHelmholtzMedium(
    ... 
    Temperature(
      min=fluidLimitsButane.TMIN,
      max=fluidLimitsButane.TMAX,
      start=298.15), // <---- Dymola initializes Temperature T in the record with the start value from the class modifier.
```
The question: is this correct?

**Comment by sjoelund** [comment]
The specification is a little unclear if it has a binding or not. The interesting question is if the following is a legal model:
```
record R
  Real a, b = a;
end R;

function Func
  output Real a;
protected
  R hdr; // Either components have binding equations and we need to check if they are acyclical... Or only the full record is considered and we cannot use R until R := something... But that would prevent hdr.a := xxx;
algorithm
  a := 2.0;
end Func;
```

**Comment by adrpo** [comment]
Both omc and dym just take the output of the function. We flatten this to:

```
class TestFunctionRecordBinding
  Real b;
equation
  b = 2.0;
end TestFunctionRecordBinding;
```

**Comment by sjoelund** [comment]
Of course, but was it a legal function?

**Comment by perost** [comment]
> ```
> package HelmholtzMedia.HelmholtzFluids.Butane "Butane"
>   extends Interfaces.PartialHelmholtzMedium(
>     ... 
>     Temperature(
>       min=fluidLimitsButane.TMIN,
>       max=fluidLimitsButane.TMAX,
>       start=298.15), // <---- Dymola initializes Temperature T in the record with the start value from the class modifier.
> ```
> 
> The question: is this correct?

12.4.4 says: "When a function is called components of a function do not have start-attributes". So I guess it's not correct.

**Comment by casella** [comment]
@thorade, it looks like the interpretation of the meaning of those record bindings is not so clear. I opened [#2757](https://github.com/modelica/ModelicaSpecification/issues/2757) on the Modelica Specification issue tracker, let's see what happens there.
 
> I think I added that line tau=Tcrit/T to remove some other error message that I did not understand.
> Probably it can be removed, as the setHelmholtzDerivsFirst / Second / Third has be used anyways.

Would you mind trying that out again and seeing what happens?

> There may be other places where variables are not initialized, but I do not know how to find them all.

As I understand, [Section 12.4.4](https://specification.modelica.org/maint/3.4/Ch12.html#initialization-and-declaration-assignments-of-components-in-functions) of the specification says that using uninitialized variables in a function should give an error. So, it should be easy to spot them, if the tool(s) you use to check them behave.

**Comment by thorade** [comment]
I tried some things, and committed a broken state to master, need to clean that up soon or revert.
Some functions like setState_pT do not use setHelmholtzDerivsFirst, but only set certain values, so just removing the equation in the record did not work.

**Comment by casella** [comment]
What about writing `Tcrit / max(T, eps)` in the record binding equation? It looks like a quite ugly hack, and it leaves all the general questions unanswered, but I guess it would at least get the library back up and running.

**Comment by mahge** [comment]
The safest workaround to get the library working for now might be to initialize `T `to `298.15`. We know it works because Dymola has been using that. 

Technically speaking, you can actually set `T` to any non-zero value and prevent OpenModelica from issuing an error. The initial value does not matter since you always explicitly update it before reading from it for the first time.  

If this does not work we can of course remove the check for now until the underlying issue is clarified properly.

**Comment by casella** [comment]
> The safest workaround to get the library working for now might be to initialize `T `to `298.15`. We know it works because Dymola has been using that.

You mean using the default start value, right? Sounds good.
 
> Technically speaking, you can actually set `T` to any non-zero value and prevent OpenModelica from issuing an error. The initial value does not matter since you always explicitly update it before reading from it for the first time.

I guess the start value would do. It is already set to room temperature precisely to avoid these issues in equation-based models. We can also slightly abuse it for records in functions, while the issue is resolved in a clean way (assuming it ever will).

@mahge can you take care of that?

Thanks!

**Comment by sjoelund** [comment]
Or do what MapleSim would do and reject the model: https://github.com/modelica/ModelicaSpecification/issues/2757

I mean, it can easily be fixed in the model itself by adding some non-zero binding for `T`

**Comment by mahge** [comment]
> You mean using the default start value, right? Sounds good.

Yes. Dymola takes it from the start value as Adrian mentioned above. 

My suggested was to update the library itself and set it in the record declaration as a fallback value.. 
If we need to pick the value automatically from the start value then it needs to be done in the FrontEnd. Maybe @perost can do this a lot quicker than I can.

**Comment by casella** [comment]
> I mean, it can easily be fixed in the model itself by adding some non-zero binding for `T`

That's why I proposed having `tau = Tcrit / max(T, eps)` in the record declaration. It's a simple library modification, it keeps the wanted behaviour for cases that do not set `tau `explicitly, as requested by @thorade, it avoids the division by zero that is currently breaking the models in OMC, and is expected to work in all tools without issues. @thorade, do you see any obvious drawbacks in this solution?

> My suggested was to update the library itself and set it in the record declaration as a fallback value..

The fact is, there are some cases where the current binding is really needed. We just need to guard against division by zero.

**Comment by thorade** [comment]
I am fine with removing all equations from the record and updating all functions to initialize the values, I can do it this weekend.

**Comment by casella** [comment]
> I am fine with removing all equations from the record and updating all functions to initialize the values, I can do it this weekend.

That would solve all issues by definition, if it's not too much work for you.

**Comment by thorade** [comment]
@casella It should be in a better state now, in the end this was the easier solution.
I only tested with OMC release before this fix, but once the library is updated on OM test server I will look at the results.

**Comment by casella** [comment]
Here they are:
- [regression report](https://libraries.openmodelica.org/branches/history/newInst/2020-12-11%2011:34:05..2020-12-11%2020:34:33.html)
- [new status](https://libraries.openmodelica.org/branches/newInst/HelmholtzMedia/HelmholtzMedia.html)

The situation is indeed much improved, but there are some models that now fail because of too many equations, e.g. [HelmholtzMedia.Examples.Validation.MaxwellLoop](https://libraries.openmodelica.org/branches/newInst/HelmholtzMedia/files/HelmholtzMedia_HelmholtzMedia.Examples.Validation.MaxwellLoop.err)

**Comment by thorade** [comment]
OK, I did some updates already yesterday that are not included in Jenkins, the error "Modelica.Blocks.Sources.R_samp not found" is fixed. I will wait one more round of Jenkins testing. All test models run in Dymola.

**Pull request merged**
