### PR TITLE
[BE] Index reduction update

### PR DESCRIPTION
**Pull request by kabdelhak**
- consider non states as stateSelect never and make them artificial states

### CODE REVIEW

**Comment by casella** [comment]
Thanks @kabdelhak !

**Comment by kabdelhak** [comment]
> Thanks @kabdelhak !

No problem! 

Unfortunately i forgot to add one more thing. I have to rerun it, but then it should be fine!

**Comment by casella** [comment]
> 
> 
> > Thanks @kabdelhak !
> 
> No problem!
> 
> Unfortunately i forgot to add one more thing. I have to rerun it, but then it should be fine!

No problem 😃

**Comment by casella** [comment]
Ready to launch!

**Comment by kabdelhak** [comment]
> Ready to launch!

Unfortunately we have to wait for someone with push privileges. I requested it in our slack group, i guess it will be pushed as soon as someone is able to.

**Comment by adrpo** [comment]
Merged and newInst coverage job started.

**Pull request merged**
