### PR TITLE
Allow resimulation on failure

### PR DESCRIPTION
**Pull request by JKRT**
-> https://trac.openmodelica.org/OpenModelica/ticket/5472

Tested with:

```
model TestInitialFailure
  Real x(start = 1);
equation
  der(x) = -x + 1;
initial equation
  x^2 + 1 = 0;
end TestInitialFailure;`
```
&
```
model test
  Real X = time;
  parameter Real B = 0;
equation
  when time > 20 then
    assert(B > 0, "test");
  end when;
end test;
```

### CODE REVIEW

**Comment by JKRT** [comment]
@casella @adeas31 Have a look:)

**Comment by casella** [comment]
@adeas31, I understand what you mean, but it would look weird to me that I need to use a different button in the case of initialization failure.

My mental model is that the green button in the Modelling windows does compile and simulate. The red buttons in the Plotting windows allow to re-simulate the latest successfully compiled model without recompiling it again, only by changing some model parameter values (this requires some result file to be present), or by changing the simulation setup, e.g. by turning on some solver logging. From a usability perspective, I don't really see why we should duplicate the re-simulate buttons in the simulation output window as well. 

If the simulation failed at initialization, so be it, you won't be able to load any simulation results. That does not prevent to mark the latest successfully simulated model as Active and enabling the re-simulation buttons on it. If there are no results available, just don't show them 😃

**Comment by JKRT** [comment]
> successfully

Can t

> 
> 
> @adeas31, I understand what you mean, but it would look weird to me that I need to use a different button in the case of initialization failure.
> 
> My mental model is that the green button in the Modelling windows does compile and simulate. The red buttons in the Plotting windows allow to re-simulate the latest successfully compiled model without recompiling it again, only by changing some model parameter values (this requires some result file to be present), or by changing the simulation setup, e.g. by turning on some solver logging. From a usability perspective, I don't really see why we should duplicate the re-simulate buttons in the simulation output window as well.
> 
> If the simulation failed at initialization, so be it, you won't be able to load any simulation results. That does not prevent to mark the latest successfully simulated model as Active and enabling the re-simulation buttons on it. If there are no results available, just don't show them 😃

Ok, so how should I proceed?  
I wrote some code a couple of hours ago that adds a such a resimulation button in the output view I am open for suggestions (I just wanted to solve this loose end since it was tagged in 1,16, and do not really have any preference:) )

**Comment by casella** [comment]
My suggestion is that as soon as a model is successfully compiled, the plotting window should show a node marked as active. If there are no results to load, there will be no result tree below that node.

Then, whenever the re-simulate and re-simulate setup buttons are pressed, the active model is re-simulated.

As soon as there are valid results to load, the variable tree is created or updated below that node.

**Comment by JKRT** [comment]
> 
> 
> My suggestion is that as soon as a model is successfully compiled, the plotting window should show a node marked as active. If there are no results to load, there will be no result tree below that node.
> 
> Then, whenever the re-simulate and re-simulate setup buttons are pressed, the active model is re-simulated.
> 
> As soon as there are valid results to load, the variable tree is created or updated below that node.

Ok so the node should be marked as active on sucessfull compilation, gotcha and there should be a manual change to the plotting view to adjust it? Or shall it be decided via the users settings? 

> 
> As I wrote in the conversation, I don't think this is really useful, I'd prefer to have those buttons in one place (the plotting window), only with an extended meaning.
> 
> BTW, re-simulating the executable without changing model parameters or simulation flags/parameters will obviously lead to the same failure, so that would be hardly useful.

This is very true. Started with some skeleton stuff. I guess removing the button again and some trickery with the conditions might do the trick. 

Awaiting Adeels suggestion, maybe if possible to provide screenshot/mock on how you think  
it should look and I will follow

**Comment by casella** [comment]
I guess switching to the plotting view automatically is governed by some user settings. @adeas31 knows about that.

**Comment by adeas31** [comment]
After the successful compilation of the model OMEdit runs the simulation executable and once the simulation executable is finished then OMEdit checks for the following things before adding a node in the `Variables Browser`,

* resultFileExists - We have a result file.
* resultFileKnown - Result file is either `mat, plt or csv`.
* resultFileNewer - Sometimes we have old result file in the same folder so we check if the result file is new or not.
* resultFileNonZeroSize - This is the output of [readSimulationResultSize](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.readSimulationResultSize.html).

`resultFileNonZeroSize` check is added as part of [ticket#4935](https://trac.openmodelica.org/OpenModelica/ticket/4935).

> My suggestion is that as soon as a model is successfully compiled, the plotting window should show a node marked as active. If there are no results to load, there will be no result tree below that node.

This is possible but perhaps requires a lot more changes. A proper fix would be to use `model_init.xml` to add variables to the `Variables Browser` instead of reading it from [readSimulationResultVars](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.readSimulationResultVars.html). By doing this we can also fix [ticket#5177](https://trac.openmodelica.org/OpenModelica/ticket/5177). But as I said in order to implement this we need quite some changes and is not a good idea to target this for 1.16.

**Comment by casella** [comment]
Sounds good to me

**Comment by JKRT** [comment]
Closing this for now

**Pull request closed without merging**
