### PR TITLE
Set appropriate method-specific defaults for gbode solver

### PR DESCRIPTION
**Pull request by bernhardbachmann**
### Purpose

Configure default settings of GBODE:
Chosen interpolation scheme is dense output, if available. Otherwise hermite.
-gbfint, -gbfctrl, -gbfnls, if not specified, gets the same values as -gbint, -gbctrl, -gbnls

### CODE REVIEW

**Review by casella — COMMENTED** [review]
_Bogus comment, sorry_

**Comment by casella** [comment]
See comments in #10333.

**Review by casella — APPROVED** [review]
LGTM

**Review by AnHeuermann — APPROVED** [review]
I made some improvement to the `-gbferr` and `-gberr` flag handling. Now the user can provide the values as strings (`default`, `richardson`, `embedded`) and the C code uses enumerations to tell them apart.

@bernhardbachmann Have a look at my changes and if you approve we can merge this PR.

**Comment by bernhardbachmann** [comment]
LGTM  :-)

**Comment by casella** [comment]
Thanks, folks!

**Comment by casella** [comment]
This PR addresses #10333.

**Pull request merged**
