### PR TITLE
Added saveTotalFile documentation to NF

### PR DESCRIPTION
**Pull request by casella**
See ticket:5448

### CODE REVIEW

**Comment by adrpo** [comment]
I guess we could actually generate a correct Modelica file, just include everything inside the total model.

**Comment by adeas31** [comment]
I remember we discussed this earlier as well. Just wrap everything in a package.

**Comment by casella** [comment]
Of course we could do that, but then the package browser will show something different from what you had originally, e.g. it will show Modelica as a sub-package. If you have models that instantiate something from `.Modelica` (which is what @sjoelund.se would like us to do all the time, BTW), those will stop to work. Is this what we want?

I would prefer if OMEdit just ran loadFile() and then showed whatever has been parsed into memory. Probably we should add a "Load saveTotal file" menu item to do that.

Anyway, in the meantime, let's document what we have already :)

**Comment by adeas31** [comment]
> I would prefer if OMEdit just ran loadFile() and then showed whatever has been parsed into memory, so that it looks the same as it did originally (but without the unused classes).

Sorry I don't get it.

**Pull request merged**
