### PR TITLE
Add more language standards.

### PR DESCRIPTION
**Pull request by perost**
- Add 3.4, 3.5, and experimental as language standards.
- Change LanguageStandard.latest to mean 3.4.

### CODE REVIEW

**Comment by sjoelund** [comment]
Should versionStringToStd2 be updated to be --std=3.3 for MSL 3.2.3? Or does this mess something up in MSL? I think it's a bit bad that Synchronous Modelica is still disabled by default due to loading the default MSL...

**Comment by perost** [comment]
> Should versionStringToStd2 be updated to be --std=3.3 for MSL 3.2.3? Or does this mess something up in MSL? I think it's a bit bad that Synchronous Modelica is still disabled by default due to loading the default MSL...

Oh right, versionStringToStd maps MSL versions to Modelica standard versions. I guess I might have messed that one up then.

**Comment by perost** [comment]
Fixed versionStringToStd and added 3.2.3 => 3.3 as suggested.

**Comment by perost** [comment]
I reverted the 3.2.3 => 3.3 change, since it broke the openmodelica/fmi/ModelExchange/2.0/FMUResourceTest.mos test case for some reason.

**Pull request merged**
