### PR TITLE
Handle incorrect models better in getModelInstance

### PR DESCRIPTION
**Pull request by perost**
- Try to ignore missing types.
- Treat connectors where part of the name can't be found like expandable connectors, to allow connectors referring to elements inside missing types.

### CODE REVIEW

**Comment by perost** [comment]
@adeas31: For a component with a missing type I just dump `"type": null` now. I'm not sure if that's good or if we should just skip the type attribute completely in that case. Just let me know what you prefer and I'll change it.

**Comment by adeas31** [comment]
We need to dump the missing type as well. This allows OMEdit to build some sort of dependency that when a missing type is loaded/created then OMEdit can automatically change from the red box to actual type.

**Comment by perost** [comment]
> We need to dump the missing type as well. This allows OMEdit to build some sort of dependency that when a missing type is loaded/created then OMEdit can automatically change from the red box to actual type.

That's true. I changed it so that it's instead dumped like:
```
"type": {
  "name": "MissingClass"
},
```
I.e. same structure like a normal class, but with only the name.

**Comment by adeas31** [comment]
No no that will not make OMEdit very happy. If `type` is a JSON object then OMEdit expects its to be a proper class.
Why not just `"type": "MissingClass"`.

**Comment by perost** [comment]
> No no that will not make OMEdit very happy. If `type` is a JSON object then OMEdit expects its to be a proper class. Why not just `"type": "MissingClass"`.

I assumed that it would be easier for OMEdit to detect that the class is missing if it gets an object with only the name, rather than a string since we already dump builtin types as strings.

**Comment by adeas31** [comment]
Yeah that's true.

So what about?

```
"type": {
"name": "MissingClass"
"missing": true
}
```

otherwise of course just the name will work as well.

**Comment by perost** [comment]
> Yeah that's true.
> 
> So what about?
> 
> ```
> "type": {
> "name": "MissingClass"
> "missing": true
> }
> ```
> 
> otherwise of course just the name will work as well.

Ok, I updated the PR to add a "missing" attribute.

**Pull request merged**
