### PR TITLE
Allow parametric plot of multiple variables against one variable

### LINKED ISSUE #4449: Plot Parametric issues

### PR DESCRIPTION
**Pull request by adeas31**
### Related Issues

Fixes #4449

### Purpose

It is not possible to do parametric plot of many variables against one variable.

### Approach

Allow selecting the x-axis variable with the shift key and then user can select one or many y-axis variables.

### CODE REVIEW

**Comment by hkiel** [comment]
Is it possible to plot more than one x,y pair (e.g. in OMNotebook) with the [`plotParametric()`](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.plotParametric.html) function?

**Comment by max-privato** [comment]
I tested the new functions and they work as expected. Using shift is practical and effective.

A small issue: the text "select x axis variable..." appears also on the SVG output, and it shouldn't.

Moreover, I would recommend, for all plots, to put is a single space between the variable name and the unit of measure, not double's.
This would enhance the legend of all plots, especially of parametric plots in which the legend
[tq.zip](https://github.com/OpenModelica/OpenModelica/files/6309199/tq.zip)

 is more complex.

**Comment by adeas31** [comment]
> Is it possible to plot more than one x,y pair (e.g. in OMNotebook) with the [`plotParametric()`](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.plotParametric.html) function?

No, it is not possible. You need to add a new plot/graph cell or what ever it is called.

**Comment by adeas31** [comment]
> I tested the new functions and they work as expected. Using shift is practical and effective.

Good!

> A small issue: the text "select x axis variable..." appears also on the SVG output, and it shouldn't.

> The legend in case of parametric plots, with all the items, including units of measure, is not optimal. Maybe the word "vs" can be written in italic style?

I will try to fix these quickly.

**Pull request merged**
