### PR TITLE
Clean directories before unstash

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by sjoelund** [comment]
@AnHeuermann perhaps this will help us...

**Comment by AnHeuermann** [comment]
How would we test this? Run this PR 10 times and hope that if this won't solve it we will see en error?

**Comment by AnHeuermann** [comment]
This won't solve errors like
```
 > git submodule foreach --recursive git clean -fdx # timeout=10
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/OpenModelica/OpenModelica.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1001)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1242)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1302)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-8150/7/pipeline#step-488-log-13

Do we use `shallow copy` for git? That should be faster. Also we could increase the timeout limit for git in the advanced settings of Jenkins, see https://stackoverflow.com/questions/36017253/jenkins-git-fetch-timeout.

**Comment by sjoelund** [comment]
We use a locally cached version of the git repo. It's just that github doesn't answer. I believe it tries to contact the server even if it has the commit locally

**Pull request merged**
