### PR TITLE
[BE] resolveLoops update

### PR DESCRIPTION
**Pull request by kabdelhak**
- eqCrossNodes triple loops can be detected now
  - detection of equal structure (e.g. arrays)

### CODE REVIEW

**Comment by sjoelund** [comment]
OMSimulator and libraries were updated (was this intentional?)

**Comment by kabdelhak** [comment]
> OMSimulator and libraries were updated (was this intentional?)

Ah nope. I keep forgetting to ignore those... After jenkins is done and i can have a look at the results i will update this pull request.

**Comment by AnHeuermann** [comment]
Is it possible you forgot to remove changes for OMSimulator and libraries as sjoelund mentioned?

**Comment by adeas31** [comment]
I think is fine as its updated to the latest commit.

**Comment by kabdelhak** [comment]
> Is it possible you forgot to remove changes for OMSimulator and libraries as sjoelund mentioned?

No they have been removed.

**Comment by lochel** [comment]
@sjoelund Jenkins could check for it the same way it does it for OMSimulator. And then we could have a github label to bypass this check.

**Pull request merged**
