### PR TITLE
Do not call fmi2SetTime in instantiated state

### PR DESCRIPTION
**Pull request by adeas31**
Use fmi2SetupExperiment

### Related Issues

#5345

### CODE REVIEW

**Comment by adeas31** [comment]
This fixes the FMI import and the imported model simulates as well. However, I am not sure about the default values I set in `fmi2SetupExperiment` maybe someone who knows more about this can review it.

**Review by AnHeuermann — APPROVED** [review]
Judging from the state machine of calling sequence (see FMI Specification 2.0.3, section 3.2.3) it should be correct to call `fmi2SetupExperiment` before calling `fmi2EnterInitialization`.

**Comment by casella** [comment]
> This fixes the FMI import and the imported model simulates as well. However, I am not sure about the default values I set in `fmi2SetupExperiment` maybe someone who knows more about this can review it.

@adeas31 I was also a bit unsure. I checked Section 2.1.6 of FMI 2.0.3, as I understand you should set `toleranceDefined = false` and `stopTimeDefined = false`, so the two corresponding inputs `tolerance` and `stopTime` will be ignored. Then, you can just set them to zero. The only thing that matters is to set the value of the `startTime` input to the value of the Modelica `time` variable upon initialization.

**Comment by adeas31** [comment]
@adrpo for now just use `time` as `startTime`. We will see if we need to expose other runtime variables.

**Pull request merged**
