### PR TITLE
Handle functions returning enumerations.

### PR DESCRIPTION
**Pull request by mahge**
### Related Issues

#8166
### Purpose

  - Handle functions returning enumerations in `wrapFunctionCalls`.
### Approach
  - A case was missing for enumeration type return functions. It is now added.

### CODE REVIEW

**Comment by AnHeuermann** [comment]
Can we always return the error message in https://github.com/OpenModelica/OpenModelica/pull/8196/files#diff-9cc4431be7f701499677dfee1e848acbe3beb830f1fe4fa16b25514b55ebbe12R1483-R1488?

**Comment by mahge** [comment]
Absolutely. I will fix it.

**Comment by mahge** [comment]
It is updated now and should print an internal error. Something like

```sh
Error processing file: test.mo
[OpenModelica/OMCompiler/Compiler/BackEnd/CommonSubExpression.mo:1486:7-1486:114:writable] Error: Internal error   - createReturnExp failed for Enumeration
Error: post-optimization module wrapFunctionCalls (simulation) failed.
```

I think this does not really need a first class dedicated error message since this is the only place it is issued anyway. Internal error seems reasonable.

**Review by AnHeuermann — APPROVED** [review]

**Comment by adrpo** [comment]
All good here, merging this as it solves the issue with the model in #8166.

**Pull request merged**
