### PR TITLE
Add all states of the fmi state machines

### PR DESCRIPTION
**Pull request by lochel**
This is going to implement the full state machines for model exchange and co-simulation as described in the FMI2.0.3 specification, section 3.2.3 "State Machine of Calling Sequence" and section 4.2.4 "State Machine of Calling Sequence from Master to Slave".

### CODE REVIEW

**Comment by lochel** [comment]
The changes pass all the FMI tests that are not using the old "modelica wrapper"-based fmi import. How should we proceed? I am not in favor of bending things for the old import just to make these tests pass. Instead, I want the FMUs to be as close to the standard as possible. @adrpo @casella @sjoelund @AnHeuermann @mahge What do you think?

### This is what happens right now
Most of the tests fail with the following error message: "fmi2SetTime failed with status : Error". That is because the Modelica wrapper is calling fmi2SetTime outside a valid state (see the state machine for fmi function calls). If we are going to fix this particular function call, then we will get the same issue with a bunch of other function calls that get called outside a valid state.

**Comment by kabdelhak** [comment]
Why not move the old one to deprecated and issue a warning for everyone who tries to use it that it will be soon gone and refer to the new one? Maintaining two imports seems superfluous to me anyway.

Does someone use the old one? It has been faulty for some time now

**Comment by casella** [comment]
> Why not move the old one to deprecated and issue a warning for everyone who tries to use it that it will be soon gone and refer to the new one? Maintaining two imports seems superfluous to me anyway.

The problem is, there is no such thing as a "new import". We have OMSimulator. But that is an _FMU/SSP simulation tool_. It allows to simulate one FMU, or multiple connected FMUs. It is not a facility to import an FMI block inside a complex structured Modelica model. 

For example, suppose you have an object-oriented vehicle model with replaceable tyre models, where the tyre characteristic laws for some models of tyres (not all) are embedded in FMUs for confidentiality issues. If you have FMI import in Modelica, you can keep all the object-oriented structure, with redeclares and stuff. If you want to do this with OMSimulator, you'd have to do something really ugly from the point of view of model structure. Just try that out.

We are talking about two completely different user requirements here. Despite claims of the contrary by some OSMC developers, OMSimulator _is by no means a replacement_ of FMI import in a complex structured Modelica model.

See, e.g., the discussion in  [#5621](https://trac.openmodelica.org/OpenModelica/ticket/5621#comment:26) and [#5345](https://trac.openmodelica.org/OpenModelica/ticket/5345)

The question is: can we still allow the (old) FMI import _by introducing some limitations_ which allow it to work without problems? As long as we make them clear (and possibly check for them explicitly) this would be the best solution to me.

> Does someone use the old one? It has been faulty for some time now

Yes! @max-privato has been begging for years to continue supporting this feature. See the above-cited discussions.

**Comment by lochel** [comment]
@casella I am fine with keeping the old import if someone is willing to maintain it.

**Comment by casella** [comment]
> @casella I am fine with keeping the old import if someone is willing to maintain it.

OK. That shouldn't be a big deal according to my proposal, as long as we have a clear list of what features of FMI are currently not supported/not implemented/not implementable. 

@lochel, @adrpo, you seemed to have fairly clear ideas about that. Could you please add a list of those feature to #5345?

**Comment by casella** [comment]
Of course we still need to get this PR through 😃

**Comment by adrpo** [comment]
Of course portable FMI import in Modelica has been discussed by MA for years with no conclusion:
https://github.com/modelica/ModelicaSpecification/issues/1727
https://github.com/modelica/ModelicaStandardLibrary/issues/2389
However some tools seem to support it somehow. The question is *how*?

**Comment by lochel** [comment]
> Of course portable FMI import in Modelica has been discussed by MA for years with no conclusion: [modelica/ModelicaSpecification#1727](https://github.com/modelica/ModelicaSpecification/issues/1727) [modelica/ModelicaStandardLibrary#2389](https://github.com/modelica/ModelicaStandardLibrary/issues/2389) However some tools seem to support it somehow. The question is _how_?

But we do not even aim for a portable FMI import, or what do you mean by that? We try to import a FMU into OpenModelica. And that is possible. It is just that our old fmi import isn't realy up to the task.

**Comment by adrpo** [comment]
By portable I mean without tool extensions to the Modelica standard.

**Pull request merged**
