### PR TITLE
Do not hardcode OPENMODELICAHOME in OMEdit

### PR DESCRIPTION
**Pull request by sjoelund**
This resolves ticket:5640.

### CODE REVIEW

**Comment by adeas31** [comment]
Isn't it better to use [QCoreApplication::applicationDirPath()](https://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath)?

**Comment by adrpo** [comment]
That would not help if the libOpenModelicaCompiler.dll/so is someplace else than OMEdit executable.

**Comment by sjoelund** [comment]
It could work, but we know we can get the path from OMC

**Comment by adrpo** [comment]
@adeas31 is this OK with you? can we merge it? 
Would be nice to not depend on any env variables anymore so we can have multiple OpenModelica installations on the same computer.

**Comment by adrpo** [comment]
I think in Windows calling SettingsImpl__getInstallationDirectoryPath will actually use OPENMODELICAHOME so we need to fix that as well. I'll open a new ticket about this.

**Comment by adrpo** [comment]
See also: https://trac.openmodelica.org/OpenModelica/ticket/5943

**Pull request merged**
