### PR TITLE
[OMSI] Added first OMSIC test

### PR DESCRIPTION
**Pull request by AnHeuermann**
First test to build FMU with simCodeTarget=omsi

Belonging to PR
  - OpenModelica/OMCompiler#3067

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2019-04-26_12-56-09](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6707/).

**Comment by lochel** [comment]
It would be good to simulate the generated unit with OMSimulator, see e.g. `testsuite\omsimulator\DualMassOscillator.mo`.

**Comment by AnHeuermann** [comment]
I'm still having an error with my new OMSI test. Rtest can't find the clean rule, but it is there.
```
 + buildSimpleOMSU                                                                   ... equation mismatch [time: 1]

==== Log /tmp/omc-rtest-aheuermann1/openmodelica/omsi/omsic/buildSimpleOMSU.mos_temp2047/log-buildSimpleOMSU.mos
true
""
true
""
"buildSimpleOMSU.fmu"
"Warning: The initial conditions are not fully specified. For more information set -d=initialization. In OMEdit Tools->Options->Simulation->OMCFlags, in OMNotebook call setCommandLineOptions("-d=initialization").
"
make: *** No rule to make target 'clean'.  Stop.

Equation mismatch: diff says:
--- /tmp/omc-rtest-aheuermann1/openmodelica/omsi/omsic/buildSimpleOMSU.mos_temp2047/equations-expected  2019-04-26 15:14:43.646005830 +0200
+++ /tmp/omc-rtest-aheuermann1/openmodelica/omsi/omsic/buildSimpleOMSU.mos_temp2047/equations-got       2019-04-26 15:14:44.174001945 +0200
@@ -3,5 +3,6 @@
 true
 ""
 "buildSimpleOMSU.fmu"
 "Warning: The initial conditions are not fully specified. For more information set -d=initialization. In OMEdit Tools->Options->Simulation->OMCFlags, in OMNotebook call setCommandLineOptions("-d=initialization").
 "
+make: *** No rule to make target 'clean'.  Stop.

Equation mismatch: omc-diff says:
Line 8: Actual file has more input than expected.

== 1 out of 1 tests failed [openmodelica/omsi/omsic/buildSimpleOMSU.mos_temp2047, time: 1]
```
Is there another place where I need to add the new test / makefile?

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2019-04-29_12-51-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6708/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2019-04-29_13-34-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6709/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-04-29_17-05-33](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6715/console).

**Pull request closed without merging**
