### PR TITLE
[janitor] cleaner filename

### PR DESCRIPTION
**Pull request by phannebohm**
I saw this snippet while looking at #844 and then changed it to what I believe is cleaner code.
Does it please your eyes as well?

### CODE REVIEW

**Comment by phannebohm** [comment]
I made a mistake in my first attempt to tidy this up. The variable `pos2` was still in use in line 604. I had deleted its declaration, which should have resulted in a compile time error. Yet the testsuite did not complain. What's up with that?
Is this code never tested, or is it only run in the linux world, thus `#if defined(__MINGW32__) || defined(_MSC_VER)` never evaluates to true, or do I misunderstand something?

**Comment by kabdelhak** [comment]
> I made a mistake in my first attempt to tidy this up. The variable `pos2` was still in use in line 604. I had deleted its declaration, which should have resulted in a compile time error. Yet the testsuite did not complain. What's up with that?
> Is this code never tested, or is it only run in the linux world, thus `#if defined(__MINGW32__) || defined(_MSC_VER)` never evaluates to true, or do I misunderstand something?

Did you change the commit history by force pushing? From what i can see neither before or after it is used in line 604: 

The linearize function is definitely tested in `/testsuite/openmodelica/linearization/` and also oftentimes used by at least Francesco and his students and colleagues. It should not even compile without that definition, maybe you mixed something up.

**Comment by phannebohm** [comment]
> Did you change the commit history by force pushing? From what i can see neither before or after it is used in line 604:
Yess, I corrected it before commenting. It was definitely wrong before, take a look:
https://github.com/OpenModelica/OpenModelica/commit/102f5034d0e1bb9ed61838b7974bbad5bc59ac25
Also the testsuite passed before my corrections, which I cannot prove, but maybe you believe me.

> The linearize function is definitely tested in `/testsuite/openmodelica/linearization/` and also oftentimes used by at least Francesco and his students and colleagues. It should not even compile without that definition, maybe you mixed something up.
I suspect when compiling under linux the preprocessor deletes that line so it remains unnoticed, until windows users try to run it, that is :(

**Comment by phannebohm** [comment]
Also I noticed the title of this PR is really bad, sorry xD

**Comment by kabdelhak** [comment]
> Also the testsuite passed before my corrections, which I cannot prove, but maybe you believe me.
Haha you don't have to prove it. :D But you can see the full history in the jenkins pipeline (top left) and the first run definitely went through.
> I suspect when compiling under linux the preprocessor deletes that line so it remains unnoticed, until windows users try to run it, that is :(
I guess so... i have no other explanation

**Comment by kabdelhak** [comment]
> Also I noticed the title of this PR is really bad, sorry xD

you can still change it :P

**Comment by mahge** [comment]
> I suspect when compiling under linux the preprocessor deletes that line so it remains unnoticed, until windows users try to run it, that is :(

By default Hudson does not build Windows omc. However, you can add the label "CI/Build Mingw" to the PR. It will then build a windows version as well. I guess it is not done by default to save time.

**Comment by phannebohm** [comment]
> By default our Hudson CI does not build Windows omc. However, you can add the label "CI/Build Mingw" to the PR. It will then build a windows version as well. I guess it is not done by default to save time.

OK that makes sense. Thank you!

**Pull request merged**
