### PR TITLE
9036 record constants

### LINKED ISSUE #9036: Constant var in record not initialized
### Description

A constant variable from a record is not initialized with a start value.

### Steps to Reproduce

Run

```Modelica
model Test
  record R
    constant Integer m = 0;
  end R;

  function foo
    "Documentation"
    input R r;
    output Integer n;
  algorithm
    assert(r.m == 7, "n not 7");
    n := r.m + 1;
  end foo;

  R r = R(m=7);
  Integer n;
equation
  n = foo(r);
end Test;
```

### Expected Behavior

Generate a equation for the constant `r.m = 7`.

For parameters

```Modelica
record R
  parameter Integer m = 0;
end R;
```

we get the start value from the init file (?).

### Version and OS

 - OpenModelica Version: v1.20.0-dev-106-gd31fbb2d46
 - OS: Ubuntu Focal

### Additional Context

From #9021 and needed for `ClaRa.Components.Mills.HardCoalMills.Check.combineMillandFurnace` from ClaRa dev version.

### PR DESCRIPTION
**Pull request by kabdelhak**
Fixes #9036 

During the phase of lowering FE->BE:
1. traverse all equations and collect record types from exps
2. traverse all variables and update record types with bindings of record elements
3. traverse all equations and apply updated record types

### CODE REVIEW

**Comment by AnHeuermann** [comment]
I tested this PR on the ClaRa model from #9021 and got the same error message as before, see https://github.com/OpenModelica/OpenModelica/issues/9021#issuecomment-1137329949.

Maybe we need to find another example for #9021.

**Comment by AnHeuermann** [comment]
New mwe that still fails
```Modelica
package Test2
  model SimCenter
    replaceable parameter ExtendedRecord1 rec constrainedby EmptyRecord;
  end SimCenter;

  record BaseRecord
    constant Integer m;
  end BaseRecord;

  record ExtendedRecord1
    extends BaseRecord(m=7);
  end ExtendedRecord1;

  partial record EmptyRecord
  end EmptyRecord;

  function foo
    input BaseRecord rec;
    output Integer m;
  algorithm
    assert(rec.m == 7, "m not 7");
    m := rec.m;
  end foo;

  model InnerM
    outer SimCenter simCenter;
    parameter BaseRecord fuelModel = simCenter.rec; // <------ the important line
    Integer m;
  equation
    m = foo(fuelModel);
  end InnerM;

  model Test
    InnerM innerM;
    inner SimCenter simCenter(replaceable ExtendedRecord1 rec);
  end Test;
end Test2;
```

**Comment by AnHeuermann** [comment]
We're getting closer...

Arrays of constants are not working and get replaced by some scalar variable.

Instead of

```C
omc_ClaRa_Basics_Media_FuelTypes_BaseFuel(threadData,
  ((modelica_integer) 7),
  ((modelica_integer) 7),
  tmp4,
  tmp5,
  tmp6,
  ((modelica_integer) 7),
  ((modelica_integer) 6),
  tmp7,
  tmp8,
  273.15
)
```

we get

```C
omc_ClaRa_Basics_Media_FuelTypes_BaseFuel(threadData,
  ((modelica_integer) 7),
  ((modelica_integer) 7),
  tmp4,
  tmp5,
  1000.0,  // <---- should be an array of constants
  ((modelica_integer) 7),
  ((modelica_integer) 6),
  0.025,  // <---- should be an array of constants
  tmp6,
  273.15  // <---- should be an array of constants
)
```

**Comment by AnHeuermann** [comment]
We are getting closer and closer 🔥 

The bindings for constant arrays and matrices are now correctly set in the backend. For matrices the test is working, but for arrays we generate wrong code in the templates:

```C
array_alloc_real_array(&tmp1, 3, 4.0, 5.0, 6.0);
```

We need to construct a base_array for `{4,5,6}` and pass that one to `array_alloc_real_array`.

**Comment by phannebohm** [comment]
:fire:

**Pull request merged**
