### PR TITLE
listReverse iters in TYPED_ARRAY_CONSTRUCTOR

### PR DESCRIPTION
**Pull request by AnHeuermann**
- Fix for ticket https://trac.openmodelica.org/OpenModelica/ticket/6268

### CODE REVIEW

**Review by mahge — COMMENTED** [review]
I think this is upto @perost. According to his explanation it is already doing the right thing. I think I agree too. We might need to find out where the call in converted to an array. Probably in the old front end (or maybe in NF when converting to DAE). I will try to find it. You can of course use this as a temporary fix for continuing with your work.

**Comment by perost** [comment]
ExpressionSimplify.simplifyReduction does the simplification `array(tanh({{10.0, 20.0, 30.0, 40.0}}[$i1, $i2]) for $i2 in 1:4, $i1 in 1:1) => array(array(tanh({{10.0, 20.0, 30.0, 40.0}}[$i1, $i2]) for $i1 in 1:1) for $i2 in 1:4)`, which is wrong since it's turned the array reduction inside out. I will see if I can fix it.

**Comment by perost** [comment]
After looking at the specification I've changed my mind again, it seems I've forgotten how multiple iterators work with array constructors. So I think this might actually be the correct solution after all.

**Comment by perost** [comment]
There are some test failures, but it looks like the test just need to be updated.

I've also opened a ticket for the specification ([#2749](https://github.com/modelica/ModelicaSpecification/issues/2749), since it's currently ambiguous how array constructors with multiple iterators should be handled. But we handle them like the examples, which I'm pretty sure is correct.

**Comment by perost** [comment]
> There are some test failures, but it looks like the tests just need to be updated.
> 
> I've also opened a ticket for the specification ([#2749](https://github.com/modelica/ModelicaSpecification/issues/2749)), since it's currently ambiguous how array constructors with multiple iterators should be handled. But we handle them like the examples, which I'm pretty sure is correct.

It was pointed out in the ticket I opened that the examples in the specification might actually be wrong, so now I'm even more confused. But it does actually seem like both of the frontend and Dymola handle it like the text says and not the example, which means ExpressionSimplify and this PR are wrong anyway. The whole situation is rather confusing...

**Comment by perost** [comment]
I think #7021 fixed this issue properly, we'll see.

**Comment by AnHeuermann** [comment]
Okay, I'll close this issue.
Everything else can be discussed in #7021

**Comment by AnHeuermann** [comment]
I had a lock at https://specification.modelica.org/master/functions.html#scalar-functions-applied-to-array-arguments
Does the example with atan misses some brackets `{`?

Also I can't see why it should make any sense to replace
`atan({a, b, c}, {d, e, f})` with `{atan({a, d}), atan({b, e}), atan({c, f})}` and finally with `{{atan(a), atan(d)}, {atan(b),atan(e)}, {atan(c), atan(f)}}`. Or did I misread the example?
But if that is the correct definition I can just fix my model that is using this.

**Comment by perost** [comment]
> I had a lock at https://specification.modelica.org/master/functions.html#scalar-functions-applied-to-array-arguments
> Does the example with atan misses some brackets `{`?
> 
> Also I can't see why it should make any sense to replace
> `atan({a, b, c}, {d, e, f})` with `{atan({a, d}), atan({b, e}), atan({c, f})}` and finally with `{{atan(a), atan(d)}, {atan(b),atan(e)}, {atan(c), atan(f)}}`. Or did I misread the example?
> But if that is the correct definition I can just fix my model that is using this.

`atan` takes two arguments, so the example `atan({a, b, c}, {d, e, f}) = {atan(a, d), atan(b, e), atan(c, f)}` is correct.

**Comment by mahge** [comment]
Another bad example I think. Why would you be famously one argument function to show multiple argument vectorization? ¯\_(ツ)_/¯

**Comment by AnHeuermann** [comment]
@perost Do you want to add this to https://github.com/modelica/ModelicaSpecification/issues/2749 or should I add a new issue?

**Comment by perost** [comment]
I opened a PR, [#2750](https://github.com/modelica/ModelicaSpecification/pull/2750)

**Pull request closed without merging**
