### PR TITLE
Fix dylib

### PR DESCRIPTION
**Pull request by hkiel**
fixes compilation on macOS

### CODE REVIEW

**Comment by hkiel** [comment]
@adrpo This PR is missing in 1.7.0 release and stops me from building on mac. Can you add it to 1.7.1 if it will ever be released? Don't know if this also applies to other PRs for mac build.

**Comment by hkiel** [comment]
With this PR compilation is fine, except for a starting problem, where `config.guess` and `config.sub` were not automatically generated (I needed to run `autoreconf --install` by hand) and a problem wiht the portfile using qt5 (I switched back to use qt4)
Running a simulation still does not work, first because of missing rpath (can fix that by script) and then because of missing symbol in library

 ```

record SimulationResult
    resultFile = "",
    messages = "Simulation execution failed for model: A1
dyld: _dyld_bind_fully_image_containing_address() error
dyld: Symbol not found: _dgetrf
  Referenced from: /opt/local/lib/x86_64-darwin18.7.0/omc/libsundials_sunlinsollapackdense.3.dylib
  Expected in: flat namespace
 in /opt/local/lib/x86_64-darwin18.7.0/omc/libsundials_sunlinsollapackdense.3.dylib
/bin/sh: line 1: 60245 Abort trap: 6           ( \"/private/var/folders/v0/jwlb2_z56gzfjhxrxdd_0q2r0000gn/T/OpenModelica/A1\" )
"
end SimulationResult;
```

**Comment by adrpo** [comment]
Yes, the plan is to fix the Mac stuff for 1.17.1, I didn't have time yet to do that.

**Comment by adrpo** [comment]
@hkiel to fix the missing `_dgetrf` configure sundials with: `-DSUNDIALS_F77_FUNC_CASE:String=lower -DSUNDIALS_F77_FUNC_UNDERSCORES:String=one`. I already fixed this on master but did not port any of the stuff to 1.17 yet.

**Pull request merged**
