### PR TITLE
Fix ticket #6171

### PR DESCRIPTION
**Pull request by phannebohm**
TODO generalize to all inverse functions

### CODE REVIEW

**Comment by phannebohm** [comment]
Oh no, what happened to the commits? They are squashed together :crying_cat_face:

**Comment by adrpo** [comment]
Sorry, I had squash & merge selected by default. 
I don't think is good to force push to the master branch (is not even possible as we have them protected against direct push). 
@sjoelund is it possible to edit the message only and keep the commit hash on the master?

**Comment by sjoelund** [comment]
No, you cannot edit a message without changing hash

**Comment by phannebohm** [comment]
Oh well, for the future I'll remember to only have one commit per PR

**Pull request merged**
