### PR TITLE
Qt6

### PR DESCRIPTION
**Pull request by adrpo**
See #11581, this is just a copy of that PR so Jenkins behaves on changes to Jenkinsfile.

### CODE REVIEW

**Comment by adeas31** [comment]
Requires https://github.com/OpenModelica/OMOptim/pull/23 merged and OMOptim updated.

**Comment by adeas31** [comment]
Requires https://github.com/OpenModelica/OMSens_Qt/pull/34 merged and OMSens_Qt updated.

**Comment by adeas31** [comment]
@jschueller I pushed in all my changes. Please check if everything works on Arch Linux. 

We should also add a new CMake-qt6 stage in the pipeline. For that to work, we need to update our docker image with qt6.

On windows QtWebEngine is still not available for msys package manager. I have disabled the documentation in Windows when compiling with OMEdit qt6. Perhaps we should do the same for Ubuntu to avoid the webengine crash. OMEdit also shows the following message on startup,

```
qt.qpa.window: SetProcessDpiAwarenessContext() failed: The operation completed successfully.
Qt's default DPI awareness context is DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2. If you know what you are doing, you can overwrite this default using qt.conf (https://doc.qt.io/qt-6/highdpi.html#configuring-windows).
```

No idea why. Some forum says that, Qt6 enables the dpi aware context by default and this message is shown since OMEdit already enables it and when Qt tries to enable it again then the message is shown. I can't find any code that sets the dpi aware context.

**Comment by jschueller** [comment]
everything good for me

**Comment by AnHeuermann** [comment]
If this is done I can finish https://github.com/OpenModelica/OpenModelica/pull/12404. My PR is stuck because some Qt5 package we need isn't available on Ubuntu Noble (at least the last time I checked).

**Comment by adeas31** [comment]
> If this is done I can finish #12404. My PR is stuck because some Qt5 package we need isn't available on Ubuntu Noble (at least the last time I checked).

This PR is only intended to add support for Qt6 and not to remove Qt5. We will continue with Qt5 until Qt6 webengine is available on Windows and Ubuntu.

**Comment by adeas31** [comment]
@adrpo can you please add qt6 to openmodelica docker

**Comment by jschueller** [comment]
Maybe the library changes could go in without the CI changes, then do the CI changes in another PR ?

**Comment by adeas31** [comment]
The CI changes for Windows are working fine since we added Qt6 to OMDev. I am just waiting for @adrpo to udpate the docker image so we have a Linux pipeline for it as well.

**Comment by adeas31** [comment]
Removed the pipeline stage `cmake-jammy-gcc-qt6` for now. Will add it later with another PR when the docker image with qt6 is ready.

**Comment by jschueller** [comment]
great!

**Pull request merged**
