### PR TITLE
Improve handling of DynamicSelect in OMEdit

### PR DESCRIPTION
**Pull request by perost**
- Implemented an Expression class for parsing and evaluating flat
  modelica expressions, with support for most builtin operators and
  functions.
- Use the new Expression class for textString annotations to enable
  dynamic behaviour via DynamicSelect.

### CODE REVIEW

**Comment by perost** [comment]
There are a couple of issues that still need to be resolved, either in this or
in a future PR:

* OMEdit uses StringHandler::getStrings to split annotations, but it breaks when
  there's a DynamicSelect call in the string (since it contains a ,). I "solved"
  this for now by just having the frontend turn DynamicSelect calls into
  strings. A better solution would be to improve getStrings so it handles calls
  properly, or just use the new Expression class to parse the whole annotation.

* It only works with the nfAPI right now, but it probably won't be too much work
  to change the old frontend to do the same.

* Only the textString annotation is handled so far.

* DynamicSelect is only handled if the whole expression is a DynamicSelect call,
  not when DynamicSelect is used as part of another expression. The Expression
  class doesn't really care, it just complicates things when trying to select
  the first or the second argument. It might not actually be legal to have
  DynamicSelect as a subexpression, the specification doesn't really say.

**Comment by perost** [comment]
Another issue I forgot to mention: the code is so far mostly undocumented, I will add comments later.

**Comment by adeas31** [comment]
> OMEdit uses StringHandler::getStrings to split annotations, but it breaks when there's a DynamicSelect call in the string (since it contains a ,). I "solved" this for now by just having the frontend turn DynamicSelect calls into strings. A better solution would be to improve getStrings so it handles calls properly, or just use the new Expression class to parse the whole annotation.

We can get rid of `StringHandler::getStrings` if we convert `getIcon/DiagramAnnotation` to OMCInterface

**Review by adrpo — APPROVED** [review]
Ok with me. I would have probably used the ANTLR lexer/parser in OpenModelica/OMParser but it would have probably been overkill for this one.

**Comment by adeas31** [comment]
@perost the code looks good. I think we should fix the remaining issues before merging this in.

I added a very basic test for the Expression class. You can add more tests by simply adding a new slot to the ExpressionTest class.

**Comment by perost** [comment]
> Ok with me. I would have probably used the ANTLR lexer/parser in OpenModelica/OMParser but it would have probably been overkill for this one.

I actually didn't realize OMParser existed. But no matter, it didn't take me more than a few hours to implement the parsing anyway, it's mostly just a simple top-down parser. In the future when someone has more time we might want to replace it with something more professional though.

> I added a very basic test for the Expression class. You can add more tests by simply adding a new slot to the ExpressionTest class.

Did you forget to add some files?

**Comment by perost** [comment]
I updated the test case that was failing so we can merge this in. I also force-pushed and overwrote the testsuite additions by @adeas31, since they caused the job to fail (due to missing files?). I'll continue to improve this once it's merged, but for now it seems better to get the basic functionality in.

**Pull request merged**
