### PR TITLE
Remove excess nesting

### PR DESCRIPTION
**Pull request by FDzhang**
### Related Issues

no

### Purpose

Equivalent logic, reducing hierarchy

### Approach

Remove excess nesting

### CODE REVIEW

**Comment by phannebohm** [comment]
If I see it correctly, you simplified this
```c
if (b1 && b2)  f1();
else if (b1)   f2();
else {
  if (b3)      f2();
  else if (b2) f1();
  else         f2();
}
```
into this
```c
if (b2) f1();
else    f2();
```

with these abbreviations:
```c
b1 = isTopLevel()
b2 = fileInfo.fileName().compare("package.mo") == 0
b3 = mpParentLibraryTreeItem->getFileName().compare(getFileName()) == 0
f1 = setSaveContentsType(LibraryTreeItem::SaveFolderStructure)
f2 = setSaveContentsType(LibraryTreeItem::SaveInOneFile)
```

I think they have different behavior in one case: when `(!b1) && b2 && b3`. Not sure what should happen here though. @adeas31?

In any case `b1` seems to be irrelevant. Nice catch!

**Comment by FDzhang** [comment]
> If I see it correctly, you simplified this
> 
> ```c
> if (b1 && b2)  f1();
> else if (b1)   f2();
> else {
>   if (b3)      f2();
>   else if (b2) f1();
>   else         f2();
> }
> ```
> 
> into this
> 
> ```c
> if (b2) f1();
> else    f2();
> ```
> 
> with these abbreviations:
> 
> ```c
> b1 = isTopLevel()
> b2 = fileInfo.fileName().compare("package.mo") == 0
> b3 = mpParentLibraryTreeItem->getFileName().compare(getFileName()) == 0
> f1 = setSaveContentsType(LibraryTreeItem::SaveFolderStructure)
> f2 = setSaveContentsType(LibraryTreeItem::SaveInOneFile)
> ```
> 
> I think they have different behavior in one case: when `(!b1) && b2 && b3`. Not sure what should happen here though. @adeas31?

You're right, maybe it should be
```c
if (b2) f1();
else    f2();

if (!b1 && b3) f2();
```
Also, in my understanding, do 
```c
    b3 = mpParentLibraryTreeItem->getFileName().compare(getFileName()) == 0

    and 

    b3 = mpParentLibraryTreeItem->getFileName().compare("package.mo") == 0
```
mean the same thing?

**Comment by mahge** [comment]
This is the best I can simplify it to:
```c
if ((b1 && b2) || (b2 || !b3)) f1();
else f2();
```

For readability reasons, this can also be written as
```c
if (b1 && b2) f1();
else if (b2 || !b3) f1();
else f2();

**Comment by phannebohm** [comment]
> You're right, maybe it should be
> 
> ```c
> if (b2) f1();
> else    f2();
> 
> if (!b1 && b3) f2();
> ```

More like:
```c
if (b2) {
  if (!b1 && b3) f2();
  else f1();
}
else f2();
 ```

> Also, in my understanding, do
> 
> ```c
>     b3 = mpParentLibraryTreeItem->getFileName().compare(getFileName()) == 0
> 
>     and 
> 
>     b3 = mpParentLibraryTreeItem->getFileName().compare("package.mo") == 0
> ```
> 
> mean the same thing?

I'm not sure. But to be honest, I'm not familiar with the semantics of this part of the code. :sweat_smile:

**Comment by phannebohm** [comment]
> This is the best I can simplify it to:
> 
> ```c
> if ((b1 && b2) || (b2 || !b3)) f1();
> else f2();
> ```

I think it should be `(b1 && b2) || (b2 && !b3)` which then can be simplified to `b2 && (b1 || !b3)`.

**Comment by FDzhang** [comment]
> More like:
> ```c
> if (b2) {
>   if (!b1 && b3) f2();
>   else f1();
> }
> else f2();
> ```
ok, Yes, this is more direct. But I think using "guard clause" may be more readable.  :joy:

**Comment by mahge** [comment]
> > This is the best I can simplify it to:
> > ```c
> > if ((b1 && b2) || (b2 || !b3)) f1();
> > else f2();
> > ```
> 
> I think it should be `(b1 && b2) || (b2 && !b3)` 

You are right, it should be `&&` and not `||`. So it should be
```c
if ((b1 && b2) || (b2 && !b3)) f1();
else f2();
```

OR

```c
if (b1 && b2) f1();
else if (b2 && !b3) f1();
else f2();
```

> which then can be simplified to `b2 && (b1 || !b3)`.

I prefer the disjunction of conjunctions though. It feels "simpler" and easier to take-in (if that makes sense).

**Comment by phannebohm** [comment]
> ```c
> if (b1 && b2) f1();
> else if (b2 && !b3) f1();
> else f2();
> ```
> 
> > which then can be simplified to `b2 && (b1 || !b3)`.
> 
> I prefer the disjunction of conjunctions though. It feels "simpler" and easier to take-in (if that makes sense).

Yes, this might be more readable.

> I think using "guard clause" may be more readable. joy

This is assuming `setSaveContentsType(LibraryTreeItem::<saving-mode>)` has no side effects, which I don't know. If that's the case then it would also be okay I guess.

In any case, there should be some clear comments on what happens and why.

**Comment by adeas31** [comment]
> Also, in my understanding, do
> 
> ```c
>     b3 = mpParentLibraryTreeItem->getFileName().compare(getFileName()) == 0
> 
>     and 
> 
>     b3 = mpParentLibraryTreeItem->getFileName().compare("package.mo") == 0
> ```
> 
> mean the same thing?

Its not the same.

> ```c
> if (b1 && b2) f1();
> else if (b2 && !b3) f1();
> else f2();
> ```

@mahge code looks fine for me and covers all the cases.

**Comment by FDzhang** [comment]
> > Also, in my understanding, do
> > ```c
> >     b3 = mpParentLibraryTreeItem->getFileName().compare(getFileName()) == 0
> > 
> >     and 
> > 
> >     b3 = mpParentLibraryTreeItem->getFileName().compare("package.mo") == 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > mean the same thing?
> 
> Its not the same.

ok, Get it，thanks
> 
> > ```c
> > if (b1 && b2) f1();
> > else if (b2 && !b3) f1();
> > else f2();
> > ```
> 
> @mahge code looks fine for me and covers all the cases.

ok, updated

Also, thanks for everyone's replies

**Review by adeas31 — APPROVED** [review]

**Pull request merged**
