### PR TITLE
Don't allow non-top-level within when loading top-level classes

### LINKED ISSUE #13047: The 'within' statement can be used to get access of a package in OMEdit translate - and should not be possible.
### Description
The 'within' can be used to get access of a package in OMEdit translate - and should not be possible.  The simulation works fine. The export to FMU does not work though, but the error text could be more clarifying. It seems that OMEdit tries to make an FMU: 

### Steps to Reproduce
The following package DEMO_v90 together with  the 'un-correct' model D90_2 illustrates the problem.

    package DEMO_v90
       package A
	      constant Real a=1;
	      constant Real b=2;
	      constant Real c=3;
       end A;	
       model M1
          replaceable package A = DEMO_v90.A;
          Real x, y, z;
       equation
          x = A.a;
          y = A.b;
          z = A.c;
       end M1;
       model M2
          replaceable package A = DEMO_v90.A;
          Real x, y, z;
       equation
          x = 2*A.a;
          y = 2*A.b;
          z = 2*A.c;
       end M2;
    end DEMO_v90;

And the 'un-correct' model D90_2 (separate file), which I must admit initially thought was an elegant solution 

    within DEMO_v90;
    model D90_2	
        M1 m1(redeclare package A = A);
        M2 m2(redeclare package A = A);
    end D90_2;

The correct model is D_90_1 below.

    model D90_1
       import DEMO_v90;	
       DEMO_v90.M1 m1(redeclare package A = DEMO_v90.A);
       DEMO_v90.M2 m2(redeclare package A = DEMO_v90.A);
    end D90_1;

### Expected Behavior
It would be helpful that during translation an error text comes that says something like that 'within' should not be used in this way and urge the use to instead use 'import'. The same error statement if export to FMU is tried. 

### Screenshots
The error text you get today after trying to export and FMU for D90_2 you see below.

Screenshot 2024-10-19 at 15 13 14

### Version and OS
OpenModelica version 1.25.0-dev-71g4fcfbbf
OS Linux Ubuntu 22.04, 64-bit

### Additional Context
The problem is discussed at Stackoverrflow 
https://stackoverflow.com/questions/79105169/use-of-modelica-concepts-within-or-import

### PR DESCRIPTION
**Pull request by perost**
- Don't allow classes to have non-top-level within clauses when loading with `loadFile` or `loadString`.
- Add flag to `loadFile` and `loadString` to disable this, since it's sometimes useful for testing.

Fixes #13047

### CODE REVIEW

**Comment by adeas31** [comment]
You need to update OMEdit.

**Comment by perost** [comment]
> You need to update OMEdit.

Yeah, I even had the files open to do it, but then I forgot since changing the API doesn't trigger a rebuild of the OMC Qt interface.

**Comment by perost** [comment]
> I think the good default for OMEdit is `allowWithin = true` since it do stuff like `within p; model m end m;` Also as I understand, `allowWithin = true` mimic the old behavior.

Where do you do that, with `loadString` or `loadFile`? I guess we don't really have to change `loadString`, but the point is to not allow it when loading user files.

**Comment by adeas31** [comment]
> > I think the good default for OMEdit is `allowWithin = true` since it do stuff like `within p; model m end m;` Also as I understand, `allowWithin = true` mimic the old behavior.
> 
> Where do you do that, with `loadString` or `loadFile`? I guess we don't really have to change `loadString`, but the point is to not allow it when loading user files.

Only with `loadString` e.g., when user manually modifies the modelica text in the editor.

**Comment by perost** [comment]
> > > I think the good default for OMEdit is `allowWithin = true` since it do stuff like `within p; model m end m;` Also as I understand, `allowWithin = true` mimic the old behavior.
> > 
> > 
> > Where do you do that, with `loadString` or `loadFile`? I guess we don't really have to change `loadString`, but the point is to not allow it when loading user files.
> 
> Only with `loadString` e.g., when user manually modifies the modelica text in the editor.

Ok, since it seems like this was seen as more of a feature than a bug by both the compiler and OMEdit I decided to scale back the changes. Now we just add the `allowWithin` flag to `loadFile` (and `loadFiles`) with default `true` to preserve the old API behaviour, but set it to `false` by default in OMEdit since OMEdit only seem to use it for `File -> Open`.

**Pull request merged**
