### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by scls19fr**
### Related Issues

Following discussion https://github.com/OpenModelica/OpenModelica/discussions/11222

### Purpose

French translation is lacking a lot of translated strings

### Approach

Edit OMEdit_fr.ts using QtLinguist

### CODE REVIEW

**Comment by scls19fr** [comment]
Ready for merge now

**Comment by scls19fr** [comment]
Sorry but I can't understand why NFExpression.mo and SD.mo are included here in this PR.

If someone can tackle that before merging that will be great!

**Comment by adeas31** [comment]
@perost I think @scls19fr merged with one of your commit. Can you please rebase this properly?

**Comment by perost** [comment]
> @perost I think @scls19fr merged with one of your commit. Can you please rebase this properly?

Rather than trying to untangle the merged commits it's probably easiest if @scls19fr just restarts from master and makes a new commit that only includes the translation file.

**Pull request closed without merging**
