### PR TITLE
Add missing record/array and constant variables to model info.json

### LINKED ISSUE #9506: Variables in info.json not expanded
### Description

I'm parsing the MODELNAME_info.json to get some useful information on used variables from non-linear equation systems.
In the `useVars` section the non-expanded name is used, in the `variables` block the expanded name is used.

```json
"variables": {
  "combustionChamber.flueGas_outlet.xi_outflow[1]":{},
  "combustionChamber.flueGas_outlet.xi_outflow[2]":{},
  "combustionChamber.flueGas_outlet.xi_outflow[3]":{},
  "combustionChamber.flueGas_outlet.xi_outflow[4]":{},
},
{
  "eqIndex": 552,
  "uses": [
    "...",
    "combustionChamber.flueGas_outlet.xi_outflow",
    "..."
  ]
}
```

Since OpenModelica currently flattens the array variables, they should be flattened everywhere.

### Steps to Reproduce

Run
```modelica
loadFile("/path/to/ClaRa/package.mo"); getErrorString();
cd("temp"); getErrorString();
buildModel(ClaRa.Components.Furnace.Check.Test_CombustionChamber_vs_Burner_control); getErrorString();
```

A list of variables that my tool can't find and that could be non-expanded in `ClaRa.Components.Furnace.Check.Test_CombustionChamber_vs_Burner_control_info.json`:
```
combustionChamber.flueGas_outlet.xi_outflow
burner.xi_flueGas
burner.fuelInlet.fuelModel
burner.fuelInlet.xi_c
burner.fuelInlet.fuelModel
burner.fuelInlet.xi_c
burner.fuelInlet.fuelModel
burner.fuelInlet.xi_c
burner.fuelInlet.fuelModel
burner.fuelInlet.xi_c
burner.fuelInlet.fuelModel
burner.fuelInlet.xi_c
burner.fuelInlet.fuelModel
burner.fuelInlet.xi_c
burner.fuelBurnerInlet.fuelModel
burner.fuelBurnerInlet.xi_c
burner.fuelBurnerInlet.fuelModel
burner.fuelBurnerInlet.xi_c
burner.fuelBurnerInlet.fuelModel
burner.fuelBurnerInlet.xi_c
burner.fuelBurnerInlet.fuelModel
burner.fuelBurnerInlet.xi_c
burner.fuelBurnerInlet.fuelModel
burner.fuelBurnerInlet.xi_c
burner.fuelBurnerInlet.fuelModel
burner.fuelBurnerInlet.xi_c
combustionChamber.flueGas_outlet.xi_outflow
```

### Expected Behavior

Expand all or no variables, but don't mix it.

### Version and OS

 - OpenModelica Version: v1.20.0-dev-341-g95b4c7812e
 - OS: Ubuntu Focal
 - Versions of used Modelica libraries: ClaRa-dev @ e974485ceb25c60d8f14d2036ac77ed6210ca86a

### PR DESCRIPTION
**Pull request by AnHeuermann**
### Related Issues

Fixes #9506.

### Purpose

Fix missing variables from info.json for some record/array variables and resolve missing constants.

### Approach

Add integer constants to model info and expand record/array variables in `uses` list from ModelInfo.
Also removing some unused functions from SimCodeTV.

### CODE REVIEW

**Comment by AnHeuermann** [comment]
@mahge Should `extractUniqueCrefsFromExpDerPreStart` get the same option to expand the component references?

**Comment by mahge** [comment]
I think it should if we want to be thorough. Right now, it is It is used only in dumping the information needed for dependency analysis for parallelization. That might be missing some info.

BTW note the difference between the two functions, `extractUniqueCrefsFromExp` and `extractUniqueCrefsFromExpDerPreStart` is that first one treats some operators like `der()` and `pre()`, as if they were function calls. 

That means give the expression `x + der(x)`:
- `extractUniqueCrefsFromExp` will give you only `x` as an extracted cref. 
- `extractUniqueCrefsFromExpDerPreStart` will give you `x` and `DER.x` as extracted crefs. 

I think in most cases we want the second case because those two are essentially two separate variables once we are past the FrontEnd. I am guessing you might probably want the second one as well even for `serializeModelInfo`.

**Comment by AnHeuermann** [comment]
> I think in most cases we want the second case because those two are essentially two separate variables once we are past the FrontEnd. I am guessing you might probably want the second one as well even for serializeModelInfo.

You are right. I need to also know if a equation depends on `x` or `der(x)`.

So I replaced `extractUniqueCrefsFromExp` with `extractUniqueCrefsFromExpDerPreStart`.
For now I can only see changes in when equations, e.g. this

```
"uses":["$whenCondition4","PID_lambda1.toPU.y"]
```

becomes

```
"uses":["$whenCondition4","$PRE.PID_lambda1.toPU.y"]
```

Should be fine. The variable `$PRE.PID_lambda1.toPU.y` isn't defined in the modle info, but removing `$PRE` is easy.

**Comment by mahge** [comment]
> For now I can only see changes in when equations, e.g. this

You mean you only encountered `pre()` operators and not the others, e.g., `der()`? If you notice something missing or odd let me know because I need to fix them.

Also, if you can think of a better name for the function change it. I just could not think of a good name.

**Comment by AnHeuermann** [comment]
> You mean you only encountered pre() operators and not the others, e.g., der()? If you notice something missing or odd let me know because I need to fix them.

I wasn't searching for it. But seems to work with `der` as well, at least for

```modelica
model M
  Real x(start=0, fixed=true);
  Real y;
  parameter Real a=0.9;
equation
  der(x) = a*x + sin(time);
  y = cos(time) + der(x);
end M;
```

**Pull request merged**
