### PR TITLE
Always choose der(state) as tearing variable

### PR DESCRIPTION
**Pull request by phannebohm**
### Related Issues

#7704

### Purpose

Try to see if that helps with anything. @casella can you test this with your thermo-fluid models?

### Approach

During simulation state derivatives are always chosen as tearing variables, unless specified otherwise by the user.

### CODE REVIEW

**Comment by casella** [comment]
@AndreaBartolini, please check the models from you-know-who when this PR is merged on master.

**Comment by casella** [comment]
@AnHeuermann, the attached model demonstrates the problem we're having with a simple Modelica.Fluid test case.

Unfortunately the problem is still there even if I set `--tearingMethod=minimalTearing`, so it seems that we may actually have to look for something else, and we should open yet another ticket. But I'm going on holiday this evening, so this can wait for a while.

If you can figure out why this model gets stuck at t = 0.21, you are eligible for the Fields medal 😄

**Comment by casella** [comment]
[TestStuckODE.txt](https://github.com/OpenModelica/OpenModelica/files/6909395/TestStuckODE.txt)

**Comment by phannebohm** [comment]
Some 8 models are still failing. Most of them look like they are okay and can just be updated, but I will have to check each of them in a little more in detail.
Not sure what's wrong with `Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMS_Start_MultiPhase`.

**Comment by phannebohm** [comment]
I seem to have broken something in the repository, I'll reopen this PR.

**Pull request closed without merging**
