### PR TITLE
Pass configure arguments to cpp-runtime

### PR DESCRIPTION
**Pull request by MarcusWalther**
I have just added a autoconf line, that gives us the possibility to pass configure arguments through the superproject and through the OMCompiler-project to the cpp-runtime.

### CODE REVIEW

**Comment by sjoelund** [comment]
Shouldn't this be in OMCompiler? OpenModelica.git does not seem to use this variable.

**Comment by MarcusWalther** [comment]
It's part of OMCompiler as well. But I want to run configure only once in the superproject and not again in the OMCompiler-project.

**Comment by sjoelund** [comment]
Non-existing options are passed to the subproject. You can set --cppruntime-flags in OpenModelica.git without it being part of OpenModelica.git. It will be automatically passed down to OMCompiler.git.

**Comment by MarcusWalther** [comment]
You are right, thank you for this information.

**Pull request closed without merging**
