### PR TITLE
Generalize use of add_array_scalar in Cpp runtime

### PR DESCRIPTION
**Pull request by rfranke**
See e.g. ModelicaTest.Fluid.TestComponents.Machines.TestWaterPump*

### CODE REVIEW

**Comment by rfranke** [comment]
I consider it a bug if a couple of models fail to compile -- most likely caused by some changes in other parts of omc and only followed up in the C runtime so far.

**Comment by adrpo** [comment]
I don't know the Cpp code very well. @AnHeuermann can you review this? 
I think these changes might needed now because of changes from @kabdelhak to not scalarize parameter arrays anymore, but I'm unsure.

**Comment by rfranke** [comment]
See the above referenced examples (TestWaterPump*). The change to the Cpp code generation is borrowed from the current C code generation.

**Comment by AnHeuermann** [comment]
Sorry, I don't know why the C runtime uses this and am not familiar with the Cpp runtime either. But when the first input of `add_array_scalar` has to be the array the changes should be finde.

**Review by adrpo — APPROVED** [review]
Seems OK!

**Pull request merged**
