### PR TITLE
Added simulation test with homotopy

### PR DESCRIPTION
**Pull request by adeas31**
Tests simulation flags `lv="LOG_NLS_V,LOG_INIT_HOMOTOPY"`

### CODE REVIEW

**Comment by adeas31** [comment]
@casella I tried to add test for homotopy logging. I used your example Modelica code that you provided in [ticket #5805](https://trac.openmodelica.org/OpenModelica/ticket/5805).

The simulation of Modelica model is terminated by assertion and it is not a good idea to add a test that check for simulation failure. Would like to contribute a model that actually works and uses homotopy logging?

**Comment by casella** [comment]
> @casella I tried to add test for homotopy logging. I used your example Modelica code that you provided in [ticket #5805](https://trac.openmodelica.org/OpenModelica/ticket/5805).
> 
> The simulation of Modelica model is terminated by assertion and it is not a good idea to add a test that check for simulation failure.

Why not? The whole point here was to get good diagnostic messages in case of failure. Logging of nonlinear solvers and homotopy solvers is pretty much useless if the initialization is successful (save, perhaps, if you want to optimize performance, e.g., the number of iterations). It is essential in case of failure.

If the testsuite has only successful cases, we will never assess how good OMC is at helping the end user deal with initialization failures, which is a big deal.

@adeas31 what do you think?

**Comment by adeas31** [comment]
The problem is that the failures are hard to test. If the simulation fails for some other reason the test will still pass.

**Comment by AnHeuermann** [comment]
For this problem we can use any model that has homotpy and finishes successfully or not?
We just add a bunch of logging and the test will tell us if the simulation stops or fails, meaning that the logging caused a problem.
If the initialization was successful or not doesn't matter for the loggin itself.

So I would say: Let's use a big model that uses as many features we are logging as possible (and still simulates though) and activate all logging flags.

**Comment by casella** [comment]
> 
> 
> The problem is that the failures are hard to test. If the simulation fails for some other reason the test will still pass.

Aren't we also checking the output log? If we turn on enough logging, we can check what actually went wrong. Do I miss something?

**Comment by adeas31** [comment]
> > The problem is that the failures are hard to test. If the simulation fails for some other reason the test will still pass.
> 
> Aren't we also checking the output log? If we turn on enough logging, we can check what actually went wrong. Do I miss something?

No we are not checking the output log. I am also not sure if its different for different platforms. I like the idea from @AnHeuermann . We can have a big model and enable all logging to see if any of the logging causes any crash. I remember we had such issues in the past that some of the logging was crashing.

**Comment by casella** [comment]
Sounds good. 

But I still think that we should also test failing models, and we should make sure that they fail "correctly", i.e. producing the right diagnostic messages. Otherwise there will hardly ever be any real progress on this front, which is crucial to improve the end-user experience.

**Pull request merged**
