### PR TITLE
Adding optional test on CentoOS6 and update 3rdParty

### PR DESCRIPTION
**Pull request by AnHeuermann**
This should solve

```bash
CMake Error at CMakeLists.txt:24 (cmake_minimum_required):
  CMake 3.4 or higher is required.  You are running version 2.8.12.2

-- Configuring incomplete, errors occurred!
make[3]: *** [/var/lib/jenkins/ws/LINUX_BUILDS/rpmbuild/BUILD/openmodelica_1.17.0~dev-126-g0d286e5/build/lib/x86_64-linux-gnu/omc/libsundials_ida.a] Error 1
make[3]: Leaving directory `/var/lib/jenkins/ws/LINUX_BUILDS/rpmbuild/BUILD/openmodelica_1.17.0~dev-126-g0d286e5/OMCompiler'
make[2]: *** [sundials] Error 2
make[2]: *** Waiting for unfinished jobs....
```
from [Jenkins nightly build](https://test.openmodelica.org/jenkins/blue/organizations/jenkins/LINUX_BUILDS/detail/LINUX_BUILDS/1119/pipeline/987).

### CODE REVIEW

**Review by sjoelund — COMMENTED** [review]
You'll need git in the image. Either use a Dockerfile agent in Jenkins to install it, or play around with the Jenkinsfile so you can perform some actions outside of the image...

**Comment by sjoelund** [comment]
Note that the RPM builds might be done slightly differently. For example, they `source /opt/rh/devtoolset-8/enable` which might set a few env.variables making things work:

https://github.com/OpenModelica/OpenModelicaBuildScripts/blob/master/rpm/SPECS/openmodelica.spec.tpl#L103
https://github.com/OpenModelica/OpenModelicaBuildScripts/blob/master/rpm/SPECS/openmodelica.spec.tpl#L142

**Comment by AnHeuermann** [comment]
But that can't be the reason that the C++ runtime isn't compiling. It explicit wants CMake version greater then 3. I think because they need specific boost features from boost 1.60.
After some trying I couldn't find a good solution to change this so I will leave it as it was.

Is the C++ runtime even build on el6 in the nightly builds? If I read https://github.com/OpenModelica/OpenModelicaBuildScripts/blob/master/rpm/SPECS/openmodelica.spec.tpl#L145 correctly, it's not.
I will disable it for now. The test for CentOS6 itself is nearly working. Of course the sanity check for C++ is not working since it's not build. So I'll disable that test for CentOS6 as well.

**Comment by sjoelund** [comment]
> Is the C++ runtime even build on el6 in the nightly builds?

No. The configure script does not contain `--with-cppruntime` so it's not built. I guess the Jenkinsfile calls `make cppruntime` explicitly and ignores that?

**Comment by AnHeuermann** [comment]
In Jenkins we configure with `--with-cppruntime`. I added a boolean to `common.buildOMC()` to turn this on or off.

**Comment by AnHeuermann** [comment]
Should solve https://test.openmodelica.org/jenkins/blue/organizations/jenkins/LINUX_BUILDS/detail/LINUX_BUILDS/1120/pipeline/978 as well. I tested in a docker image but it isn't tested here.

**Comment by AnHeuermann** [comment]
Still not all problems are solved: https://test.openmodelica.org/jenkins/blue/organizations/jenkins/LINUX_BUILDS/detail/LINUX_BUILDS/1121/pipeline

So I'll need to check the Makefiles again.

**Comment by adrpo** [comment]
The el8 is just a glitch, on rerun it works fine again.

For the Xenial ones:
`/var/lib/jenkins/ws/LINUX_BUILDS/tmp.build/openmodelica-1.17.0~dev-141-g62d8844/build/lib/x86_64-linux-gnu/omc/libsundials_ida.a`
Note that you have an extra "/omc/" at the end, but if you look above it is installed in:

```
Install IDA
-- Installing: /var/lib/jenkins/ws/LINUX_BUILDS/tmp.build/openmodelica-1.17.0~dev-141-g62d8844/OMCompiler/3rdParty/sundials-5.4.0/build/lib/x86_64-linux-gnu/libsundials_ida.a
```

**Comment by sjoelund** [comment]
I had started a bit of work on #6933. Seems there's a little to go to fix it :)

**Pull request merged**
