### PR TITLE
[Cpp] Handle OMHOME with spaces in path

### PR DESCRIPTION
**Pull request by AnHeuermann**
First fix for ticket [#6004](https://trac.openmodelica.org/OpenModelica/ticket/6004).
Test should be added as well, see [#6005](https://trac.openmodelica.org/OpenModelica/ticket/6005).

### CODE REVIEW

**Comment by AnHeuermann** [comment]
@adrpo Any idea how to add a test for install location with spaces?

**Comment by adrpo** [comment]
I guess we could do it as part of the sanity test, see here:
https://github.com/OpenModelica/OpenModelica/blob/master/.CI/common.groovy#L176
You also need to add MINGW label to this PR :)

**Comment by adrpo** [comment]
We could just do mklink /J PathWithSpaces C:\path\with\no\spaces\OpenModelica\build. And then try to build stuff with an omc from PathWithSpace. Then delete the mklink junction.

**Comment by adrpo** [comment]
We should make it more challenging and add also special characters ăîșțâåöä and so on.

**Comment by adrpo** [comment]
@AnHeuermann please make a ticket about testing this and assign me to it, I'll fix it myself as I know how to do it.

**Comment by AnHeuermann** [comment]
First we need to add a test, otherwise the CI/MINGW is testing nothing. 
But I can't change the Jenkins files, I'm not trustworthy enough.
Can you do it or is it only @sjoelund?

**Comment by adrpo** [comment]
I can change the Jenkins files, I can try to add a test. Do I have access to your repo so I can push to this PR?

**Pull request merged**
