### PR TITLE
[FMI] Reset eventInfo only on entering event mode

### PR DESCRIPTION
**Pull request by AnHeuermann**
Fix for [ticket 5367](https://trac.openmodelica.org/OpenModelica/ticket/5367).
  - `fmi2EnterEventMode` will reset `eventInfo`. Then the FMU integrator  will set `newDiscreteStatesNeeded=fmi2True`.
    Inside fmi2NewDiscreteStates value for `valuesOfContinuousStatesChanged` will stay true if it becomes true at some point.
  - `valuesOfContinuousStatesChanged` can't trigger another call to `fmi2EventUpdate` any more. Would lead to infinit loop.

### CODE REVIEW

**Comment by AnHeuermann** [comment]
I added a test that validates the results with the [FMUComplianceChecker](https://github.com/modelica-tools/FMUComplianceChecker ) for BouncingBall example.

**Comment by AnHeuermann** [comment]
@adrpo or @sjoelund Jenkins will ignore my changes to Jenkinsfile. Can one of you rebase this or move it to a branch that is allowed to change the Jenkisfile?

**Comment by AnHeuermann** [comment]
@sjoelund 
I'm not happy with the changes I did to the Jenkinsfile. All I need for my test in stage `testsuite-fmu-crosscompile` is the build omc and fmuCheck.linx64 in PATH.
Is this a minimal change to accomplish that?

**Comment by sjoelund** [comment]
I'm not sure why you needed to create an additional stage for this. It's quite expensive to install all libraries and unstash a whole omc installation for one test. Make it part of the other stage instead.

Also, the syntax of the Jenkinsfile is invalid. I gave you write access to the repository so Jenkins will trust your changes to the Jenkinsfile.

**Comment by AnHeuermann** [comment]
I validated that my test is working with the new BouncingBall test:
https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-959/13/pipeline/907#step-935-log-51
And that it it not working without fixes:
https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-959/12/pipeline#step-939-log-51

Can be merged :grinning:

**Pull request merged**
