### PR TITLE
Fix solvability detection for if expressions.

### PR DESCRIPTION
**Pull request by mahge**
- Do not detect/collect x from pre(x). They are different variables.
  - Do not use traverseExpBottomUp. Use traverseExpTopDown and stop at
    pre().

  - At some point we have to roll up our sleevs and change pre, previous,
    der, start, ... to their own specific EXP types instead of having them
    as CALL() expressions.

### CODE REVIEW

**Comment by kabdelhak** [comment]
>     * Do not detect/collect x from pre(x). They are different variables.
> 
>     * Do not use traverseExpBottomUp. Use traverseExpTopDown and stop at
>       pre().
> 
>     * At some point we have to roll up our sleevs and change pre, previous,
>       der, start, ... to their own specific EXP types instead of having them
>       as CALL() expressions.

Good that you found that!

Yes definitely, replacing the der/pre/... calls is kind of the first thing i want to change in the new backend. Those are variables and not function calls. But maybe it is doable for the current one also, we have the needed functions to do that.

**Comment by mahge** [comment]
Ya. It is unfortunate that they are not standalone expressions. We have SIZE() as its own exp but not DER() or PRE(). 🤦‍♂️. I guess the front end didn't care about them that much.

BTW try to avoid `traverseExpBottomUp `if you don't have a specific reason to use it. It is not good for this exact reason. You can not make such decisions when traversing bottom up. The exps in the call, _in this case `pre`_, are already processed when you reach the `pre `call itself. 

Use `traverseExpsTopDown `so that you can look at the top exp first and then decide if you want to go down or not.

**Comment by mahge** [comment]
> 
> 
> LGTM!
> 
> Maybe there are some checks like this somewhere else missing, but you are right we should generally replace those calls.

I wanted to the the effect of this and then will add `der()` and `delay()` to the list. They are wrong for the same reason as `pre `here

**Comment by sjoelund** [comment]
`delay()` you can't really remove because sadly it doesn't break algebraic loops. There is a debug-flag (I believe) that enforces that though.
And `der()` has sort of the opposite problem because you solve for the derivative.

**Comment by mahge** [comment]
> 
> 
> `delay()` you can't really remove because sadly it doesn't break algebraic loops. There is a debug-flag (I believe) that enforces that though.
> And `der()` has sort of the opposite problem because you solve for the derivative.

In reality the problem with der() might be rare or even non-xistent. 
I am not sure how it all works out with state selection and dummy derivatives. I guess they might be replaced from der(x) to $DER.x at some point if it is a dummy derivative. 

Otherwise, if der(x) is dummy derivative and if we have such an equation
`x = if ... then der(x)*der(x) else 0`

will be marked unsolvable (NON_LINEAR) for x. 

But this might not even happen at all. No idea.
In any case it might still be nice to explicitly stop at der(..) when looking for solvabilty of x.

**Comment by mahge** [comment]
> 
> 
> `delay()` you can't really remove because sadly it doesn't break algebraic loops. There is a debug-flag (I believe) that enforces that though.
> And `der()` has sort of the opposite problem because you solve for the derivative.

As for `dealy(x,..)`, 
yes there is a flag called DELAY_BREAK_LOOP. I am not sure what it does. My assumption was that delay is a fancy `pre`. Since the value is obtained by interpolation I thought it would not depend on x.

`x = if delay(x,1) > 0 then 1 else 0;`

will be marked unsolvable for `x` as it is right now. I don't know if such things are allowed or not.

**Comment by sjoelund** [comment]
It's not gotten by interpolation if you take very long steps. You sadly need to have the current value in order to delay. It's a bit stupid.

**Comment by mahge** [comment]
> 
> 
> It's not gotten by interpolation if you take very long steps. You sadly need to have the current value in order to delay. It's a bit stupid.

Aha. I didn't know that. Then we can skip it. Or we can decide based on the flag. As it is done for the other places delay is processed.

**Pull request merged**
