### PR TITLE
Clarify equation is for resolving rounding errors

### PR DESCRIPTION
**Pull request by AnHeuermann**
### Related Issues

I struggled to understand what
```C
delta_hh[ii] = y[ii] + delta_hh[ii] - y[ii];
```
was trying to achieve.

@phannebohm pointed me to the explanation: https://en.wikipedia.org/wiki/Numerical_differentiation#Step_size

### CODE REVIEW

**Comment by phannebohm** [comment]
Did you check whether the compiler actually keeps that computation?

**Comment by AnHeuermann** [comment]
No. We should use optimization levels `-O2` or `-Os`. But I have no idea what they are doing on different compiler toolchains. On Linux we use gcc and clang, I guess the gcc version is the one users end up with. There is a giant list for gcc alone what these optimization levels will do: https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html
I'll just assume they will keep it even it is basically `a=a`.

**Comment by phannebohm** [comment]
We should check this first, i.e. make a small program and look at the assembly. I can have a go tmrw.

**Comment by AnHeuermann** [comment]
I'm going to merge this PR. It clarifies why `delta_hh[ii] = y[ii] + delta_hh[ii] - y[ii];` is done what was the sole purpose of this PR.

If on of the used C compilers could remove this equation in some optimization stage is still an open question.
@phannebohm You can provide an additional PR to make sure the equation in question is never removed by any C compiler.

**Pull request merged**
