### PR TITLE
New balance initialization

### PR DESCRIPTION
**Pull request by kabdelhak**
### Related Issues
 - related to ticket #6200

### Purpose
 - problem: old balancing algorithm is way to convoluted and seems to make errors

### Approach
- solution: from scratch implementation with new approach:
   1. sort init vars to be matched last
   2. compute adjacency matrix
   3. inverse match (var->eq)
   4. remove unmatched equations
   5. fix unmatched vars
   6. success
 - ToDo: 
   - check removed equations for consistency
   - check fixing of unmatched vars for fixability
   - more documentation

### CODE REVIEW

**Comment by casella** [comment]
... und?

**Comment by casella** [comment]
@kabdelhak the suspence is almost unbearable 😅

Can you fix the failing model in the testsuite and get this PR through, so we can see if it magically solves all the pending failures due to structural problems at initialization?

Thanks!

**Comment by kabdelhak** [comment]
> @kabdelhak the suspence is almost unbearable sweat_smile
> 
> Can you fix the failing model in the testsuite and get this PR through, so we can see if it magically solves all the pending failures due to structural problems at initialization?
> 
> Thanks!

Sorry! Currently very occupied with other stuff. 

It seems like i need to think a little more about this approach, the difference in ordering my stuff does seems to easily break stuff. I have to figure out if simcode expects a certain ordering of variables and equations, because it is very fragile to changing that.

I was able to figure out why the model fails or at least how to conceptually fix it, but that requires re-ordering stuff. That made a whole lot of other things break, which i have to look into. Does not seem like it will be fixed in the next few days.

**Comment by casella** [comment]
No problem, take your time. It seemed to me it was basically done already.

For project management purposes it would be nice if you could drop a few lines on the ticket explaining what the situation is, so I don't need to bug you :)

**Comment by casella** [comment]
Ouch. Setup fails while running:
```
docker pull docker.openmodelica.org/build-deps:v1.16-qt4-xenial— Shell Script
```
@adrpo, what can possibly go wrong with such an old release?

**Comment by sjoelund** [comment]
> Ouch. Setup fails while running:
> 
> ```
> docker pull docker.openmodelica.org/build-deps:v1.16-qt4-xenial— Shell Script
> ```
> 
> @adrpo, what can possibly go wrong with such an old release?

The servers are getting new IP addresses and rebooting

**Comment by kabdelhak** [comment]
> Argh, still two tests failing... sweat_smile

I don't really know what's happening, locally everything is fine. Looking at the logs shows that there is very marginal differences in values. I guess comparing the outcome of LOG_IPOPT istn't a good idea.

**Comment by perost** [comment]
> yes. Although i tested #6199 only for the later mentioned model `Buildings.Fluid.HeatExchangers.DXCoils.AirCooled.Examples.SingleSpeed` and not the original one `Buildings.Experimental.DistrictHeatingCooling.Plants.Validation.Plant_Carnot_T_ClosedLoop` because i could not find the latter one, has it been moved in the latest buildings version?

Seems it's Buildings.Obsolete.DistrictHeatingCooling.Plants.Validation.Plant_Carnot_T_ClosedLoop in the latest Buildings version, so I guess it's not a very important model given that it went from Experimental to Obsolete.

**Comment by kabdelhak** [comment]
> Seems it's Buildings.Obsolete.DistrictHeatingCooling.Plants.Validation.Plant_Carnot_T_ClosedLoop in the latest Buildings version, so I guess it's not a very important model given that it went from Experimental to Obsolete.

Thanks! I still tested it just to see if it works - and it does! yay :)

**Pull request merged**
