### PR TITLE
Replaceable Redeclare Support

### PR DESCRIPTION
**Pull request by adrpo**
- still a bit of work in to do but if it passes the testsuite we can merge it and continue from there
- activate replaceable support via a setting flags in OMEdit->Tools->General->Bottom (not on by default)
- use the get*Element* instead of get*Component* API functions
- fix bactrace.c/h (no QT_NO_DEBUG flag will ever get to that as is a C file)
- add -g back when we build on Windows (more meaningful traces)

### CODE REVIEW

**Comment by casella** [comment]
Could we just skip the MacOS thing for the time being and get the PR in? That could be fixed later.

**Comment by adrpo** [comment]
@casella i got some time now to look into it, if it takes more than an hour I'll remove the MACOS label and then we can merge it.

**Comment by casella** [comment]
`Mac doesn't know cp -u, remove that`

Boy, what an ordeal 😄 

I hope it now finally works...

**Comment by casella** [comment]
Mac test passed 👍

**Comment by casella** [comment]
Something's wrong in OMEdit tests...

**Comment by casella** [comment]
MacOS [broken again](https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-943/4/pipeline/41)?

**Comment by adrpo** [comment]
@casella yes, I did this fix wrong, I'm trying again.

**Comment by casella** [comment]
🚀 💐 🍰 !

@adrpo can you merge and start a nightly build for Windows and Linux?

**Comment by casella** [comment]
🍷 🍾 🥳

**Pull request merged**
