### PR TITLE
Annotation completion

### PR DESCRIPTION
**Pull request by adeas31**
See https://github.com/OpenModelica/OMEdit/pull/219 for comments and details.

### CODE REVIEW

**Comment by atrosinenko** [comment]
> Use `ComponentInfo::getParameterValue`

The signature of this function seems quite suspicious to me... This function receives a `className`, then loads something and sets a flag that everything is loaded (not depending on the `className`) and this function is `public`.

 I will not work on this PR until the weekend, but just to shorten the round-trip: do I get it right, the `className` is expected to be identical on every invocation with this object as `this`?

**Comment by atrosinenko** [comment]
@adeas31 Meanwhile, looks like now this PR belongs to **your** fork of `OpenModelica` repo. Maybe, it would be better for you to move the forgotten autocompletion icon to the proper directory and merge it on your own, and then I open new PR.

**Comment by adeas31** [comment]
You can add my repo as git remote and can work on the branch used in this PR.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-04-08_12-18-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6649/console).

**Pull request closed without merging**
