### PR TITLE
link sundials statically on mingw in cvode_solver.h

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

**Comment by mahge** [comment]
@adrpo I think it is better if we define this from the compile commands i.e. Windows Makefiles. People can include sundials headers in other places (or before the defines) and this leads to confusing issues where some files compile fine while others report undefined imported functions. This is exactly what happened with @AnHeuermann on upgrading Sundials and now with @arun3688 (I think.)
Plus it allows us to configure things easier, e.g., if we want to link to shared cvode for some reason.

We should also move other definitions that affect other headers like these to the compile commands whenever we can.

**Comment by adrpo** [comment]
@mahge: we need to clean this up quite a bit. I want to do it after the 1.16 release, basically use the same makefiles for MinGW and Linux, including configure. I think having a global omc_config.h that we include everywhere would help a lot with easier to understand configuration.

**Comment by mahge** [comment]
@adrpo Ya there is a lot to fix there. Same configuration
- Header file locations (e.g `openmodelica*.h` headers in `simrt/c/` should probably go in `OMCompiler`)
- Include paths should be cleaned. `-Ic/meta -Ic/util` .. removed and just include from `c/`)
- Maybe sort out what goes where in `Compiler/runtime` vs `simrt/c`. Maybe have a common runtime at `OMCompiler` level
- Clearly specify which libraries we build as static and which as dynamic. 
....

Maybe we can create a ticket to list out what we should/not do and try to do it step by step once 1.16 is done.

**Comment by sjoelund** [comment]
For the C runtime, the FMI headers don't need `-I...` - those includes were changed to be relative:
```
OMCompiler/SimulationRuntime/c/util/omc_error.h:#include "../openmodelica.h"
```

It's only needed for some of the simulation runtime files because I got bored of fixing everything

**Pull request merged**
