### PR TITLE
GBODE documentation added in the user guide

### PR DESCRIPTION
**Pull request by bernhardbachmann**
### Related Issues

#9372

### Purpose

Documentation in the user guide

### CODE REVIEW

**Comment by casella** [comment]
Gosh, @adrpo, why is this failing because of OMSimulator?

**Review by casella — APPROVED** [review]
Looks very good to me! I'm no sure why the CI has issues with it...

**Comment by casella** [comment]
For the record, I just read the diff, I'm not 100% sure that the RST will render correctly, we can double-check once it's merged in.

**Comment by perost** [comment]
> Looks very good to me! I'm no sure why the CI has issues with it...

Seems the CMake build is still broken. I added the label to skip it, but @bernhardbachmann will have to push a new commit to rerun the CI stuff.

**Comment by casella** [comment]
@bernhardbachmann do you want @AnHeuermann to look at this before pushing it in, or should I just go ahead?

**Review by AnHeuermann — APPROVED** [review]

**Pull request merged**
