### PR TITLE
Read input file relative to inputPath

### PR DESCRIPTION
**Pull request by AnHeuermann**
Fix for ticket #6035

### CODE REVIEW

**Comment by AnHeuermann** [comment]
@adeas31 Can you validate if the problem described in #6035 is fixed with this?
I can't build OMEdit at the moment...

**Comment by adeas31** [comment]
See my comment on [#6035](https://trac.openmodelica.org/OpenModelica/ticket/6035). I think this PR is not needed. Basically before simulating the model this particular inputPath is not available. When the user simulates the model then OMEdit generates this path so its not an ideal way to read from this path for user input files. For user input files use the working directory of OMEdit.

**Comment by casella** [comment]
See discussion in https://trac.openmodelica.org/OpenModelica/ticket/6035#comment:7

**Comment by casella** [comment]
@AnHeuermann, let's see how the discussion evolves in the ticket. In case this PR is merged,  I would recommend to add a short note to the [-iff flag documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-iif) that relative paths start from the directory specified by `-inputPath`, or from the working directory by default.

**Pull request merged**
