### PR TITLE
[NB] Fix differentiation of builtin functions

### PR DESCRIPTION
**Pull request by phannebohm**

### CODE REVIEW

**Comment by phannebohm** [comment]
This hopefully fixes some regressions from [this report](https://libraries.openmodelica.org/branches/history/newInst-newBackend/2024-07-24%2013:32:29..2024-07-26%2010:59:22.html).

**Comment by casella** [comment]
Unfortunately not many, see [report](https://libraries.openmodelica.org/branches/history/master/2024-07-26%2016:35:11..2024-07-26%2022:32:18.html).

**Comment by phannebohm** [comment]
Well, not for the OB but definitely for the NB, see [this report](https://libraries.openmodelica.org/branches/history/newInst-newBackend/2024-07-26%2010:59:22..2024-07-30%2003:25:33.html).

**Comment by casella** [comment]
Of course, sorry 😄

**Comment by phannebohm** [comment]
The NB still doesn't properly remove `$OMC$inStreamDiv` calls, so some models are stuck at Template phase. But that should be easy to fix, I'll do that when I'm back from vacation. :+1:

**Comment by phannebohm** [comment]
Should be fixed in #12785.

**Pull request merged**
