### PR TITLE
[BE] reactivate resolveLoops/reshuffleLoops

### PR DESCRIPTION
**Pull request by kabdelhak**
- should be fixed in ASSC but this resolves it for now

### Related Issues

 - ticket #5817

### Purpose

 - converts uncaught analytical singularities

### Approach

- use old reshuffle loops algorithm

### CODE REVIEW

**Comment by casella** [comment]
@kabdelhak did you make any progress with the tests?

**Comment by kabdelhak** [comment]
Seems like everything can be resolved but `Modelica.Electrical.Machines.Examples.AsynchronousInductionMachines.AIMC_DOL.mos` from MSL 3.2. 

Attached you can see the difference in the result file. To me it just looks like different noise, but i cannot really judge. The red version is the new one (with reshuffle loops) and the blue one is ASSC only. Should i just update the reference file?
[OMPlot.pdf](https://github.com/OpenModelica/OpenModelica/files/6530821/OMPlot.pdf)

**Comment by casella** [comment]
It's definitely noise, and it's perfectly justified since there is some approximation in the time integration of the state variables. If you tighten the tolerance, the amplitude will go down.

We have already discussed within MAP-LIB to remove those variables from the reference files, see [#3476](https://github.com/modelica/ModelicaStandardLibrary/issues/3476).

Please go ahead with the PR. Only, it's not clear to me what do you mean by "update the reference file". We should use the official ones from the MA, and fight until we can actually have good ones, rather than silently fix them in the background.

**Comment by kabdelhak** [comment]
> Please go ahead with the PR. Only, it's not clear to me what do you mean by "update the reference file". We should use the official ones from the MA, and fight until we can actually have good ones, rather than silently fix them in the background.

Jenkins rejects my changes if i do not change the reference file or remove this variable from being tested because these differences are interpreted as more than just noise by our diff algorithm. Would it be okay to remove the check for this variable? As far as i know i unfortunately cannot change the tolerance.

**Comment by casella** [comment]
> Jenkins rejects my changes

What a nasty fella :)

> if i do not change the reference file or remove this variable from being tested because these differences are interpreted as more than just noise by our diff algorithm. Would it be okay to remove the check for this variable?

For the time being, definitely. This fall I'll try to address this issue more systematically within the MAP-LIB group.

**Comment by sjoelund** [comment]
Check with @lochel if 04d00c8efdb4c583fc507d1aebac2805798ee383 was generated using Dymola or OMC. The commit message doesn't say, but a lot of the files are generated by OMC

**Comment by kabdelhak** [comment]
> Check with @lochel if [04d00c8](https://github.com/OpenModelica/OpenModelica/commit/04d00c8efdb4c583fc507d1aebac2805798ee383) was generated using Dymola or OMC. The commit message doesn't say, but a lot of the files are generated by OMC

Lennart thinks it might be generated with OMC but he is not quite sure. I removed the check for the variable, if there is no problem with this, it can be pushed.

**Comment by casella** [comment]
> Check with @lochel if [04d00c8](https://github.com/OpenModelica/OpenModelica/commit/04d00c8efdb4c583fc507d1aebac2805798ee383) was generated using Dymola or OMC. The commit message doesn't say, but a lot of the files are generated by OMC

Of course we can generate the reference file ourselves and then claim that OMC has a verification success rate of 100%. It's not particularly fair, but in fact it is what Dymola does, since the reference files for MSL are generated with Dymola.

For the time being this is ok, until we properly fix the reference file generation process within MAP-LIB

**Comment by casella** [comment]
>  I removed the check for the variable, if there is no problem with this, it can be pushed.

For our internal testsuite, the one that Jenkins uses to decide that a PR is valid, this is definitely ok. That variable is the noisy result of subtracting much largere variable that sum to zero, so there's no hope to reproduce it correctly.

What I was referring to was the verification results of the library testsuite, which is another story.

**Comment by lochel** [comment]
@casella yes, I agree. But as you stated yourself: there is no point in reproducing Dymola results. I think only analytical results would actually make sense to compare in the library tests. In fact, that is how I generated the reference files for the PNlib.

**Comment by casella** [comment]
> @casella yes, I agree. But as you stated yourself: there is no point in reproducing Dymola results. I think only analytical results would actually make sense to compare in the library tests. In fact, that is how I generated the reference files for the PNlib.

That would be nice in principle. In practice, most realistic physical models have no analytical results, and since people do use Modelica tools to simulate realistic models, not toy models, we also need to test how tools handle them.

I think a reasonable compromise is to try to obtain numerical solutions which are as precise as possible. Assuming that the model equations respect the Cauchy condition, are smooth enough, and are not chaotic, there are theoretical guarantees that numerical solutions asymptotically appoximate the exact ones. 

In the old days, the Dymola reference results were obtained with 1e-4 precision, which was clearly not good enough - the proof was that many discrepancies among tools were resolved if tighter tolerances were taken. So, we settled on 1e-6 tolerance. Although this is good enough for most practical situations, the solutions you obtain are still far enough from the exact one to create problems with verification in some cases. The problem is that different tools will have different approximations, which may legitimately be different, precisely because they are approximations. We should use much tighter tolerances for cross checking.

**Comment by lochel** [comment]
I don't think we should use simulation results from any tool as reference. We can use those to assist generating reference files. But I think experts have to create reference signals, without numerical noise or artifacts in them.

**Comment by lochel** [comment]
This is the wrong place for this discussion... Sorry for that. Should we move it?

**Comment by casella** [comment]
Sure, but my plan is to start working on this seriously from September. There will be a MA task force working on these topics, are you intrerested to join?

**Comment by lochel** [comment]
Yes, I want to contribute. Count me in 👍

**Pull request merged**
