### PR TITLE
Change sundials install directory.

### PR DESCRIPTION
**Pull request by mahge**
- Sundials will be installed in `<install_dir>/include/omc` instead of
    `<install_dir>/include/omc/c` Note the c.

  - More libraries should be fixed like this. Ipopt is already done some
    time ago.
    Figured that now is as good a time as any to fix sundials.

### CODE REVIEW

**Comment by sjoelund** [comment]
Remember to fix install paths in: https://github.com/OpenModelica/OpenModelicaBuildScripts/tree/master/debian

**Comment by mahge** [comment]
@sjoelund This only affects the installation of the header files. It does not change the library installations. I will check if they are needed to be updated in the debian build scripts but my guess is they do not.

**Comment by sjoelund** [comment]
I did check and they are installed in omc-common: https://github.com/OpenModelica/OpenModelicaBuildScripts/blob/master/debian/omc-common.install

If any runtime headers need them, they need to be there. Otherwise, they should not be in the include-files. But I believe people want to include them in co-simulation source-code FMUs, so they probably belong somewhere.

**Comment by mahge** [comment]
I suspect most, if not all, of them are there only for source code FMUs. But I can not start filtering them out now. For now I am just trying to move them to a more appropriate place. 

The `fmil` headers have been in `include/omc` for some time and we have not had any problems so far. However, I can update them in the build scripts if needed. No problem.

**Comment by mahge** [comment]
Added here https://github.com/OpenModelica/OpenModelicaBuildScripts/pull/17

**Pull request merged**
