### PR TITLE
fix ticket:5663, handle '%%' in text annotation

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

**Comment by adeas31** [comment]
@adrpo should I squash and merge it?

**Comment by adrpo** [comment]
Maybe it would be better to do this:
https://github.com/OpenModelica/OpenModelica/blob/a60e910233292aa4aee66d1b46d2f5a5200c0bdb/OMEdit/OMEdit/OMEditGUI/Annotations/TextAnnotation.cpp#L616
Change this line to compare and move it to 611?

**Comment by adeas31** [comment]
We can probably move it to 611 but can't change it to compare. You could have something like `%name is %%`.

**Comment by adeas31** [comment]
And also you can't move it before `updateTextStringHelper` because then it is changed to `%` and `updateTextStringHelper` will eat it.

**Comment by adrpo** [comment]
Eh, never mind, you can just use your solution, seems fine.

**Pull request merged**
