### PR TITLE
Disable module evaluateParameters

### PR DESCRIPTION
**Pull request by lochel**

### CODE REVIEW

**Comment by lochel** [comment]
@perost Does the new frontend evaluate all the parameters that need to be evaluated?

**Comment by lochel** [comment]
@OpenModelica/developers Should protected parameters be evaluated?

**Comment by perost** [comment]
> @perost Does the new frontend evaluate all the parameters that need to be evaluated?

That very much depends on your definition of "need to be evaluated". It evaluates all parameters that are needed for determining types, i.e. "structural" parameters, and also some additional cases to keep the backend happy.

**Comment by lochel** [comment]
So should  `b1` be detected and evaluated in the frontend:

```Modelica
  parameter Boolean b1 = true;
  parameter Real f = if b1 then g else 2.0;
  parameter Real g = if b1 then 2.0 else f;
```

**Comment by perost** [comment]
> So should `b1` be detected and evaluated in the frontend:
> 
> ```modelica
>   parameter Boolean b1 = true;
>   parameter Real f = if b1 then g else 2.0;
>   parameter Real g = if b1 then 2.0 else f;
> ```

The NF will try to evaluate the condition in the if-expression if the branches have different types (because some libraries depend on that), i.e. if the type of the if-expression can't be determined it will try to do branch selection.

**Comment by lochel** [comment]
This isn't detected by the new frontend:

```
  parameter Real f = g;
  parameter Real g = f;
```

**Comment by perost** [comment]
> This isn't detected by the new frontend:
> 
> ```
>   parameter Real f = g;
>   parameter Real g = f;
> ```

I know, I haven't implemented that check yet since it's not really vital. It's important of course, but the main priority has been to make valid models work.

**Comment by kabdelhak** [comment]
> I know, I haven't implemented that check yet since it's not really vital. It's important of course, but the main priority has been to make valid models work.

Sure, but this is required to detect dependencies which are seemingly cyclic. 

> The NF will try to evaluate the condition in the if-expression if the branches have different types (because some libraries depend on that), i.e. if the type of the if-expression can't be determined it will try to do branch selection.

This is only true for equations but not for parameter bindings, as mentioned above. You don't check them in the first place.

**Comment by perost** [comment]
> > The NF will try to evaluate the condition in the if-expression if the branches have different types (because some libraries depend on that), i.e. if the type of the if-expression can't be determined it will try to do branch selection.
> 
> This is only true for equations but not for parameter bindings, as mentioned above. You don't check them in the first place.

What do you mean? Of course the NF type checks parameter bindings, it just doesn't check if they are cyclically dependent or not.

**Comment by kabdelhak** [comment]
> > > The NF will try to evaluate the condition in the if-expression if the branches have different types (because some libraries depend on that), i.e. if the type of the if-expression can't be determined it will try to do branch selection.
> > 
> > 
> > This is only true for equations but not for parameter bindings, as mentioned above. You don't check them in the first place.
> 
> What do you mean? Of course the NF type checks parameter bindings, it just doesn't check if they are cyclically dependent or not.

Yes i meant checking for cyclic dependencies, this is vital for the backend to evaluate those bindings. Could it be possible to fully evaluate it in the frontend? I guess this would make some backend modules superfluous (which are partly replaced by the new frontend anyways).

**Comment by perost** [comment]
>Could it be possible to fully evaluate it in the frontend? I guess this would make some backend modules superfluous (which are partly replaced by the new frontend anyways).

Possibly, but it depends on what knowledge is needed to determine whether a parameter should be evaluated or not. The backend has more knowledge about the model as a whole than the frontend, so it might be difficult for the frontend to apply the same rules. But it's certainly something that can be discussed.

**Comment by kabdelhak** [comment]
> > Could it be possible to fully evaluate it in the frontend? I guess this would make some backend modules superfluous (which are partly replaced by the new frontend anyways).
> 
> Possibly, but it depends on what knowledge is needed to determine whether a parameter should be evaluated or not. The backend has more knowledge about the model as a whole than the frontend, so it might be difficult for the frontend to apply the same rules. But it's certainly something that can be discussed.

Okay, that would be the optimal solution. The minimal thing that is needed is that `b1` has to get `final= true`, that is what the old frontend does and `evaluateParameters` in combination with `simplifyIfEquations` takes care of it. But those models are mostly useless right now and it would ne great to get rid of them or at least thin them out ( i guess some form of simplification for if equations has to stay).

**Comment by perost** [comment]
> > > Could it be possible to fully evaluate it in the frontend? I guess this would make some backend modules superfluous (which are partly replaced by the new frontend anyways).
> > 
> > 
> > Possibly, but it depends on what knowledge is needed to determine whether a parameter should be evaluated or not. The backend has more knowledge about the model as a whole than the frontend, so it might be difficult for the frontend to apply the same rules. But it's certainly something that can be discussed.
> 
> Okay, that would be the optimal solution. The minimal thing that is needed is that `b1` has to get `final= true`, that is what the old frontend does and `evaluateParameters` in combination with `simplifyIfEquations` takes care of it. But those models are mostly useless right now and it would ne great to get rid of them or at least thin them out ( i guess some form of simplification for if equations has to stay).

If I understand correctly this means that the backend can't handle if-expressions in bindings, and either the frontend or the backend needs to do branch selection? That's certainly something the frontend can do, it would actually be easier than what it does now.

The issue right now is the array modifiers issue that I've been struggling with for a while, evaluating more things in the NF would expose that issue even more. But once I've fixed that issue I can look into evaluating if-expressions more. If this is what you require you can open a ticket about it, to make sure it's not forgotten.

**Comment by kabdelhak** [comment]
> > > > Could it be possible to fully evaluate it in the frontend? I guess this would make some backend modules superfluous (which are partly replaced by the new frontend anyways).
> > > 
> > > 
> > > Possibly, but it depends on what knowledge is needed to determine whether a parameter should be evaluated or not. The backend has more knowledge about the model as a whole than the frontend, so it might be difficult for the frontend to apply the same rules. But it's certainly something that can be discussed.
> > 
> > 
> > Okay, that would be the optimal solution. The minimal thing that is needed is that `b1` has to get `final= true`, that is what the old frontend does and `evaluateParameters` in combination with `simplifyIfEquations` takes care of it. But those models are mostly useless right now and it would ne great to get rid of them or at least thin them out ( i guess some form of simplification for if equations has to stay).
> 
> If I understand correctly this means that the backend can't handle if-expressions in bindings, and either the frontend or the backend needs to do branch selection? That's certainly something the frontend can do, it would actually be easier than what it does now.
> 
> The issue right now is the array modifiers issue that I've been struggling with for a while, evaluating more things in the NF would expose that issue even more. But once I've fixed that issue I can look into evaluating if-expressions more. If this is what you require you can open a ticket about it, to make sure it's not forgotten.

The backend can handle if expressions in bindings if they are not circular. Otherwise they will just be put into the initial system and processed correctly. But resolving as much as possible in the frontend (structural parameters etc.) would be best. 

There is another question still open: Should protected parameters be evaluated? There is no way to change them after compilation and that seems to be different from OF to NF.

**Comment by casella** [comment]
See also discussion in [ticket:5390](https://trac.openmodelica.org/OpenModelica/ticket/5390)

**Comment by casella** [comment]
More comments in [ticket:5170#comment:16](https://trac.openmodelica.org/OpenModelica/ticket/5170#comment:16)

@lochel, I assume this PR only has testing purposes, and you have no intention of actually disabling `evaluateParameters` on master, right?

**Comment by lochel** [comment]
Yes, this was just for testing purpose.

**Pull request closed without merging**
