### PR TITLE
Highlight the active LibraryTreeItem

### LINKED ISSUE #7104: Highlighting the active tab in the Libraries' browser
### Description
I usually have several models with the same components or system name open. It woul dmake it easier to see which model I am editing if the active tab is highlighted in the libraries' browser.

image

### Version and OS
- OMCompiler v1.17.0-dev.354+g9220249be4
- OMSimulator v2.0.0.post281-g1ce5796-linux
- OS: WSL - Ubuntu 20.04

### PR DESCRIPTION
**Pull request by adeas31**
Fixes #7104

### CODE REVIEW

**Comment by adeas31** [comment]
image

As discussed in #7104, I have not made it to scroll automatically instead I added a button in `Libraries Browser` that says `Scroll to active`. Another solution would be to have a setting for `Libraries Browser` that says e.g., `Synchronize with Model Widget` which could be used to enable/disable the automatic scrolling to active item.

@casella @max-privato @dietmarw what do you guys think?

**Comment by dietmarw** [comment]
First of all, are OM tickets now here on GitHub? I still see trac.openmodelica.org up and running. So I'm slightly confused....

As for the button. Is that a per use option or do you mean it should be like a settings button but more present?

I think the focus follows active model such a natural and expected behaviour that I'd say it should not need a special button but should be on by default and can be deselected in the options if one wishes so.
Also might be a good idea asking @lochel since he brought it up originally.

**Comment by adeas31** [comment]
> First of all, are OM tickets now here on GitHub? I still see trac.openmodelica.org up and running. So I'm slightly confused....

Yes, you can use Github from now on. The trac.openmodelica.org will be off soon.

> 
> As for the button. Is that a per use option or do you mean it should be like a settings button but more present?

For now I implemented it as button (as shown in the image above) which is always shown and allows user to scroll to active model.

> 
> I think the focus follows active model such a natural and expected behaviour that I'd say it should not need a special button but should be on by default and can be deselected in the options if one wishes so.

I personally don't like that focus follows the active model. But I m in favor of making it a default on which can be disabled via options and in that case we don't need a button in the `Libraries Browser`.

> Also might be a good idea asking @lochel since he brought it up originally.

**Comment by casella** [comment]
> > First of all, are OM tickets now here on GitHub? I still see trac.openmodelica.org up and running. So I'm slightly confused....
> 
> Yes, you can use Github from now on. The trac.openmodelica.org will be off soon.

To be honest, I'm still using trac for project management until @adrpo manages to migrate the old tickets on GitHub. No big deal, but I'd stick to trac until that is done.

**Comment by dietmarw** [comment]
Though slightly off topic but still let me get this straight. OM is currently running two issue trackers which are not synchronised and each only containing part of the tickets? What could possible go wrong :-1:

**Comment by lochel** [comment]
We are running two systems which actually are synchronized. All ticket numbers map 1:1 between Trac and github. We will migrate all the content asap. However, we are soon running out of dummy issues that we reserved in order to map everything straight.

**Comment by dietmarw** [comment]
Does not look like it: https://trac.openmodelica.org/OpenModelica/ticket/7112

**Comment by adeas31** [comment]
Its the other way around. Trac tickets are mapped to github issues. For example the latest one from trac https://trac.openmodelica.org/OpenModelica/ticket/6350 can be found on github https://github.com/OpenModelica/OpenModelica/issues/6350.

**Comment by dietmarw** [comment]
So as long as changes are not synced bad to Trac then basically GitHub should be a read only mirror. Because now you have to check two places. This is a less than ideal situation and **very** confusing and not helping the project.

**Review by lochel — COMMENTED** [review]
I tested the button and it works really well - both for Modelica classes and OMSimulator models.

#### Comment 1 (appearance of the button itself)
I don't like the positioning of the button. I think it should be smaller and probably just have an icon instead of text to make it less dominant. In addition I would like to have another button that collapses all elements in the tree view. This makes it even more important to make the button smaller to not overload the libraries browser with buttons.

#### Comment 2 (behavior/settings)
And then we could add an option in the settings to change the behavior of the button between enable/disable synchronization (toggle button) and jumping to active element as implemented right now.

#### Comment 3 (highlighting style)
The highlight isn't very obvious for the selected element. Maybe changing the border color to red or fading the blue background color for the active element would help.

image

**Review by lochel — COMMENTED** [review]
#### Comment 1 (appearance of the button itself)
> I don't like the positioning of the button. I think it should be smaller and probably just have an icon instead of text to make it less dominant. In addition I would like to have another button that collapses all elements in the tree view. This makes it even more important to make the button smaller to not overload the libraries browser with buttons.

The button looks nice. 👍 

#### Comment 2 (behavior/settings)
> And then we could add an option in the settings to change the behavior of the button between enable/disable synchronization (toggle button) and jumping to active element as implemented right now.

The button shouldn't be visible at all if disabled in the settings.
Or - what I would prefer - make the button to toggle between synchronized/not synchronized and use the option in the settings to change it's behavior to "jump-to-active-item".

#### Comment 3 (highlighting style)
> The highlight isn't very obvious for the selected element. Maybe changing the border color to red or fading the blue background color for the active element would help.

The dark green is still difficult to see. I tested it locally with red which makes it easier to spot. But maybe you rather want to change the blue box to a lighter color and keep the green for aesthetic reasons?

image

Edit: Or can you increase the line thickness of the frame?

**Comment by adeas31** [comment]
> #### Comment 1 (appearance of the button itself)
> > I don't like the positioning of the button. I think it should be smaller and probably just have an icon instead of text to make it less dominant. In addition I would like to have another button that collapses all elements in the tree view. This makes it even more important to make the button smaller to not overload the libraries browser with buttons.
> 
> The button looks nice. 👍
> 
> #### Comment 2 (behavior/settings)
> > And then we could add an option in the settings to change the behavior of the button between enable/disable synchronization (toggle button) and jumping to active element as implemented right now.
> 
> The button shouldn't be visible at all if disabled in the settings.

That is possible.

> Or - what I would prefer - make the button to toggle between synchronized/not synchronized and use the option in the settings to change it's behavior to "jump-to-active-item".

I didn't understand this.

> 
> #### Comment 3 (highlighting style)
> > The highlight isn't very obvious for the selected element. Maybe changing the border color to red or fading the blue background color for the active element would help.
> 
> The dark green is still difficult to see. I tested it locally with red which makes it easier to spot. But maybe you rather want to change the blue box to a lighter color and keep the green for aesthetic reasons?

The red is used for unsaved models so its not a good choice. Changing the default blue color is possible but I would not suggest that as it requires changing the Qt's default functionality. https://doc.qt.io/qt-5/qpalette.html#ColorRole-enum see `QPalette::Highlight` option.

> 
> image
> 
> Edit: Or can you increase the line thickness of the frame?

**Review by lochel — APPROVED** [review]
Nice! ❤️

**Comment by adeas31** [comment]
@sjoelund can you please test this on Linux?

**Comment by perost** [comment]
Here's how it looks for me on Linux. I guess the look depends on what theme is used though.
screen1
screen2

**Review by lochel — APPROVED** [review]
fine with me

image

**Pull request merged**
