### PR TITLE
[FE] update unboxing for metamodelica

### PR DESCRIPTION
**Pull request by kabdelhak**
- add support of unboxing in array subscripts that are qualified crefs

### CODE REVIEW

**Review by mahge — APPROVED** [review]
LGTM.

**Review by mahge — CHANGES_REQUESTED** [review]
The error message is missing.

**Comment by kabdelhak** [comment]
> The error message is missing.

Yes this PR is not finished yet, i just wanted to push everything and separate it from the NB branch.

I also still want to merge the two cases or at least make a function for the stuff that is equal for both cases.

**Review by mahge — APPROVED** [review]

**Comment by kabdelhak** [comment]
I closed this by mistake, new PR: #8519

**Pull request closed without merging**
