### PR TITLE
[OMSICpp] new branch with all the changes that were reverted, re-applied

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

**Comment by adrpo** [comment]
@niklwors, @AnHeuermann, i based this one on master and re-applied the commits from the previous branch, hopefully the merging will now work fine.

**Comment by adrpo** [comment]
https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-273/2/pipeline/39
CMake Error at solver/CMakeLists.txt:67 (MESSAGE):
  Could not determine sundials version

Mac seems to have issues, @AnHeuermann you had a fix for this, no? maybe you can integrate it in here as well.

**Comment by sjoelund** [comment]
It has that copy-pasted line `FIND_PATH(SUNDIALS_CONFIG_FILE "sundials_config.h" ${SUNDIALS_INCLUDE_DIR} "${SUNDIALS_INCLUDE_DIR}/sundials")` which is broken and fixed in the current cpp directory... By not using `FIND_PATH`, which doesn't seem to work properly (finding the system sundials instead of our version).

**Comment by lochel** [comment]
@adrpo Is this obsolete?

**Comment by adrpo** [comment]
Already merged via another branch.

**Pull request closed without merging**
