### PR TITLE
[OSX] Fix dylib and binaries for relative paths

### PR DESCRIPTION
**Pull request by AnHeuermann**
Fixed Sundails dylibs for OSX build.

### CODE REVIEW

**Comment by AnHeuermann** [comment]
Well all the stuff for OMCpp is still not correct.
@niklwors Can you point me to the locations where those are build? They seem to be build with some templates.
Then I can add the matching `change_install_name` fun as well.


```bash
omodmac:OpenModelica andreas$ ( find build/ -name "*.dylib" -exec otool -L {} ";" | tr -d "\t" | grep -v : | grep -v "^[/@]" )
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppMath.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppMath.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSystemBase.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSimulationSettings.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppFMU.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppIDA.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSolver.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppMath.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppKinsol.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSolver.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppMath.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppLinearSolver.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSolver.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppMath.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppMath.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppModelicaUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSolver.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppMath.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppRK12.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSolver.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppMath.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppRTEuler.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSolver.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppMath.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSimController.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppModelicaUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppMath.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSimulationSettings.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtendedSystem.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSystemBase.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSimulationSettings.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppUmfPack.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppSolver.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppMath.dylib (compatibility version 0.0.0, current version 0.0.0)
libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
```

**Comment by AnHeuermann** [comment]
Well I finally found where the path should be updated:
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Makefile.omsi.common#L86
Adding the missing stuff here should fix the problems.

```bash
build/lib/x86_64-darwin15.4.0/omc/OMSICpp/libOMCppDataExchange.dylib:
        @rpath/OMSICpp/libOMCppDataExchange.dylib (compatibility version 0.0.0, current version 0.0.0)
        /opt/openmodelica/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
        /opt/openmodelica/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
        /opt/openmodelica/lib/libboost_serialization-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
        /opt/openmodelica/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
        libOMCppExtensionUtilities.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by AnHeuermann** [comment]
@sjoelund Can you merge your PR https://github.com/OpenModelica/OpenModelica/pull/916 or cherry-pick my commits to your PR to see if it's working now?

**Comment by sjoelund** [comment]
Or you could just cherry-pick my commit to your branch since you don't have write access to my branch ;)

**Comment by AnHeuermann** [comment]
I tried that but Jenkins did not run the check. Don't know what I did wrong there but let's do it again.

**Comment by sjoelund** [comment]
Jenkinsfile has been modified in an untrusted revision... That's why. I gave you write access to my branch. I am not sure if it's only admins who can modify the Jenkinsfile...

**Comment by AnHeuermann** [comment]
Continued in https://github.com/OpenModelica/OpenModelica/pull/916.

**Pull request closed without merging**
