### PR TITLE
Use Qt's builtin json functionality if possible

### PR DESCRIPTION
**Pull request by adeas31**
### Related Issues

#6350

### Purpose

Speed up the reading of `model_info.json` file.

### Approach

Parsing of big json files is not so efficient wih the custom json parser.
Avoid using custom QJson parser on latest Qt versions.

### CODE REVIEW

**Comment by adeas31** [comment]
@sjoelund the library (http://qjson.sourceforge.net/) that we use for json parsing is not very efficient for big data. I changed the implementation to use [QJsonDocument](https://doc.qt.io/qt-5/qjsondocument.html) if possible. We still support old Qt versions so we have to keep the old implementation.

Can you please test if you debugger still works in Variables Browser.

**Comment by sjoelund** [comment]
I think we could just remove qjson since RedHat 6 is off life support, and we upgraded our Macs to versions where Qt4 is no longer supported.

**Comment by sjoelund** [comment]
That is if Qt 5.0.0 really is enough...

**Comment by adeas31** [comment]
Fine for me.

I will make a new PR to kill qjson and update OMEdit minimum requirement from Qt 4.6 to Qt 5.0

**Pull request merged**
