### PR TITLE
Assume that we have Lapack on Windows.

### PR DESCRIPTION
**Pull request by mahge**
- We also Assume that the lapack we have provides the deprecated
    lapack routines.

### CODE REVIEW

**Comment by adrpo** [comment]
I added the MINGW label, i guess we could run it again with it.

**Comment by mahge** [comment]
@adrpo I thought about it. But realized that it would not show us anything. It will build of course. However, since it does not run any tests, there is probably not much to see from it.

**Comment by adrpo** [comment]
Much better: Test Result (125 failures / -61)

**Comment by mahge** [comment]
Perfect. That seem to have fixed all the new failures.

**Pull request merged**
