### PR TITLE
Fix #6252

### LINKED ISSUE #6252: Placeholder

### PR DESCRIPTION
**Pull request by perost**
- Remove the input prefix from inputs with bindings if the binding
  is moved to an equation.

### CODE REVIEW

**Comment by sjoelund** [comment]
I still think there should be a warning or notification that this is done (when not doing checkModel)

**Comment by perost** [comment]
> I still think there should be a warning or notification that this is done (when not doing checkModel)

I'm not sure about that, it would indicate that the user is doing something wrong when they aren't. Is there any situation in which removing the input prefix would cause issues?

**Comment by sjoelund** [comment]
Top-level inputs are typically used to make it possible to control FMUs. It's pretty good to give the user a hint that this will not be possible. It's not necessarily wrong, so I guess a notification would be better than a warning. @casella ?

**Comment by casella** [comment]
> 
> 
> Top-level inputs are typically used to make it possible to control FMUs. It's pretty good to give the user a hint that this will not be possible. It's not necessarily wrong, so I guess a notification would be better than a warning. @casella ?

Agreed. Something like "top-level input variable XXX has a binding, so it won't be accessible as an input from the outside"

**Comment by perost** [comment]
> > Top-level inputs are typically used to make it possible to control FMUs. It's pretty good to give the user a hint that this will not be possible. It's not necessarily wrong, so I guess a notification would be better than a warning. @casella ?
> 
> Agreed. Something like "top-level input variable XXX has a binding, so it won't be accessible as an input from the outside"

Ok, I went with `Top-level input ‘%s‘ has a binding equation and will not be accessible as an input of the model`. I thought "input of the model" was a bit clearer than "input from the outside", but I can change it if you have any objections.

**Comment by casella** [comment]
> Ok, I went with `Top-level input ‘%s‘ has a binding equation and will not be accessible as an input of the model`. I thought "input of the model" was a bit clearer than "input from the outside", but I can change it if you have any objections.

Crystal clear, thanks!

**Pull request merged**
