### PR TITLE
More clarifications for MacOS

### PR DESCRIPTION
**Pull request by adrpo**
Explain what to do if the compiler cannot find stdio.h

### CODE REVIEW

**Comment by mahge** [comment]
What does OMEdit have as C and C++ compilers? If it is `cc` and `c++` (instead of g++ or clang++ ...) then we might have already covered this in the documentation. There is some info in there about explicitly setting C and CXX compilers when configuring. Even if you want it to pick the default ones.  Maybe we should move that to higher to make it more visible. Some more info [here](https://github.com/OpenModelica/OpenModelica/discussions/9129#discussioncomment-3031002).

**Comment by adrpo** [comment]
OMEdit has by default the compilers that were detected by configure. If those are not properly configured you get issues.

**Comment by adrpo** [comment]
Feel free to move the text around. Maybe we should have a Q & A section at the end so we don't clutter the flow for the "usually working fine" parts.

**Comment by mahge** [comment]
> OMEdit has by default the compilers that were detected by configure. 

If the default ones are `cc` and `c++` the that is probably the issue. You can double check it by inspecting what the default include directories are for `cc` vs `clang` 

```sh
$ /Library/Developer/CommandLineTools/usr/bin/cc -x c -v -E /dev/null
```
and 
```sh
$ clang -x c -v -E /dev/null
```

They both report exactly the same version but `clang` has one more default include directory, namely `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include`. I do not know why they did this it was very difficult to find out.

**Comment by mahge** [comment]
> Feel free to move the text around. Maybe we should have a Q & A section at the end so we don't clutter the flow for the "usually working fine" parts.

Yes, that is probably a good idea. I think it can use a revision. I will do that.

**Pull request merged**
