### PR TITLE
if true then true else if false then false else ?

### PR DESCRIPTION
**Pull request by phannebohm**

### CODE REVIEW

**Comment by phannebohm** [comment]
There are also quite a few of these in OMParser/test/msl.mo, not sure if they belong there...

**Review by JKRT — APPROVED** [review]
Checked on my machine. This seems to be all occurences. All tests pass, so should be OK to merge

**Comment by phannebohm** [comment]
Done, thanks

**Comment by phannebohm** [comment]
I am quite confused as to how this PR seems to have an effect on testing regressions ([newInst](https://libraries.openmodelica.org/branches/history/newInst/2020-08-27%2020:34:35..2020-08-30%2011:32:50.html), [master](https://libraries.openmodelica.org/branches/history/master/2020-08-27%2023:06:15..2020-08-30%2012:06:18.html))
It wasn't supposed to change anything.

**Comment by sjoelund** [comment]
Those are models that randomly fail

**Pull request merged**
