### PR TITLE
Add QtWebEngine support

### PR DESCRIPTION
**Pull request by jschueller**
see #9592

### CODE REVIEW

**Comment by jschueller** [comment]
@mahge it still pulls the previous image

**Comment by mahge** [comment]
Hmm. Maybe jenkins is doing this intentionally for security reasons. Maybe it intentionally doesn't pick up your changes to the Jenkinsfile. That would explain the issue.

I am not sure which part of my privilege allows me to do that. Maybe being maintainer is enough.

**Comment by mahge** [comment]
Jenkins logs this:
```
Pull request #11524 updated
17:32:25 Connecting to https://api.github.com/ using GitHub Access Token
Connecting to https://api.github.com/ to check permissions of obtain list of jschueller for OpenModelica/OpenModelica
Loading trusted files from base branch master at 2f9ee43d88c7cb78763b9b72ed71d70cd12e2985 rather than 4d67cccc63ca486372c39bbb09529849ccb2eee2
Obtained Jenkinsfile from 2f9ee43d88c7cb78763b9b72ed71d70cd12e2985
```

So yes, it is intentionally preventing you from modifying the Jenkinsfile. It is doing its job properly of course. It is me and you who were expecting it to do the unadvisable thing.

There are a couple of ways to continue this but first I can try removing you from the commit related to the Jenkinsfile changes. If that works we can continue. If not, which means Jenkins checks the PR author instead of the commit author, I guess we need to open a PR for you and the work can continue there.

**Comment by jschueller** [comment]
Still not allowed, I guess because anyone could fake a commit from someone else, but not the PR creation.

**Comment by mahge** [comment]
> Still not allowed, I guess because anyone could fake non-signed commits from someone else, but not the PR creation.

Oh yes. That is true as well. I guess we need a new PR created by a maintainer. 

I am trying to find where in the Jenkins documentation this is explained. I also want to see if there is a way to add exceptions for specific PRs or user's temporarily. I am guessing there would not be such options for the same security reasons.

**Comment by mahge** [comment]
@adrpo is there something we can do here apart from creating a new PR by a maintainer?

**Comment by mahge** [comment]
@jschueller I am not sure how this would work. Even if we create a PR for you, you won't be able to push changes to it unless you are a maintainer. 

Maybe someone who knows better about GitHub's confiurations can give us an idea of how to continue. 

In the meantime however, you can just continue with your work. We know the build now is fine now. So the next things to do are :

 - Actually test if OMEdit functions and works as expected with WebEngine
 - Modify the code so we can select WebEngine or WebKit as needed. We have to support WebKit for Windows MinGW builds since WebEngine is not available there.   This can get complicated but is probably managable.

**Comment by jschueller** [comment]
@mahge I added an option OM_OMEDIT_ENABLE_QTWEBENGINE that we can enable to use webengine instead of webkit
the code has missing minor bits marked TODO because there is no equivalent API in webengine

**Comment by mahge** [comment]
> @mahge I added an option OM_OMEDIT_ENABLE_QTWEBENGINE that we can enable to use webengine instead of webkit the DocumentationWidget code has missing minor bits marked TODO because there is no equivalent API in webengine

Okay. Don't worry about the CMake setting too much as long as it is working for you. We can restructure it later if needed. I think we can pick one of them as the main one and look for it first. If it is found we enable it. If it is not found then we look for the other one. If second one found we use that. Otherwise we issue an error and fail. We can implement this later so no worries for now.

That said, I think it is time that @adeas31 got involved in this now. -He can probably simplify things for you. He might also have some requirements and expectations. It is better to know before going too far.

**Comment by jschueller** [comment]
which distributions ? even debian 10 has qt5
in #9620 you told me that I could assume qt>=5
why is it not tested then ?

**Comment by adeas31** [comment]
Yeah sorry my bad. I looked at the code and we have this,

```
#include <QtGlobal>
#if (QT_VERSION < QT_VERSION_CHECK(5, 0, 0))
#error "OMEdit requires Qt 5.0.0 or newer"
#endif
```

So its fine.

**Comment by adeas31** [comment]
I can't review the PR now. I will try to do it tomorrow.

I see several `todo` in the code. Does this mean you are still working on it? In that case I will wait until you are finished.

**Comment by jschueller** [comment]
not really, its just places were there are no direct equivalent api in qwebenginepage, maybe javascript can be used instead but I would no know how to do it

**Review by adeas31 — APPROVED** [review]
The changes are fine. There are a lot of things that are not working with the QWebEngine e.g., I saw that you set the page to be editable but is not working as expected. The links are not handled etc. But since this is just part of CMake and OFF by default we can merge these changes and continue fixing QWebEngine with new PRs.

I restarted the job with Windows label. Once its done I will merge this.

**Comment by jschueller** [comment]
great, looks like it passed windows too

**Pull request merged**
