### PR TITLE
Fetch interfaces for external TLM sub-models

### PR DESCRIPTION
**Pull request by robbr48**
Access from context menu within the external sub-model.

This uses the `oms_fetchExternalModelInterfaces` API function in OMSimulator.

Edit: I added a new QAction instead of using the existing one for fetching interfaces, since it is still used in the previous TLM implementation.

### CODE REVIEW

**Comment by lochel** [comment]
@adeas31 @robbr48 is there any chance to integrate these changes?

**Comment by adeas31** [comment]
Ohhh this is rather old. I will try to resurrect it.

**Comment by adeas31** [comment]
@robbr48 is it possible for you to update this PR. This is very old when OMEdit was a submodule. I am unable to rebase it in a proper way. Maybe we can kill this PR and make a new one.

**Comment by AnHeuermann** [comment]
@robbr48 and @adeas31. This PR is now stale for another year. Should we close it?

**Comment by adeas31** [comment]
Yes we should to close this and @robbr48 need to make a new one.

**Pull request closed without merging**
