### PR TITLE
Cherry pick two bug fixes for Cpp runtime

### PR DESCRIPTION
**Pull request by rfranke**
#### Fix Cpp index of model variables for multidimensional arrays
Relevant if multi-dimensional arrays are part of the state vector.
The commit includes a new testcase.

#### Fix assignment of values to constant bvector in linear loops
A linear loop of the form `Ax=b` with constant `b` was treated as `Ax=0`.
Optimized on Sep 15, 2015:
commit e71411d00101bc29ff85be322d0fdf9a1e8eb249 "-some changes during intialization of linear algloops"
See `_bInitialized`, removed on Dec 14, 2016:
commit cab8786aaf392317662695b24fac2708be3592e7 "Separated nonlinear and linear system ..."

### CODE REVIEW

**Comment by rfranke** [comment]
Fine with me. I'm also hoping for fixes for messed up array expressions (issues #7818 and #7824).

**Comment by casella** [comment]
OK. In fact there are other pending issues that I really hoped were solved, see #7848, but I guess they will all have to end up in 1.18.1.

**Comment by casella** [comment]
@rfranke, I got lost by how GitHub presents things.

I checked the [commit history for maintenance/1.18](https://github.com/OpenModelica/OpenModelica/commits/maintenance/v1.18) but I can't see these fixes.

It is also not clear to me what are the commits on the master branch

**Comment by rfranke** [comment]
I removed these two commits and then github closed the PR, maybe because nothing had been left to merge.
I'm preparing a new PR with more bug fixes; still waiting for #7867 that currently hangs with osx-fmuchecker.

**Pull request closed without merging**
