### PR TITLE
Add OMSimulator as submodule

### PR DESCRIPTION
**Pull request by lochel**
### Purpose

This PR adds the OMSimulator to the OpenModelica super-project.

### Type of Change

- New feature (non-breaking change which adds functionality)

---

### Open Questions and Pre-Merge TODOs

- [x] Update makefiles

### CODE REVIEW

**Comment by sjoelund** [comment]
If you want it built, the makefiles need to be adapted... And the build projects (to be in the installer)

**Comment by sjoelund** [comment]
And was the Hudson job changed to not auto-update this?

**Comment by lochel** [comment]
> If you want it built, the makefiles need to be adapted... And the build projects (to be in the installer)

According to the last meetings, we'll do that later.

**Comment by sjoelund** [comment]
OK, then it might just be the Hudson job to not get a bunch of commits only bumping this subproject

**Comment by lochel** [comment]
> And was the Hudson job changed to not auto-update this?

I can do that, but I don't see why. It's basically the same than OMCompiler and it makes sense to have the latest version in the nightly builds.

**Comment by adeas31** [comment]
> > If you want it built, the makefiles need to be adapted... And the build projects (to be in the installer)

> According to the last meetings, we'll do that later.

Atleast you need to fix the makefiles to build it otherwise merging OMEdit code doesn't make sense.

**Comment by lochel** [comment]
Okay, I will add a target to the makefiles to build it manually.

**Comment by lochel** [comment]
@adeas31 I've now updated the makefiles. So I guess this should be good enough to merge the OMEdit changes, right?

**Comment by adeas31** [comment]
Yes. Once this PR is merged then I can merge OMEdit changes.

**Comment by adrpo** [comment]
Sounds good to me, we need to do this anyway, we can improve it later.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-07-12_08-59-36](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5884/console).

**Pull request closed without merging**
