### PR TITLE
Delete OpenModelicaScriptingAPI.tmp.mo after use

### PR DESCRIPTION
**Pull request by phannebohm**
### Related Issues

Retry #11351 to see if it is Jenkins' fault.

### CODE REVIEW

**Comment by mahge** [comment]
I should have said something but I found out later that this can be reproduced. 

It seems adding the comment causes the issue if it is there when OpenModelica is built for the first time. If you add the comment afterwards and rebuild, everything seems to go fine. If you have the comment when you first build OpenModelica you get the error message that you see here on Jenkins. However, if you just run the build once again after that, you get another error, i.e., the Boolean error is no longer printed but it just fails without any messages. So ya that is fun. Git clean, recompile, sift through messages, rinse and repeat, takes a lot of time.   

Between this and #9602, today has been a weird day 🙂.

**Comment by phannebohm** [comment]
This is really weird :sweat_smile: 
@AnHeuermann suggested that the special ` character may be responsible. I removed that now, let's see...
But why would that work for cmake and not for makefiles?

**Comment by mahge** [comment]
The bootstrapping sources are different. They means the bootstrapped omc created by CMake and autoconf are different.

If the autoconf build succeeds once somehow, i.e., a new omc is generated from the current MetaModelica sources, then that omc will have no problem with the comments. It is only the compiler created from the bootstrapping C source files that will have the issue.

The specific issue is, having a comment in an if condition. The error message was complaining about `conditional bool`. As it turns out, a variable named `bool` is used as the if condition.

I am not entirely sure yet but it might be caused by #11241 updating the bootstrapping sources for the CMake build but not for the autoconf one. The autoconf ones are in the OpenModelica repository itself while the CMake ones are downloaded during configure time from https://github.com/OpenModelica/OMBootstrapping.

You want something more exciting 🙂, apparently you can not build a debug version of OpenModelica (with `-g - O0`) with the autoconf build right now. `-O2` works fine. So debugging the bootstrapped compiler is a no go for now. 

Anyway, it is most likely that the issue is #11241 not updating the bootstrapping sources for the autoconf build. I think @perost didn't realize there were two places to update for the two build systems.

**Comment by perost** [comment]
> Anyway, it is most likely that the issue is #11241 not updating the bootstrapping sources for the autoconf build. I think @perost didn't realize there were two places to update for the two build systems.

#11241 didn't update the bootstrapping sources, it only changed the parsing of within-statements so I didn't bother updating them since it doesn't affect MetaModelica. I only update the bootstrapping sources when it's necessary, and then you're usually forced to update both of them to get the change through.

**Comment by mahge** [comment]
It was just a guess assuming comments in if-conditions worked in the past. The might just as well been there for a long time. 

I can see that you updated the boostrapping sources for CMake (https://github.com/OpenModelica/OMBootstrapping/commits/master). However, the bootstrapping sources for the autoconf build ( https://github.com/OpenModelica/OpenModelica/commits/master/OMCompiler/Compiler/boot/bootstrap-sources) have not been modified in a while. Considering that the parser changed in #11241, and also I have nothing else to think of yet, it seemed like a good place to start.

The autoconf based debug build of the bootstrapped compiler (configured with `CFLAGS="-g -O0" CXXFLAGS="-g -O0`) also fails with the error message
```
/usr/bin/ld: OpenModelica/build/lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: undefined reference to `omc_AbsynUtil_setClassCommentsAfterEnd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So there is something not quite right there.

**Comment by perost** [comment]
> I can see that you updated the boostrapping sources for CMake (https://github.com/OpenModelica/OMBootstrapping/commits/master). However, the bootstrapping sources for the autoconf build ( https://github.com/OpenModelica/OpenModelica/commits/master/OMCompiler/Compiler/boot/bootstrap-sources) have not been modified in a while. Considering that the parser changed in #11241, and also I have nothing else to think of yet, it seemed like a good place to start.

I've only updated the bootstrapping header so the change is in the [boot folder](https://github.com/OpenModelica/OpenModelica/commits/master/OMCompiler/Compiler/boot) above, not in the `bootstrap-sources` folder.

**Comment by mahge** [comment]
Ah I see. In that case the next possible contender is https://github.com/OpenModelica/OpenModelica/pull/8125. Which means this issue has been there for about 2 years now.

**Comment by phannebohm** [comment]
I guess I'll have to merge this without comment then.

We can open an issue for comments in if-conditions. Looks like that is a bit more involved than fits in this PR.

**Comment by mahge** [comment]
> I guess I'll have to merge this without comment then.
> 
> We can open an issue for comments in if-conditions. Looks like that is a bit more involved than fits in this PR.

I think so. There is no reason why this should wait for the bootstrapping related issues.

**Pull request merged**
