### PR TITLE
Enable the rename context menu item

### LINKED ISSUE #7110: Renaming of components, i.e., submodels
### Description
OMEdit doesn't allow renaming submodels.

### Screenshots
image

### Version and OS
- Connected to OMCompiler v1.17.0-dev.359+ge7fca47128
- Connected to OMSimulator v2.0.0.post285-g7de662d-linux
 - WSL2, 64 bit

### PR DESCRIPTION
**Pull request by adeas31**
Fixes #7110
Handle the rename of models separately

### CODE REVIEW

**Comment by adeas31** [comment]
@lochel then crash caused by https://github.com/OpenModelica/OMSimulator/pull/928 is fixed now.

**Comment by adeas31** [comment]
Time to fix `[loadSnapshot] this API cannot be used to rename a model`.

**Comment by lochel** [comment]
> Time to fix `[loadSnapshot] this API cannot be used to rename a model`.

Not yet 😄 there are still several issues with the `oms_rename` function (e.g., connections and connectors get still destroyed in the internal representation) that we are addressing in OpenModelica/OMSimulator#928.
Can you add the rename functionality to the context menu in the diagram view? Right-clicking on a component seems to be a quite common approach for renaming.

**Comment by adeas31** [comment]
> @adeas31 Can you add the rename functionality to the context menu in the diagram view? Right-clicking on a component seems to be a quite common approach for renaming.

Is already there but hidden inside `Properties` menu item.

**Comment by lochel** [comment]
I noticed that. It is nice, but wouldn't hurt to also have it in the context menu, right?

**Comment by adeas31** [comment]
Sure but then I suggest to remove it from other places. Keeping the same functionality at several places adds up to more maintenance work of course. We can decide what is a more natural place to have it?

**Comment by lochel** [comment]
I see your point! I guess we can keep it as it is then. And if needed we can change it later anyays.

**Comment by lochel** [comment]
@adeas31, you can merge this pull request after #7138

**Review by lochel — APPROVED** [review]

**Pull request merged**
