### PR TITLE
Revert "[SimCode] update daeMode (#728)"

### PR DESCRIPTION
**Pull request by lochel**
This reverts commit c67fe97a0834c7cc47f23db12e5fc5f23f0e1f5f.

### CODE REVIEW

**Comment by casella** [comment]
@adrpo, @sjoelund, can you please merge this ASAP?

**Comment by sjoelund** [comment]
Why does it need to be reverted? Did it break something? If so, there's a test in the test suite missing

**Comment by casella** [comment]
> Why does it need to be reverted? Did it break something? 

Yes, see comments in #728. 

>If so, there's a test in the test suite missing

AFAIK there are probably no tests at all using --daeMode in the testsuite, or maybe just a few. The failing tests are in the 3rdparty testsuite, specifically PowerGrids, which is the only library currently activating this mode explicitly. And, we still don't even know why they fail.

If we want to support --daeMode seriously, we should basically run the same models we run in odeMode also in daeMode. If we did it now, the result will be a bloodbath, just compare [MSL 3.2.3 newInst](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.3/Modelica_3.2.3.html) with [MSL 3.2.3 newInst-daeMode](https://libraries.openmodelica.org/branches/newInst-daeMode/Modelica_3.2.3/Modelica_3.2.3.html).  We can think about it, and I will open a ticket about this issue ASAP, but for the time being please just merge this PR, so that the models in PowerGrids get running again.

@kabdelhak will test his new PR with those models before pushing it.

**Comment by sjoelund** [comment]
I guess add those models to the testsuite as total models before even starting to develop the fix.

**Comment by casella** [comment]
Sounds good. @kabdelhak, can you take care of that?

**Comment by casella** [comment]
See [#5843](https://trac.openmodelica.org/OpenModelica/ticket/5843)

**Pull request merged**
