### PR TITLE
Work around MetaModelica bug in Conversion

### PR DESCRIPTION
**Pull request by perost**

### CODE REVIEW

**Comment by casella** [comment]
@sjoelund, @adrpo, can you please re-run the conversion testing job? Thanks!

**Comment by perost** [comment]
> @sjoelund, @adrpo, can you please re-run the conversion testing job? Thanks!

@sjoelund started it after this PR was merged.

**Comment by casella** [comment]
I'll keep an eye on the [report](https://libraries.openmodelica.org/branches/overview-special-jobs.html). It seems it takes several days to go through it.

**Comment by perost** [comment]
The conversion testing job got killed when Jenkins was restarted due to the issues we had yesterday, but it's running again now.

**Pull request merged**
