### PR TITLE
Support parsing of double underflow and convert to zero

### PR DESCRIPTION
**Pull request by adrpo**
- give a warning on underflow and convert to zero.
- double overflow is still an error.

### CODE REVIEW

**Comment by adrpo** [comment]
@casella do you think this is OK?

**Comment by adrpo** [comment]
I will change the code so we can parse these files so the user can save them in OMEdit. 
The error should come later when we flatten the model.

**Comment by adrpo** [comment]
But for now, we can merge this one.

**Comment by casella** [comment]
> @casella do you think this is OK?

See my comments [here](https://github.com/OpenModelica/OMMatlab/issues/17#issuecomment-1312082312).

**Pull request merged**
