### PR TITLE
Fix for #9918

### LINKED ISSUE #9918: OMEdit can not run models with imported FMUs even in simple cases
### Description
I could not run in OM models using imported FMUs created by Dymola, even in the simplest case.

_There is a remote possibility that my Dymola's FMU lacks some permission. However it shouldn't, since I've bought the license to export, and in other cases I can create FMUs from dymola that can be run inside OM (through SSP). But, strangely, not in this simple case._ 

### Steps to Reproduce
Consider, from [FirstDym.zip](https://github.com/OpenModelica/OpenModelica/files/10201385/FirstDym.zip)
StepFirst.mo: 
image
its output is:
image
The same result can be obtained creating an FMU ME with OM (First.fmu) then importing it in the following model StepFirstFmu:
image
If, however, the FMU is created from Dymola (FirstDym.fmu), the model StepFirstFmuDym does not work:
image

### Expected Behavior
The model StepFirstFmuDym.mo should give the same firstOrder.y signal as StepFirst.mo and StepFirstFmu.mo

### Version and OS
OM 1.20.0, Win 11

### PR DESCRIPTION
**Pull request by casella**
Should fix #9918 by avoiding calls to fmi2SetTime when in initialization state.

### CODE REVIEW

**Review by adeas31 — APPROVED** [review]

**Comment by casella** [comment]
@adeas31, unfortunately this created a lot of problems. Is it the code or a CI glitch?

**Comment by adeas31** [comment]
Seems like the code. The simulation is failing.

**Comment by mahge** [comment]
The first failing testcase `/testsuite/openmodelica/fmi/ModelExchange/2.0/FMUResourceTest.mos` works fine if you use the NF here
https://github.com/OpenModelica/OpenModelica/blob/a92310ef8cf055561aabdfb11282b634bfcc3433/testsuite/openmodelica/fmi/ModelExchange/2.0/FMUResourceTest.mos#L5

With the OF it fails with the error 
```
simulationOptions = "startTime = 0.0, stopTime = 100.0, numberOfIntervals = 500, tolerance = 1e-06, method = 'dassl', fileNamePrefix = 'FMUResourceTest_TestResource_me_FMU', options = '', outputFormat = 'mat', variableFilter = '.*', cflags = '', simflags = ''",
messages = "Simulation execution failed for model: FMUResourceTest_TestResource_me_FMU
module = FMUResourceTest_TestResource, log level = ERROR: [logStatusError][FMU status:Error] fmi2GetInteger: Illegal model exchange call sequence. fmi2GetInteger is not allowed in model_state_instantiated state.
assert | debug   | fmi2GetInteger failed with status : Error
assert | info    | simulation terminated by an assertion at initialization
module = FMUResourceTest_TestResource, log level = ERROR: [logStatusError][FMU status:Error] fmi2Terminate: Illegal model exchange call sequence. fmi2Terminate is not allowed in model_state_error state.
"
end SimulationResult;
```

I will check the second model.

The error message is just hidden because the script sets `echo(false);` to suppress the outputs.

**Comment by mahge** [comment]
Both testcases pass with the NF. They need to be adjusted to use the NF

https://github.com/OpenModelica/OpenModelica/blob/a92310ef8cf055561aabdfb11282b634bfcc3433/testsuite/openmodelica/fmi/ModelExchange/2.0/FMUResourceTest.mos#L5


https://github.com/OpenModelica/OpenModelica/blob/a92310ef8cf055561aabdfb11282b634bfcc3433/testsuite/openmodelica/cppruntime/fmu/modelExchange/2.0/testCombiTable2D.mos#L5

**Comment by casella** [comment]
> Both testcases pass with the NF. They need to be adjusted to use the NF

Is there any reason why we should still use the OF? I can't see any, we only use the OF for bootstrapping and for API functions that have not yet been converted to the NF, but we shouldn't be using it for generating code that is expected to run simulations, right?

If so, @mahge please go ahead with that. Thanks!

**Comment by casella** [comment]
testCombiTable2D.mos still fails 😞

**Comment by mahge** [comment]
> Is there any reason why we should still use the OF? I can't see any, we only use the OF for bootstrapping and for API functions that have not yet been converted to the NF, but we shouldn't be using it for generating code that is expected to run simulations, right?

Many tests are still run with the OF. Only because nobody has checked and changed them to the NF. The tests are  "diff" tests, as in the they compare the outputs of the compiler. So converting the flattening tests to use the NF will require some level of tedious work. Simulation tests on the other hand can and should be changed to NF nowadays. 

> testCombiTable2D.mos still fails 😞

It is odd. It works fine on my machine. Maybe it has to do with the CMake vs normal build. I will check.

**Comment by casella** [comment]
> Many tests are still run with the OF. Only because nobody has checked and changed them to the NF. The tests are "diff" tests, as in the they compare the outputs of the compiler. So converting the flattening tests to use the NF will require some level of tedious work. 

OK. But it for some reason they start failing with the OF and don't fail with the NF, there's no reason not to update them, right?

> > testCombiTable2D.mos still fails 😞
> 
> It is odd. It works fine on my machine. Maybe it has to do with the CMake vs normal build. I will check.

Weird.

**Comment by mahge** [comment]
> OK. But it for some reason they start failing with the OF and don't fail with the NF, there's no reason not to update them, right?

I think so. We should update them whenever we can. I will try and see if I can update the similar test cases in the PR.



> > It is odd. It works fine on my machine. Maybe it has to do with the CMake vs normal build. I will check.
> 
> Weird.

As it turns out this was a debug vs release build difference. There is an un-initialized variable (representing an external table object) being used by the CPP runtime when it tries to simulate and imported FMU. In the debug builds this was being initialized to null and everything goes fine. In release builds it gets a garbage value.

I will try and fix it. Although I am not sure how to do it yet.

**Comment by mahge** [comment]
We took a look at this with @AnHeuermann yesterday and it turned out that we were doing things in the wrong order when importing FMUs. It is not just a CPP runtime or even an OF issue even though the issue manifests when those are used.  

I tried to clean up the importing code we generate a bit. However, some tests break if I modify things too much. So for now I have made the smallest change that lets the test pass. The test now passes even with the OF.

At some point someone should take another look at the Modelica importing code we generate and the order in which FMI operations are done.

**Pull request merged**
