### PR TITLE
Fix for ticket 5766

### PR DESCRIPTION
**Pull request by AnHeuermann**
- Don't ignore `-ils` flag any more
  - Added testcase for `-ils` flag
  - Made description of `-ils` flag more detailed

### CODE REVIEW

**Comment by adrpo** [comment]
You need to also update the testsuite files.

**Comment by casella** [comment]
Any other issue with this PR? I need to understand if some `PowerGrids` models work with a sufficient number of homotopy steps, just taking one in some cases is not really enough.

Thanks!

**Comment by AnHeuermann** [comment]
The commit itself should be working. The question is if Jenkins can do the tests now. It failed in steps that are before or way after my changes.

**Comment by casella** [comment]
Thank you Adrian! I'll see if I can trigger a Windows nightly right away

**Comment by casella** [comment]
Just started

**Pull request merged**
