### PR TITLE
Use the model name instead of fully qualified path

### LINKED ISSUE #5796: Models with long path names cause a code generation failure under Windows

### PR DESCRIPTION
**Pull request by adeas31**
Fixes #5796. Avoid creating long path by only using the model name

### CODE REVIEW

**Comment by adeas31** [comment]
@casella now the file name prefix is automatically set to the model name unless specified explicitly. I also set the generated folder name to model name. This PR guarantees the unique folder name by appending the timestamp with the folder name. We add 16 characters extra for timestamp compared to long fully qualified paths.

**Comment by casella** [comment]
> @casella now the file name prefix is automatically set to the model name unless specified explicitly. 

Good.

> I also set the generated folder name to model name. This PR guarantees the unique folder name by appending the timestamp with the folder name. We add 16 characters extra for timestamp compared to long fully qualified paths.

I'm not 100% sure about this idea, because it will generate one new directory each time you simulate. In fact it's good if you want to keep all past results, it isn't if you don't, because your temp directory will very soon fill up with old stuff. 

What do you think?

**Comment by adeas31** [comment]
Yes it will clutter the temp directory. Then I guess we should just stick to filename prefix solution and keep the folder name same as before i.e., fully qualified.

**Comment by casella** [comment]
Maybe we could leave your solution for the directory with name + timestamp as an option?

**Comment by adeas31** [comment]
Yes that one alternate to keep both functionalities but perhaps not needed. For now the folder name is fully qualified path and the generated files use just the model name.

**Pull request merged**
