### PR TITLE
OMEdit: update DynamicSelect handling

### PR DESCRIPTION
**Pull request by atrosinenko**
Account for the fact that now DynamicSelect annotation is formatted as `DynamicSelect(...)` function invocation, not just `{...}`. Technically, its second agument is arbitrary expression. For now, just support

* `if <var> then <color1> else <color2>` -- for colors
* `String(value, precision, <unused>)` -- for TextAnnotation

Model for testing:
```modelica
model Test
  Modelica.Blocks.Interaction.Show.RealValue realValue1(number = time, use_numberPort = true)  annotation(
    Placement(visible = true, transformation(origin = {-2, 16}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Interaction.Show.BooleanValue booleanValue1(use_activePort = true)  annotation(
  
    Placement(visible = true, transformation(origin = {-2, -2}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  realValue1.numberPort = time * 10; 
  booleanValue1.activePort = time > 0.5;
annotation(
    uses(Modelica(version = "3.2.2")),
    Diagram(coordinateSystem(initialScale = 0.1)));
end Test;
```

Editing:
Editor

"Plotted" diagram:
Plot

### CODE REVIEW

**Comment by atrosinenko** [comment]
To be reviewed:
* performance of `getStrings()`
* possible regressions w.r.t. re-saving annotations (are some data lost that were preserved earlier?)
* ...

**Comment by adrpo** [comment]
Is this handling the new front-end (NF) or the current front-end? 
For NF one needs to use `-nfAPIDynamicSelect ` to get the DynamicSelect expressions.
See: https://trac.openmodelica.org/OpenModelica/ticket/5631

Also, it doesn't seem to work on Qt4: 
```
Util/StringHandler.cpp:936:53: error: ‘class QString’ has no member named ‘back’
       else if (!ele.isEmpty() && value.at(i) == ele.back())
```

**Comment by atrosinenko** [comment]
> Also, it doesn't seem to work on Qt4

Dropped usage of `QString::back()`. Hope then will work...

> Is this handling the new front-end (NF) or the current front-end?

It handles both frontends (they seem to behave identically) but for NF the `nfAPIDynamicSelect` is required.

**Comment by atrosinenko** [comment]
In fact, this should probably be implemented in the backend but this PR handles at least the basic use cases. Together with OPC UA it could be nice feature.

**Comment by adrpo** [comment]
As far as I know the current front-end filters out some of the DynamicSelect so they can appear only in some contexts, the NF does not do that so one can use DynamicSelect anywhere in a graphical annotation. 

The specification says: "Any value (coordinates, color, text, etc.) in graphical annotations can be dependent on class variables using the DynamicSelect expression". I wonder if one could use DynamicSelect to change graphics, i.e. something like: `Icon(graphics={DynamicSelect(Rectangle(...), Ellipse(...))}`.

**Comment by atrosinenko** [comment]
Added the second commit. It is work-in-progress and RFC. It implements tracking interactive simulation for diagram window. When debugging it, I spotted an issue with the first commit: I cannot distinguish when expression is not supported from the case when it has some particular value (0, false, etc.).

```modelica
model TestInteractive
  Modelica.Blocks.Interaction.Show.RealValue value annotation(
    Placement(visible = true, transformation(origin = {-7, -2}, extent = {{-15, -10}, {15, 10}}, rotation = 0)));
  Modelica.Blocks.Interaction.Show.BooleanValue upMarker annotation(
    Placement(visible = true, transformation(origin = {8, 22}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Interaction.Show.BooleanValue downMarker annotation(
    Placement(visible = true, transformation(origin = {8, -24}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Boolean up, down, blinkOn;
  Real x;
  input Real target;
equation
  der(x) = target - x;
  blinkOn = mod(time, 1) > 0.5;
  up   = (target > x) and blinkOn;
  down = (target < x) and blinkOn;
  value.numberPort = x;
  upMarker.activePort   = up;
  downMarker.activePort = down;

annotation(
    Diagram(graphics = {Text(origin = {-22, 23}, extent = {{-18, 9}, {18, -9}}, textString = "Up"), Text(origin = {-26, -50}, extent = {{-14, 38}, { 18, 16}}, textString = "Down")}),
    uses(Modelica(version = "3.2.3")));end TestInteractive;
```

**Comment by atrosinenko** [comment]
I have fixed a potential issue with unknown expression types but it seems, variables are sometimes lost, see:

```modelica
model TestInteractive
  Modelica.Blocks.Interaction.Show.RealValue value annotation(
    Placement(visible = true, transformation(origin = {-7, -2}, extent = {{-15, -10}, {15, 10}}, rotation = 0)));
  Modelica.Blocks.Interaction.Show.BooleanValue upMarker annotation(
    Placement(visible = true, transformation(origin = {8, 22}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Interaction.Show.BooleanValue downMarker annotation(
    Placement(visible = true, transformation(origin = {8, -24}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Boolean up, down;
  Real x;
  input Real target;
equation
  der(x) = target - x;
  up   = (target > x);
  down = (target < x);
  value.numberPort = x;
  upMarker.activePort   = up and (mod(time, 1) > 0.5);
  downMarker.activePort = down and (mod(time, 1) > 0.5);

annotation(
    Diagram(graphics = {Text(origin = {-22, 23}, extent = {{-18, 9}, {18, -9}}, textString = "Up"), Text(origin = {-26, -50}, extent = {{-14, 38}, { 18, 16}}, textString = "Down")}),
    uses(Modelica(version = "3.2.3")));end TestInteractive;
```
with new frontend.

**Comment by atrosinenko** [comment]
Meanwhile, should [this line](https://github.com/atrosinenko/OpenModelica/blob/b31b61e36853b99efe92ffd920496686a4aef82a/OMCompiler/SimulationRuntime/opc/ua/omc_opc_ua.c#L664) unlock `&state->mutex_values[latestValues]` in
```cpp
  waitForStep(state);

  pthread_mutex_lock(&state->mutex_values[state->latestValues ? 0 : 1]);
  latestValues = state->latestValues;
  state->latestValues = state->latestValues ? 0 : 1;

  state->time[latestValues] = t;

  for (i = 0; i < modelData->nVariablesReal; i++, realIndex++) {
    state->realVals[latestValues][realIndex] = (data->localData[0])->realVars[i];
  }
  for (i = 0; i < modelData->nVariablesReal; i++, boolIndex++) {
    state->boolVals[latestValues][boolIndex] = (data->localData[0])->booleanVars[i];
  }

  pthread_mutex_unlock(&state->mutex_values[latestValues]);
```
It seems like either some intricate mutex handling or just a mistake: changing `latestValues` to `latestValues ? 0 : 1` (unlocking what the code locked several lines above) eliminates glitches and the simulation executable no more deadlocks after the first pause. Unfortunately, I cannot say for sure because I don't know details about what is protected by what mutex.

**Comment by adrpo** [comment]
> Meanwhile, should [this line](https://github.com/atrosinenko/OpenModelica/blob/b31b61e36853b99efe92ffd920496686a4aef82a/OMCompiler/SimulationRuntime/opc/ua/omc_opc_ua.c#L664) unlock `&state->mutex_values[latestValues]` in
> 
> ```c++
>   waitForStep(state);
> 
>   pthread_mutex_lock(&state->mutex_values[state->latestValues ? 0 : 1]);
>   latestValues = state->latestValues;
>   state->latestValues = state->latestValues ? 0 : 1;
> 
>   state->time[latestValues] = t;
> 
>   for (i = 0; i < modelData->nVariablesReal; i++, realIndex++) {
>     state->realVals[latestValues][realIndex] = (data->localData[0])->realVars[i];
>   }
>   for (i = 0; i < modelData->nVariablesReal; i++, boolIndex++) {
>     state->boolVals[latestValues][boolIndex] = (data->localData[0])->booleanVars[i];
>   }
> 
>   pthread_mutex_unlock(&state->mutex_values[latestValues]);
> ```
> 
> It seems like either some intricate mutex handling or just a mistake: changing `latestValues` to `latestValues ? 0 : 1` (unlocking what the code locked several lines above) eliminates glitches and the simulation executable no more deadlocks after the first pause. Unfortunately, I cannot say for sure because I don't know details about what is protected by what mutex.

@sjoelund, @AnHeuermann any ideas on this mutex?

**Comment by AnHeuermann** [comment]
Sorry, I've not worked with this yet.
But I would agree, it looks more rigth.

**Comment by atrosinenko** [comment]
Is it worth targeting it for 1.14?

**Comment by adeas31** [comment]
Sorry I haven't got enough time to look through it. I just briefly looked the code and I don't like the way you are parsing the dynamic select strings. We need a proper parser for that.

Anyways this can wait. We can target this for 2.0 release.

**Comment by atrosinenko** [comment]
Frankly speaking, I don't like this way, too :) On one hand, it allows basic cases to work, on the other, it may be misleading for implementers of custom components. 

Ideally would be to have some compiler pass that converts these expressions in a dummy `DynamicSelect(defaultValue, syntheticVarReference)`, I think. Otherwise one have to reimplement almost the entire Modelica spec in C++ as well as in MetaModelica.

**Comment by atrosinenko** [comment]
Or even return plain component descriptions from the backend with `DynamicSelect`s evaluated and marked as "may change", so on every visualization step those parts would be requested. On one hand, this can handle even the case proposed by @adrpo 

> Icon(graphics={DynamicSelect(Rectangle(...), Ellipse(...))}.

and would be more uniform than current `mDynamicValue`s spread everythere.

On the other hand, it is probably an enormous amount of work even not mentioning that this should be supported by the **simulation runtime**, not only some compiler pass...

**Comment by lochel** [comment]
@adeas31 Any chance to integrate these changes? Or will it require a new and different attempt?

**Comment by adeas31** [comment]
Yes at least I think that this requires a new and better approach.
I will close this for now as is rather old. @atrosinenko if you have time then update it to the latest code and test it again to see if it still works as expected.

**Pull request closed without merging**
