### PR TITLE
CMake improvments

### PR DESCRIPTION
**Pull request by mahge**
@mahge
Add missing susan template target.
b5b4271

  - This was working because the normal OpenModelica compilation generated
    the mo file from the tpl file. The CMake compilation was just picking
    that one and never complained.

@mahge
[cmake] Generate OpenModelicaScriptingAPI.mo
64eed1d

  - This was missing. CMake compilation worked only because the normal
    OpenModelica compilation generated this file. The CMake compilation
    was just picking up that file and never complained.

@mahge
[cmake] Move Dynload_omc.cpp to omcruntime lib.
423c76e

  - It was in omcbackendruntime. It seems like it "belongs" in omcruntime.

@mahge
[cmake] Remove omparse-boot.
2f1a1f4

  - It is not needed. We are trying a different approach for bootstrapping

@mahge
Move some scripting API functions to CevalScript.
e215985

  - This were in CevalScriptBackend.mo before. The reason they were in there
    was that the original plan for bootstrapping with the CMake config
    was to not use the bootstrap tarball. Instead the plan was to use
    the latest C source files of the MetaModelica sources that passed
    the CI run. This meant these scripting api functions were not
    technically needed for the 'normal bootstrapping' so they could be
    in the "backend" interface.

    However, bootstrapping just changed. And the tarball(and related nuances)
    are mostly gone. So at this point it is worth to take the same source
    files that the normal bootstrapping uses since they are already
    available within the repo.

@mahge
Add boot folder to cmake configuration/compilation
f5ffb54

@mahge
A quick support for generating config.unix.h.
4aae339

@mahge
Add boot libraries and use them for bootstrapping.
4795955

  - Added omparse-boot
  - Added omcruntime-boot
  - Added omcgraphstream-boot

  All of this can probably be avoided if OpenModelciaBootstrapping header
  is added to version control and updated with the bootstrapping sources.

  For now I am going to do it this way since this is how the 'normal'
  bootstrapping works.

@mahge
Use OpenModelicaBootstrappingHeader.h from tarball
03ebe58

  - Use OpenModelicaBootstrappingHeader.h from tarball-include for now.

    It would be nice if it is also added to source control just like the
    C bootstrapping source files. Otherwise it might actually break.

    If we add it to source control we can also remove the boot libraries
    like omparse-boot, omcruntime-boot ....

@mahge
Add generation of Util/Autoconf.mo
6714810

  - This adds a quick and ugly generation of Autoconf.mo from
    Autoconf.mo.in (linux) or from (copy only) Autoconf.mo.omdev.mingw
    (windows)

  - The generation code is added in Compiler/runtime/CMakeLists because
    we have a few variables already defiend in there for generation of
    config.unix.h.

    This should probably be moved outside to some higher directory.

@mahge
Add (incomplete) generation of c/RuntimeSources.mo
7079cf4

  - This just a quick way to enable bootstrapping.
    The contents of the file are not really complete and can not be expected
    to be used for simulation yet.
    But that is the case for many other things regarding simulation
    executable compilation. There is some work needed to handle that.

@mahge
Update 3rdParty submodule.
36ecba5

  - The changes from the branch are merged to master on 3rdParty.
    Submodule head is updated now.

### CODE REVIEW

**Review by adrpo — APPROVED** [review]
OK with me!
Just get rid of the /mahge/dev/ -> /per/workspace/ changes as they have no value.

**Comment by mahge** [comment]
I wanted to get rid of them. But his folder's stiring literal is longer than mine. Which means they won't fit whatever array they are effectually assigned to if I just update the string literals. I don't think it is a serious issue since they are not used apart from error messages and bootstrapping is not supposed to error out.  I thought it might be safer to just leave them as is to be on the safe side.
I will check and see if It is easy to not update them. It will help in the future as well.

**Comment by sjoelund** [comment]
> Just get rid of the /mahge/dev/ -> /per/workspace/ changes as they have no value.

I think we should change the messages to strip out the directory when creating the bootstrapping sources for the future

**Comment by mahge** [comment]
> 
> I think we should change the messages to strip out the directory when creating the bootstrapping sources for the future
Yes I was thinking of the same thing. Can we do it similar to how testsuite friendly names are generated?

**Pull request merged**
