### PR TITLE
Update PATH with library dirs before system calls.

### LINKED ISSUE #6242: Modelica External C dependencies are not found on Windows
This is a placeholder created during migration to preserve original issue numbers.

----

Migrated-From: https://trac.openmodelica.org/OpenModelica/ticket/6242

### LINKED ISSUE #8546: TILMedia simulation process crashes
### Description
Simulation process of TILMedia testers crashes.

### Steps to reproduce
Start OMEdit (Windows 64-bit)
Open TILMedia (https://github.com/TLK-Thermo/TILMediaClaRa)
Simulate one of the models in the "Testers" package (e.g. TILMedia.Testers.TestLiquid, default simulation setup was used)

### Expected behavior
Successful simulation. According to the [OM tests](https://libraries.openmodelica.org/branches/master/TILMedia/TILMedia.html) the models simulate successfully on Linux.

### Screenshots
image

### Version and OS
 - OpenModelica Version: omc v1.19.0-dev-586-gbf2fb176ac-64bit
 - OS: Windows 10
 - TILMedia ClaRa 1.7.0

### PR DESCRIPTION
**Pull request by mahge**
- On Windows the required DLLs need to be in the same directory as the
    executable or they need to be in PATH.

    So, before we issue commands that launch simulation executables, update
    the PATH by prepending the library dirs used for linking the executable.

    E.g. If these paths are used to compile a simulation executable:
    ```
    {
     \"-LC:/Users/username/AppData/Roaming/.openmodelica/libraries/Buildings/Resources/Library/win64\",
     \"-LC:/Users/username/AppData/Roaming/.openmodelica/libraries/Buildings/Resources/Library\",
      ...
    }
    ```

    we update the PATH to
    ```
    C:\Users\username\AppData\Roaming\.openmodelica\libraries\Buildings\Resources\Library\win64;
    C:\Users\username\AppData\Roaming\.openmodelica\libraries\Buildings\Resources\Library;
    %PATH%
    ```

    before launching the simulation executable. Then we reset it back immediately afterwards.

  - Fixes #8546. Fixes #6242.

### CODE REVIEW

**Comment by mahge** [comment]
Fixes #8546. Fixes #6242.

**Comment by adrpo** [comment]
Note that this will not work if you use OMEdit as it calls make and then runs the executable. I would suggest dumping a file Model_setLibPaths.cmd that can be called by OMEdit before running the executable.

**Comment by mahge** [comment]
I did not think of OMEdit manually calling the executable. I thought about generating a bat script similar but it seemed a relatively bigger change considering only `simulate` being called.

Does OMEdit use `buildModel` or does it call `translateModel` and then manually builds the generated code? If it calls `buildModel` then we can maybe get away without having to generate the script. 

That said, it might be better to generate the scripts since that means we can also run the simulation from command line just as easily without having to worry about the DLL locations.

**Comment by sjoelund** [comment]
It uses `translateModel` so that compilation of C-files can be stopped easier

**Comment by mahge** [comment]
Okay. Makes sense. 

Then we should go with the scripts and cover all possible cases. We already have the information so it should just be writing it out at a proper stage and updating the `simulate` and friends APIs to call that on Windows.

**Pull request merged**
